az-digital/az_quickstart

.lando.yml
.probo.yaml

This pull request updates the URLs that are used for building local development dependencies to use the github urls rather than the bitbucket urls.

UADIGITAL-2211: Update Repository Workflow in Local Development

---

README.md

Creating a basic pull request to see how the GitHub process works.

Update readme with basic Quickstart info

---

.github/CODEOWNERS

Using the maintainers team for all files as a starting point.  Fixes #11.

feature/11: Added CODEOWNERS file.

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/spike.md
.github/ISSUE_TEMPLATE/task.md
.github/ISSUE_TEMPLATE/user_story.md

...and edit bug report & feature request for consistent formatting

Add User Story, Task & Spike templates to github issues #20 

---

composer.json

Was also just looking for a way to test that our CODEOWNERS file is working.

Fixes #22.  Replaced uadigital.arizona.edu with digital.arizona.edu in composer.json.

---

CONTRIBUTING.md
COPYRIGHT.txt

See https://github.com/az-digital/az_quickstart/issues/31
https://github.com/az-digital/az_quickstart/issues/31
Hoping probo checks will do the work for me  : )

Drupal 8 Coding Standards on CONTRIBUTING.md and COPYRIGHT.txt

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md

As requested here https://github.com/az-digital/az_quickstart/pull/21#issuecomment-580920521 we'd like to follow drupal.org's example and include "Proposed Resolution" to our feature and bug fix requests
https://github.com/az-digital/az_quickstart/issues/27
https://github.com/az-digital/az_quickstart/pull/21
n/a

Add "Proposed Resolution" to issue bug and feature templates

---

.gitattributes

Fixes #36 
Tested in private fork of AZ Quickstart.  Seems to improve detection of files.

Fixes #36: Added .gitattributes to help GitHub classify various files correctly.

---

composer.json
modules/custom/az_layouts/config/install/layout_builder_styles.style.az_accordion.yml
modules/custom/az_layouts/config/install/layout_builder_styles.style.az_align_content_right.yml
modules/custom/az_layouts/config/install/layout_builder_styles.style.az_background_azurite.yml
modules/custom/az_layouts/config/install/layout_builder_styles.style.az_background_transparent_black.yml
modules/custom/az_layouts/config/install/layout_builder_styles.style.az_background_transparent_sky.yml
modules/custom/az_layouts/config/install/layout_builder_styles.style.az_background_transparent_white.yml
modules/custom/az_layouts/config/install/layout_builder_styles.style.az_bg_blue.yml
modules/custom/az_layouts/config/install/layout_builder_styles.style.az_bg_cool_gray.yml
modules/custom/az_layouts/config/install/layout_builder_styles.style.az_bg_red.yml
modules/custom/az_layouts/config/install/layout_builder_styles.style.az_bg_triangles_centered.yml
modules/custom/az_layouts/config/install/layout_builder_styles.style.az_bg_triangles_top_left.yml
modules/custom/az_layouts/config/install/layout_builder_styles.style.az_bg_triangles_top_right.yml
modules/custom/az_layouts/config/install/layout_builder_styles.style.az_bg_triangles_trilines.yml
modules/custom/az_layouts/config/install/layout_builder_styles.style.az_card.yml
modules/custom/az_layouts/config/install/layout_builder_styles.style.az_card_deck.yml
modules/custom/az_layouts/config/install/layout_builder_styles.style.az_full_width.yml
modules/custom/az_layouts/config/install/layout_builder_styles.style.az_margin_bottom_1.yml
modules/custom/az_layouts/config/install/layout_builder_styles.style.az_margin_bottom_2.yml
modules/custom/az_layouts/config/install/layout_builder_styles.style.az_margin_bottom_3.yml
modules/custom/az_layouts/config/install/layout_builder_styles.style.az_margin_bottom_4.yml
modules/custom/az_layouts/config/install/layout_builder_styles.style.az_margin_bottom_5.yml
modules/custom/az_layouts/config/install/layout_builder_styles.style.az_section_align_items_center.yml
modules/custom/az_layouts/config/install/layout_builder_styles.style.az_section_margin_bottom_3.yml
modules/custom/az_layouts/config/install/layout_builder_styles.style.az_section_margin_bottom_5.yml
modules/custom/az_layouts/config/install/layout_builder_styles.style.az_section_vertical_padding_10.yml
modules/custom/az_layouts/config/install/layout_builder_styles.style.az_section_vertical_padding_5.yml
modules/custom/az_layouts/config/install/layout_builder_styles.style.az_vertical_padding_10.yml
modules/custom/az_layouts/config/install/layout_builder_styles.style.az_width_50.yml

Adds patch submitted by module maintainer which adds weights to layout builder style config entities and updates existing exported layout builder styles with weights to make order more predictable in Layout Builder UI.
Fixes #46.
Tested locally with Lando.

Fixes #46: Adds Layout Builder Styles ordering patch.

---

composer.json

I realized too late that the patch that was actually committed by the Layout Builder Styles maintainers for [d.o. issue 3080384](https://www.drupal.org/project/layout_builder_styles/issues/3080384) was actually a little different than the one we added in #47.  This adds the actual patch that was committed by the maintainers to AZ Quickstart.
Fixes #46 (again).

Fixes #46: Use more recent Layout Builder Styles ordering patch.

---

composer.json

Updates Drupal core to version 8.8.4 for [SA-CORE-2020-001](https://www.drupal.org/sa-core-2020-001)
Fixes #56

Fixes #56: Updated Drupal core to version 8.8.4 for SA-CORE-2020-001.

---

composer.json

Update Drupal core to latest bugfix/patch version.
#147 
Confirmed that local composer install still works (including existing core patch) using lando:
```
- Installing drupal/core (8.8.5): Loading from cache
- Applying patches for drupal/core
https://www.drupal.org/files/issues/2020-02-12/1461322-20.patch (ajax css load order issue)
```

Fixes #147: Updated Drupal core to version 8.8.5.

---

CONTRIBUTING.md

Before I forget, adding some basic instructions for getting phpunit testing to work in local dev environments.
#66 
This is documentation

Adding some basic instructions for phpunit testing.

---

README.md

Closes #68 by adding bullets below Readme's How to contribute section

---

.github/ISSUE_TEMPLATE/task.md

The current description "Work that doesn't require a pull request." isn't accurate. This recommends a more general / catch-all description "Work that needs to be done."
https://github.com/az-digital/az_quickstart/issues/73

Change description of task issue type -- Closes #73

---

.ddev/commands/web/phpunit
.lando.yml
CONTRIBUTING.md

- Adds `phpunit` lando tooling command and phpunit DDEV script that provide the necessary options to run PHPUnit with the correct bootstrap config, etc
#66 
#156 
Tested locally with lando.  Haven't actually tested the DDEV script yet, but I believe it should work.

Fixes #156: Added Lando & DDEV tooling for PHPUnit.

---

modules/custom/az_cas/config/install/cas.settings.yml
modules/custom/az_cas/tests/src/Functional/AzCasTest.php

- Provides default values for new CAS module error message settings
#161 
Tested locally using lando:
- composer install
- phpcs
- phpunit
- drupal-check
- manual functional testing

Fixes #161: Provide UArizona-specific default values for new CAS module settings.

---

.github/ISSUE_TEMPLATE/feature_request.md
.github/PULL_REQUEST_TEMPLATE/pull_request_template.md

I've added Roles and Permissions considerations to our feature request and pull request templates
Closes #158 
#158 
No functional changes. Have reviewed the new markdown files.

Adds roles and permissions considerations to our templates

---

.ddev/commands/web/install
.lando.yml
.probo.yaml
CONTRIBUTING.md

Add admin user credentials to contributing doc

---

composer.json

Updates Drupal core to version 8.8.6 (security update addressing SA-CORE-002 and SA-CORE-003).
#203

Fixes #203: Updated Drupal core to version 8.8.6 for SA-CORE-002.

---

themes/custom/az_barrio/css/style.css

Fixes #192 
Min-width for search box changed to 576px to allow for more top margin before eliminating it on mobile.
Tested locally.

Set search box margin to min-width 576px.

---

az_quickstart.info.yml
composer.json

Fixes #216 by adding Token module to facilitate token replacements.
Tested locally.

Add Token module.

---

composer.json

Fixes #235: Updated Drupal core to version 8.8.8 for SA-CORE-2020-004, SA-CORE-2020-005 & SA-CORE-2020-006 (security updates).

---

themes/custom/az_barrio/az_barrio.theme
themes/custom/az_barrio/theme-settings.php

Fixes #174 by changing includes statement and adding a phpcs comment to
ignore specific test producing the warning in the theme files.
Tested locally with Lando.
Changed the includes statements in the two theme files producing phpcs warnings.

Change include statement to reduce phpcs warnings

---

.ddev/commands/web/phpunit
.gitattributes

Fixes #237 by specifying an end-of-line designation for the DDEV phpunit command and re-adding the phpunit file with WSL.
#66 
#156 
Tested locally with DDEV on Windows.

Update gitattributes EOL designation for phpunit.

---

.ddev/commands/web/install
.eslintrc.json
.lando.yml
.probo.yaml
composer.json
modules/custom/az_cas/az_cas.info.yml
modules/custom/az_demo/migrations/az_demo_menu_links.yml
modules/custom/az_media/config/install/media.type.az_remote_video.yml

Copied backwards-compatible (D8-compatible) changes from PR #221 and updated Drupal core to 8.9.x
#220 
Locally with Lando.

#220: Update Drupal core to 8.9.x and apply backwards-compatible D9 changes

---

composer.json

- Updates core to 9.0.5
- Resolves false-positive symfony/http-kernel vulnerability warnings showing up in our security checks.
#307 
Locally with Lando.

Fixes #307: Update Drupal core to version 9.0.5.

---

.ddev/commands/web/install
.github/workflows/security.yml
.lando.yml
.probo.yaml
README.md
composer.json
themes/custom/az_barrio/includes/common.inc
themes/custom/az_barrio/theme-settings.php

- Replaced references to `master` branch with `main`
- Added `2.x-dev` alias for `main` branch, which should allow other projects to `compser require az-digital/az_quickstart:2.*`
#311 
Needs testing

#311: Replaced references to master branch with main.  Set up numeric branch alias for main branch.

---

composer.json

Updates Drupal core for:
https://www.drupal.org/sa-core-2020-007 - moderately critical
https://www.drupal.org/sa-core-2020-008 - moderately critical
https://www.drupal.org/sa-core-2020-009 - critical
https://www.drupal.org/sa-core-2020-010 - moderately critical
https://www.drupal.org/sa-core-2020-011 - moderately critical
#326 
ProboCI FTW

Fixes #326: Updated Drupal core to version 9.0.6 for SA-CORE-2020-007, SA-CORE-2020-008, SA-CORE-2020-009, SA-CORE-2020-010, SA-CORE-2020-011.

---

modules/custom/az_demo/tests/src/Functional/AZDemoContentTest.php
modules/custom/az_paragraphs/tests/src/Functional/AZParagraphsTest.php

Applied suggested changes from Drupal.org change record (https://www.drupal.org/node/2909426) to our existing test classes.
#346 
ProboCI FTW.

Fixes #346: Changed visibility of $modules property on test classes to protected.

---

.github/workflows/create-upload-release.yml
.github/workflows/security.yml

Use env file instead of set-env

---

.probo.yaml
composer.json

Update composer.json with minimum version numbers that are compatible with composer 2.0

---

.gitignore

Closes #361 
#361 
```
lando ssh  --user root
sudo apt-get update
sudo apt-get install vim
```
edit a file in vim
```
git status
```
see no extra vim files.

Add local-settings and Vim settings to .gitignore

---

.ddev/commands/web/install
.lando.yml
.probo.yaml

Renames fallback branch names in Probo, lando, and ddev config files to '2.0.x'.

Updated main references to 2.0.x.

---

composer.json
themes/custom/az_barrio/includes/common.inc

Update arizona-bootstrap version until we have automated process

Update arizona-bootstrap v2.0.5

---

.github/workflows/create-upload-release.yml
.github/workflows/security.yml

This change uses https://github.com/shivammathur/setup-php to set the PHP version of this action to 7.3
This will close issue #421

Set actions PHP version to 7.3

---

themes/custom/az_barrio/config/install/az_barrio.settings.yml
themes/custom/az_barrio/config/optional/block.block.az_barrio_search.yml
themes/custom/az_barrio/templates/page.html.twig

Closes #425 
- Added classes within the az_barrio theme settings interface under Layout / Region / UA header utilities
- Put the search block into UA header utilities on install
- Did not implement any design.

Move search block to red bar and hide it on mobile

---

.github/workflows/arizona-bootstrap-release.yml

This action should create a new branch, update the version number of arizona bootstrap in composer.json, commit the change, and open a new PR.
Closes #332

Add action to create PR for new Arizona Bootstrap releases

---

.github/workflows/create-upload-release.yml

This update converts the release action to have a manual trigger which will accept a version number as input.

Create Release Action

---

themes/custom/az_barrio/az_barrio.theme

Remove unneeded footer styles.
Closes #438

Unset bootstrap_barrio site-footer css

---

composer.json

https://www.drupal.org/sa-core-2021-001
#455

Closes #455: Updated Drupal core to version 9.1.3 for SA-CORE-2021-001.

---

composer.json
modules/custom/az_card/az_card.info.yml
modules/custom/az_media/az_media.info.yml
modules/custom/az_media/config/install/core.entity_form_display.media.az_image.default.yml
modules/custom/az_media/config/install/core.entity_form_display.media.az_image.media_library.yml
modules/custom/az_media/config/install/crop.type.az_card_image.yml
modules/custom/az_media/config/install/image.style.az_card_image.yml
modules/custom/az_media/config/install/media.type.az_image.yml

Adds cropping functionality to Quickstart.
This PR adds the [Crop API](https://www.drupal.org/project/crop) and [Image Widget Crop](https://www.drupal.org/project/image_widget_crop) modules to the installation profile, which are the current most common cropping implementations in D9. A crop is added for card images, which are in use on the card paragraph type and the view at `/people`.
#411 
To test, do the following:
- Go to `/admin/config/media/crop` and verify that the Card Image crop type exists.
- Go to `/admin/config/media/image-styles/manage/az_card_image` and verify that the card image style is using the Card Image crop.
- Add a Person, fill out required fields
- Click `Add media`
- Upload an image and fill out alt text
- Verify that the `Crop Image` dropdown exists on the media …

Fixes #411: Add cropping module to Install Profile

---

.github/pull_request_template.md

Currently, the first item under Checklist is not clear and often confusing, especially to new contributors. This PR hopes to make the contribution process more clear.
#469 
This has not been tested as it is simply a change to the template markdown file.

#469: Fix Github PR template to be more clear

---

.github/workflows/arizona-bootstrap-release.yml

Configure git before creating PR

---

modules/custom/az_core/az_core.module

Toolbar quickstart version indicator implementation created during local development workflow demo in 2020-11-04 workshop.
#338

#338: Add Quickstart 2.0 indicator to toolbar.

---

composer.json

This should fix GitHub's Dependabot for the az_quickstart repo.
See https://github.com/az-digital/az_quickstart/network/updates/88928942
#522 
Impossible to test until we merge, I'm afraid.

Closes #522: Configure composer minimum-stability to fix Dependabot.

---

.ddev/commands/web/phpcbf
.gitattributes
.gitignore
.lando.yml
modules/custom/az_mail/az_mail.module
modules/custom/az_mail/src/commands/AZMailCommands.php
modules/custom/az_paragraphs/src/Plugin/paragraphs/Behavior/AZTextWithMediaParagraphBehavior.php
themes/custom/az_barrio/theme-settings.php

Adds PHPCBF tooling, adds `.phpcs-cache` to .gitignore, fixes various existing coding standards issues.
#466 
Locally with lando

Closes #466: Added lando/DDEV tooling for PHPCBF and fixed various PHPCS issues.

---

modules/custom/az_event/az_event.info.yml
modules/custom/az_event/config/install/core.entity_view_display.node.az_event.az_card.yml
modules/custom/az_event/config/install/views.view.az_events.yml
themes/custom/az_barrio/config/optional/block.block.views_block__az_events_az_sidebar.yml

Initial work on views and styling for Event Card Group and Sidebar Event Block
This is ready!
Created Grid View (block) on the Events View:
And the Grid Sidebar:
Some questions:
-In QS 1 both of the blocks use the card display - is that desirable? If summaries are entered it takes up a lot of space when displayed on the node (often longer than the actual event content in the main content region)
-I haven't been able to get Event Card Group to actually create cards of equal height (despite trying multiple things). Does this matter? (we currently don't have the grid views with cards for person or news having equal height, but it would be nice eventually)
-You can see from the screenshot that things look a bit strange for repeating dates. What is the desired behavior here? (calendar view …

Event Card Group and Sidebar (Closes #548 & #549)

---

composer.json
modules/custom/az_media/config/install/filter.format.az_standard.yml

https://github.com/az-digital/az_quickstart/issues/534

#534 & #539: Add patch to resolve issue where user can't switch view modes on embedded media

---

themes/custom/az_barrio/css/style.css
themes/custom/az_barrio/css/uaqs_navigation_overlay_menu_scroll.css

Move overlay_menu_scroll fix to appropriate file in media query

---

composer.json

https://www.drupal.org/sa-core-2021-002
This also includes 9.1.6 since we haven't merged #666 yet.
#665, #667
ProboCI FTW!

Closes #665, Closes #667: Update Drupal core to 9.1.7 for SA-CORE-2021-002 (critical security update).

---

composer.json

When logged in via cas, you are presented with an exception when trying to log out.
This PR adds a patch that should resolve the exception encountered when trying to log out.
Closes #640

Resolve ServiceNotFoundException when logging out

---

modules/custom/az_flexible_page/az_flexible_page.install

Adds DB update function for @smayden's existing #681 PR.
#573

Added DB update function to enable new az_flexible_page module depdencies.

---

composer.json

Update to latest Drupal core bugfix release (9.1.8).  AFAICT, all of our existing core patches are still needed although I had to use a newer version of the patch for the [core menu editing UX issue](https://www.drupal.org/project/drupal/issues/2957953) similar to @trackleft's 9.2.x PR.
#712 

Fixes #712: Update Drupal core to 9.1.8 (bugfix release).

---

composer.json

https://www.drupal.org/sa-contrib-2021-009
Fixes #731

Fixes #731: Update ctools to 8.x-3.6 for SA-CONTRIB-2021-009 (moderately critical security update).

---

themes/custom/az_barrio/az_barrio.info.yml

Goal: see the styles being applied while editing in the CKEditor.
Thank you @trackleft for the solution!
Closes #387

Closes #387: Add stylesheet reference for CKEditor

---

composer.json

This PR is to install Paragraph Admin Module Temporary to validate the list of paragraphs migrated.
This PR is to install Paragraph Admin Module Temporary to validate the list of paragraphs migrated.

Paragraph Admin module to see paragraph content

---

composer.json

The security update hasn't actually been published yet (as of 9:48 AM) but once it does, this _should_ be what we need.
#803 
We'll test once the update is actually released

Fixes #803: Updated Drupal core to 9.1.9 for SA-CORE-2021-003 / PSA-2021-05-25 (moderately critical security update).

---

modules/custom/az_migration/README.md
modules/custom/az_migration/az_migration.info.yml
modules/custom/az_migration/migrations/migrate_plus.migration.az_node_carousel.yml

Carousel Type Migration
You can test this in Probo build

Feature/734 - Carousel Migration

---

.github/workflows/review-site.yml

Attempt to resolve kitten install issues by waking the environment and sleeping before running drush site-install

Wake env before doing site install

---

.probo.yaml
composer.json

Added core patch for [known Drupal core issue](https://www.drupal.org/project/drupal/issues/3163925) that is making intermittent ProboCI PHPunit failures harder to troubleshoot / debug.
#766 
It's about to be tested in ProboCI.

Closes #766: Limit fastest to 10 parallel processes on ProboCI.

---

modules/custom/az_migration/migrations/migrate_plus.migration.az_node_person.yml

Fixes a typo in the migration file.

Fixes #808: Corrected typo in migrate_plus.migration.az_node_person.yml

---

.github/workflows/create-release.yml

This change will send a repo dispatch event notification to the upstream repo when a release occurs
https://github.com/az-digital/az-quickstart-pantheon/pull/18

Send notification to upstream on release

---

modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_jumbotron.yml
modules/custom/az_migration/src/Plugin/migrate/process/ParagraphsBehavior.php
modules/custom/az_migration/src/Plugin/migrate/process/ParagraphsJumbotronFieldMerge.php

Migrate Jumbotron paragraph type
Migrate Jumbotron paragraph type
Closes #778

Closes #778: Migration for D7 Jumbotron paragraph type (to AZ Text)

---

modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_single_card.yml
modules/custom/az_migration/src/Plugin/migrate/process/ParagraphsBehavior.php

Paragraph Single Card migration to az_paragraphs_cards
Paragraph Single Card migration to az_paragraphs_cards
Closes #787

Closes #787: Migration Paragraph Single Card to AZ Cards

---

composer.json

https://www.drupal.org/sa-contrib-2021-015
#847

Closes #847: Updated ctools module to 8.x-3.7 for SA-CONTRIB-2021-015.

---

composer.json
modules/custom/az_media/config/install/filter.format.az_standard.yml
themes/custom/az_barrio/az_barrio.theme

This PR turns on bootstrap utilities for table classes for the standard text format
QS2 is currently not using the bootstrap 4 classes for tables. This makes a configuration change to the Standard Text formatter to allow Bootstrap Utilities Table Classes. 
I also added more table classes to the allowed HTML tags so that more bootstrap classes can be used.
@trackleft has also fixed problems with conflicting table.css file and table styles applying to subsequent tables lower down the page.
Before:
After:
Possible future work outside of this ticket:
- Allow more classes to be specified in table properties (similar to QS1) – right now they have to be entered in the source code.
#795 
Tested in Probo and locally.
Probo test site: https://7b5e2985-cedf-4a13-ab91-3a35916c835d--pr-839.probo.build/ …

Closes #795: Make tables use bootstrap table classes

---

modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_callout.yml
modules/custom/az_migration/src/Plugin/migrate/process/ParagraphsBehavior.php
modules/custom/az_migration/src/Plugin/migrate/process/ParagraphsCalloutFieldMerge.php

Paragraph Migration for Callout to AZ text
Paragraph Migration for Callout to AZ text
Closes #780

Closes #780: Migration for D7 callout paragraph type (to text).

---

modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_column_image.yml
modules/custom/az_migration/src/Plugin/migrate/process/ParagraphsColumnImageFieldMerge.php

Migration for Paragraph Column Image to AZ Text
Migration for Paragraph Column Image to AZ Text

Closes #779: Migration for D7 column image paragraph type (to AZ Text).

---

themes/custom/az_barrio/az_barrio.theme
themes/custom/az_barrio/templates/layout/page.html.twig

Closes #871: Adding navbar-offcanvas class to array, not resetting the array.

---

themes/custom/az_barrio/az_barrio.theme
themes/custom/az_barrio/config/optional/block.block.az_barrio_messages.yml
themes/custom/az_barrio/config/schema/az_barrio.schema.yml
themes/custom/az_barrio/css/style.css
themes/custom/az_barrio/theme-settings.php

- Removes extra spacing above body content (#852)
- Removes external link styling theme setting (#854)
- Moves status messages to AZ Barrio help region (#863)
- ~Removes sidebar region menu style overrides (#864)~
#852 
#854 
#863

Closes #852, Closes #854, Closes #863: Misc Arizona Barrio improvements/fixes.

---

modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_full_width_media_row.yml
modules/custom/az_migration/src/Plugin/migrate/process/ParagraphsBehavior.php
modules/custom/az_migration/src/Plugin/migrate/process/ParagraphsFWMediaRowFieldMerge.php
modules/custom/az_migration/src/Plugin/migrate/source/AZParagraphsItem.php

Full Width Media Row Paragraph Migration
Full Width Media Row Paragraph Migration

Closes #785: Migration or D7 full-width media row paragraph type (to text on media).

---

modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_chucks_view.yml
modules/custom/az_migration/src/Plugin/migrate/process/ParagraphsChunksViewDisplayMapping.php

Paragraph Chunks View to az_paragraphs_view Migration
Paragraph Chunks View to az_paragraphs_view Migration

Closes #783: Migration for D7 views paragraph type.

---

.github/workflows/review-site.yml
.probo.yaml
az_quickstart.info.yml

Closes #881 
Verified terminus command works

Closes #881: Disable az_demo by default. Enable in Probo & Kitten.

---

config/install/user.role.az_content_editor.yml

Content editors can currently save content as published by default, but can not save unpublished drafts or publish unpublished content.
Content editors should be able to save content as either published or unpublished and be able to publish content that is set to unpublished. Granting them the 'Administer Content' permission (`administer nodes` in the file) gives them this ability and also retains the functionality where they can only delete their own content.
Note: we were hesitant to grant this for the alpha release of QS2 last fall, erring on the side of being less permissive. But we intended to do further testing/research. 'Administer Content' does warn:
However, as this [drupal issue discusses](https://www.drupal.org/project/drupal/issues/2842960), administer content may not be as …

Closes #901: Grant 'Administer nodes' permission to content editors

---

config/install/filter.format.basic_html.yml
config/install/filter.format.restricted_html.yml
config/install/user.role.anonymous.yml
config/install/user.role.authenticated.yml

This PR removes permission for restricted html (for the anonymous role) and basic html (for authenticated role).
Currently content editors and admins are seeing the basic and restricted html as text format options when editing content.
It appears that this is because basic html and restricted html are permitted for anonymous/authenticated roles (and all content editors/admins also have those roles).
Current permissions in QS 2:
Anonymous - restricted html
Authenticated - basic html
Content editor - standard
Content admin - full html (would also be able to use standard as they are assigned editor role as well)
Administrator - restricted, basic, standard, full
This PR changes things to:
Anonymous - none
Authenticated - none
Content editor - standard
Content admin - full html (would also be …

Closes #902: Removing basic restricted html permissions

---

themes/custom/az_barrio/css/style.css

Closes #929: Fix sidebar nav can't scroll on mobile (temporary fix).

---

modules/custom/az_paragraphs/az_paragraphs_text_media/templates/paragraph--az-text-media--default.html.twig

Closes #927: Fixing background on content for column (on text with media).

---

README.md

Closes #925: Add documentation for how to use/install Quickstart to README.

---

modules/custom/az_demo/az_demo.info.yml
modules/custom/az_migration/az_migration.info.yml

Closes #934: Label az_demo and az_migration as experimental modules.

---

composer.json

https://www.drupal.org/sa-core-2021-004
#952 
ProboCI, FTW

Closes #952: Updated Drupal core to 9.2.2 for SA-CORE-2021-004.

---

CONTRIBUTING.md

Closes #948 Update contributing docs with devel and theme debug settings.

---

themes/custom/az_barrio/templates/content/node--az-person--full.html.twig

Closes #956.
#956
Untested.  (ProboCI, FTW)

Closes #956: Make display of fields conditional in full az-person template.

---

RELEASES.md

This PR adds the word Draft to the top of our release policy and states to overall goals that we are trying to achieve.
#971

Closes #971: Mark RELEASES.md as draft

---

RELEASES.md

Updates core/contrib update policies in RELEASES.md (WIP)
#970

Closes #970: Update core/contrib update policies for Quickstart releases

---

composer.json

https://www.drupal.org/psa-2021-08-09
https://www.drupal.org/sa-core-2021-005
#976

Closes #976: Update Drupal core to 9.2.4 for SA-CORE-2021-005 (moderately critical security update).

---

modules/custom/az_event/config/install/core.entity_form_display.node.az_event.default.yml
modules/custom/az_seo/config/quickstart/core.entity_form_display.node.az_event.default.yml

Aligned az_event hide_date setting in az_seo version of az_event node create form, with the one in `az_event`
#1010 
Probo

Closes #1010 Aligned `az_event` `hide_date` setting in `az_seo` version of `az_event` node create form, with the one in `az_event`.

---

.ddev/commands/web/eslint
.ddev/commands/web/install
.lando.yml
.probo.yaml
modules/custom/az_event/js/az_calendar_filter.es6.js
modules/custom/az_event/js/az_calendar_filter.js
modules/custom/az_paragraphs/az_paragraphs_text_media/js/az_paragraphs_az_text_media_youtube.es6.js

Also updates node 12.x versions in various places.
#1016 
- Tested locally in lando
- Needs to be tested in Probo (once available)
- Needs to be tested with ddev

Closes #1016: Remove eslint-config-drupal-bundle (use existing javscript tooling instead) and apply ESlint fixes.

---

CONTRIBUTING.md

Adding more lando instructions to account for drupal hardening the permissions on install.
#1021
With lando

Closes #1021 Document how-to enable theme debugging.

---

composer.json

https://www.drupal.org/project/drupal/releases/9.2.6
#1029 
Needs testing.  (ProboCI FTW)

Closes #1029: Updated Drupal core to 9.2.6 (moderately critical security update).

---

composer.json

https://www.drupal.org/sa-contrib-2021-028
#1031 
Needs testing.

Closes #1031: Updated entity_embed module to 8.x-1.2 for SA-CONTRIB-2021-028 (moderately critical security update).

---

modules/custom/az_paragraphs/az_paragraphs_view/config/install/field.field.paragraph.az_view_reference.field_az_view_reference.yml

From Joe:
It didn't look to me like the field config in the field UI reflected your changes so I built your branch locally, changed the settings via the field UI and then re-exported the single config via the Configuration synchronization UI and applied the resulting config yml file changes

Re-exported field config via Configuration Synchronization UI.

---

modules/custom/az_demo/data/az_demo_page_node.json
modules/custom/az_demo/data/az_demo_remote_video.json
modules/custom/az_demo/data/az_demo_text_media_paragraph.json
modules/custom/az_demo/migrations/az_demo_remote_video.yml
modules/custom/az_demo/migrations/az_demo_text_media_paragraph.yml
modules/custom/az_paragraphs/src/Plugin/migrate/process/ParagraphsBehavior.php

Adding additional demo content to help us test more text on media use cases.
This also adds a fix for the migration of text on media spacing paragraph behavior field.
Closes #1048
Locally and on Probo https://7b5e2985-cedf-4a13-ab91-3a35916c835d--pr-1052.probo.build/pages/text-media

Closes #1048: Text on media with video demo content

---

composer.json
modules/custom/az_migration/migrations/migrate_plus.migration.az_node_news.yml

Remove from az_migration as well.

Remove field_az_caption from news migration

---

composer.json
modules/custom/az_migration/README.md
modules/custom/az_migration/migrations/migrate_plus.migration.az_menu_links.yml
modules/custom/az_migration/migrations/migrate_plus.migration.az_node_flexible_page.yml
modules/custom/az_migration/src/Plugin/migrate/process/MigratedPathLookup.php

- Provides QS1 > QS2 migration plugin for menu links (adapted from [this example](https://git.drupalcode.org/project/drupal/-/blob/9.2.x/core/modules/menu_link_content/migrations/d7_menu_links.yml) in Drupal core) which migrates menu link content for the following Quickstart menus:
| Quickstart 1 menu name | Quickstart 2 menu name |
| ----------- | ----------- |
|`main-menu`| `main`|
|`uaqs-utility-links` | `az-utility-links`|
|`uaqs-footer-information-for` | `az-footer-information-for`|
|`uaqs-footer-topics` | `az-footer-topics`|
|`uaqs-footer-resources` | `az-footer-resources`|
|`uaqs-footer-main` | `az-footer-main`|
- Provides new `MigratedPathLookup` migration process plugin which can be used to transform menu item link paths by looking up the ID of the associated migrated node or …

Closes #1065: Added migration for Quickstart menu links.  Closes #1127: Added marquees to flexible page migration.

---

modules/custom/az_migration/migrations/migrate_plus.migration.az_user.yml

Map all roles to authenticated.

Closes #1143 Migrated users are getting added as Administrators instead of Authenticated

---

modules/custom/az_migration/migrations/az_redirects.yml

This migrates redirects from a source site to a destination site.
Reused [MigratedPathLookup](https://github.com/az-digital/az_quickstart/blob/main/modules/custom/az_migration/src/Plugin/migrate/process/MigratedPathLookup.php) plugin provided for the menu migration
Skip row on use count = 0
Migrate marcomm site from pantheon to local
Compare redirects after migration
tested terms and nodes

Closes #1123 Migrate Redirects

---

modules/custom/az_migration/migrations/migrate_plus.migration.az_node_carousel.yml
modules/custom/az_migration/migrations/migrate_plus.migration.az_node_event.yml
modules/custom/az_migration/migrations/migrate_plus.migration.az_node_flexible_page.yml
modules/custom/az_migration/migrations/migrate_plus.migration.az_node_news.yml
modules/custom/az_migration/migrations/migrate_plus.migration.az_node_person.yml

Paths are migrated separately in migrate drupal to drupal, and therefore the existing d7_node plugin does not contain information for paths.
We have a plugin that extends d7_node called az_node, which does supply path information.
In this pr I switch out the node plugin and change the path settings to first disable pathauto on migrated content, and then set the path as it exists in the source site instead of the default set in pathauto.
Closes #1083 
Compare probo to kitten
* [Source](https://kitten.ltrr.arizona.edu/news/2021/09/could-mans-best-friend-be-mans-best-medicine
)
* [Migrated](https://539ea09d-510d-441c-9c7c-a9bab272154d--site-migration.probo.build/news/2021/09/could-mans-best-friend-be-mans-best-medicine
)
* [Source](https://kitten.ltrr.arizona.edu/events/23-weekend-canyon-runn …

Closes #1083 Ensure paths are migrated for all content types.

---

modules/custom/az_paragraphs/src/Plugin/paragraphs/Behavior/AZTextWithBackgroundParagraphBehavior.php

Should fix notices being generated by AZTextWithBackgroundParagraphBehavior.
#1162

Closes #1162: Fix notices being generated by Text with background paragraphs behavior.

---

modules/custom/az_news/az_news_feeds/az_news_feeds.install
modules/custom/az_news/az_news_feeds/az_news_feeds.links.task.yml
modules/custom/az_news/az_news_feeds/az_news_feeds.routing.yml
modules/custom/az_news/az_news_feeds/config/install/migrate_queue_importer.cron_migration.az_news_feeds.yml
modules/custom/az_news/az_news_feeds/src/Form/AzNewsFeedsAdminForm.php

Adding a form to the content section of the admin interface that allows for changing the url you are importing news content from.
You can visit it by going to /admin/content/az-news-feeds

Adding rudimentary UI for changing URL of news feed.

---

composer.json

#1169 
local build and some pantheon sites

Fixes #1169: Add Menu Link Attributes module

---

themes/custom/az_barrio/config/install/az_barrio.settings.yml

Remove classes from footer sub region that are only needed with the global footer.
Probo build: https://c2deb048-6b8c-49c1-9461-9976baac54d5.probo.build/
Closes #1204

Closes #1204: Removing problem classes from footer sub region (for now).

---

modules/custom/az_migration/README.md

As a developer running a quickstart 1 to quickstart 2 migration, I might not know that we are only migrating one link from the multi-value link field in cards, this documentation notes that.
#1156 
Update documentation

Adding more information to the cards migration readme.

---

composer.json

https://www.drupal.org/sa-core-2022-001
#1239 
Verified local composer install with lando (and that existing core patches still apply)

Closes #1239: Updated Drupal core to 9.2.11 for SA-CORE-2022-001 (moderately critical security update).

---

composer.json

https://www.drupal.org/sa-contrib-2022-004
https://www.drupal.org/project/jquery_ui_datepicker/releases/8.x-1.2
#1242 
Needs testing

Closes #1242: Update jQuery UI Datepicker to 1.2 for SA-CONTRIB-2022-004 (moderately critical security update).

---

themes/custom/az_barrio/az_barrio.libraries.yml
themes/custom/az_barrio/az_barrio.theme
themes/custom/az_barrio/css/az-barrio-off-canvas-nav.css
themes/custom/az_barrio/css/style.css
themes/custom/az_barrio/css/uaqs_navigation_overlay_menu_scroll.css

Ensures mobile buttons are clickable regardless of wordmark appearance setting being enabled
Closes #1222 
Probo

Closes #1222: Update min-height of red bar to accommodate different theme settings.

---

.ddev/commands/web/install
.github/workflows/security.yml
.lando.yml
.probo.yaml

2.1.x branch specific changes needed for CI and local development tool configs. This should only be merged into the `2.1.x` branch.

2.1.x branch-specific changes for CI configs.

---

RELEASES.md

We updated the definitions of minor and patch releases during the 2/4/2022 Friday meeting. Now we need to update the official RELEASES.md file.
https://docs.google.com/document/d/1iX6q713v0J9Tf0mLNAAea4ccDHGvh13qF-cOxySj05c/edit#
Closes #1283

Closes #1283: Update RELEASES.md

---

modules/custom/az_migration/src/Plugin/migrate/process/ParagraphsChunksViewDisplayMapping.php
modules/custom/az_migration/src/Plugin/migrate/process/ParagraphsColumnImageFieldMerge.php

Related files:
- [ParagraphsChunksViewDisplayMapping.php](https://github.com/az-digital/az_quickstart/blob/issue/1285-inline-document-migrate-plugins-kevin/modules/custom/az_migration/src/Plugin/migrate/process/ParagraphsChunksViewDisplayMapping.php)
- [migrate_plus.migration.az_paragraph_chucks_view.yml](https://github.com/az-digital/az_quickstart/blob/issue/1285-inline-document-migrate-plugins-kevin/modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_chucks_view.yml)
- [ParagraphsColumnImageFieldMerge.php](https://github.com/az-digital/az_quickstart/blob/issue/1285-inline-document-migrate-plugins-kevin/modules/custom/az_migration/src/Plugin/migrate/process/ParagraphsColumnImageFieldMerge.php)
- [migrate_plus.migration.az_paragraph_column_image.yml](https://github.c …

add code example for paragraphs_column_image_field_merge

---

composer.json

Addresses [SA-CORE-2022-003](https://www.drupal.org/sa-core-2022-003) and [SA-CORE-2022-004](https://www.drupal.org/sa-core-2022-004).
Drupal [9.2.13 releasee notes](https://www.drupal.org/project/drupal/releases/9.2.13)
Also includes [9.2.12 ](https://www.drupal.org/project/drupal/releases/9.2.12) which was for a Twig security update.
#1323 
Verified local composer install in lando

Closes #1323: Updated Drupal core to 9.2.13 for SA-CORE-2022-003 & SA-CORE-2022-004.

---

modules/custom/az_migration/src/Plugin/migrate/process/ParagraphMappingFlexiblePage.php

Refactoring ParagraphMappingFlexiblePage class to correctly process the condition in which there is more than one source value. 
Actually I have no idea if this is intended functionality for this class so please discuss.
https://github.com/az-digital/az_quickstart/issues/1278
Running this against my own migrations and finding that I'm able to successfully migrate data per the migration script in the linked issue.

Closes #1278: Refactoring ParagraphMappingFlexiblePage Class

---

.ddev/commands/web/install
.github/workflows/security.yml
.lando.yml
.probo.yaml

2.2.x branch specific changes needed for CI and local development tool configs. 
The destination branch for this PR should be changed to the `2.2.x` branch once it is created.  This should _only_ be merged into the `2.2.x` branch.
#1367 

#1367: 2.2.x branch-specific changes for CI configs.

---

.ddev/commands/web/install
.github/workflows/security.yml
.lando.yml
.probo.yaml

Enable CI builds to use matching branch name in az-quickstart-dev repo if it exists.
#876

Closes #876: Enable testing of related az-quickstart-dev branches in main repo CI builds.

---

composer.json

https://www.drupal.org/sa-core-2022-006
https://www.drupal.org/project/drupal/releases/9.2.16
#1421 

Closes #1421: Update Drupal core to 9.2.16 for SA-CORE-2022-006.

---

.probo.yaml
modules/custom/az_migration/migrations/migrate_plus.migration.az_node_flexible_page.yml

In Quickstart 1 Paragraphs and Field Collections reside in separate tables in the database, yet they both use `item_id` as their unique identifier, which leads to collisions when combining them into the same field during migration.
Additionally, field collections can not be added to paragraph reference fields in QS1, nor is there a field on flexible pages for contacts, which make this an easy choice. Remove contacts from the page migration altogether.
Fixes #1232 
Locally, using the UXUA database which has many contacts attached to events and many paragraphs.
On Probo you can see the fix in action here: https://857e6bb8-25f6-41cf-89a8-5478c551094e--site-migration.probo.build/uaqs_flexible_page
In previous migrations it looks like this.
**Arizona Quickstart** (install profile, custom …

Fixes #1232 Optionally add html paragraphs to migration lookup, and remove contacts from page migration.

---

modules/custom/az_cas/config/quickstart/cas.settings.yml
modules/custom/az_core/tests/src/Functional/ConfigOverrideTest.php

closes #1426 
Changed default CAS hostname to shibboleth.arizona.edu.
I deployed a local stack via `lando start` and was able to authenticate in via CAS.
I was unable to run `lando phpunit` as it seemed to never complete. I aborted it after 90 minutes.
**Arizona Quickstart** (install profile)

Closes #1426: Change default CAS hostname to shibboleth.arizona.edu

---

.github/pull_request_template.md

Update PR template to include section for describing steps on how to test and clean up formatting
issue/1454

Closes #1454: Add steps to test to PR template.

---

modules/custom/az_carousel/src/Plugin/Block/AZCarouselNotice.php
modules/custom/az_person/src/Plugin/Block/AZPersonReorderNotice.php

Closes #1394 
Locally
- [] My change requires a change to the documentation.

Closes #1394: Updating views re-order notice blocks to use render arrays and Url::fromRoute.

---

modules/custom/az_migration/migrations/migrate_plus.migration.az_node_person.yml

Adds `strip_tags` callback to address field in existing person migration.
Closes #986 
- Create archives of database and files from D7 site containing address fields with HTML tags
- Follow directions for creating and configuring a local dev site using scaffolding repo in [AZ Migration README](https://github.com/az-digital/az_quickstart/tree/main/modules/custom/az_migration#using-the-quickstart-scaffolding-repo-recommended) using D7 site archives
- Update Quickstart version reference in composer.json to use this PR branch:
```
composer require "az-digital/az_quickstart:dev-issue/986"
```
- Try importing `az_migration` group with `lando drush mim --group=az_migration`
- Create a Pantheon sandbox site using Quickstart 2 upstream
- Add the [raw diff file of this …

Closes #986: Strip HTML tags from Person address field during migration.

---

composer.json
modules/custom/az_demo/data/az_demo_event_node.json
modules/custom/az_demo/migrations/az_demo_event_node.yml
modules/custom/az_demo/migrations/az_demo_menu_links.yml

Smart date module updates introduced some new features for timezones that interfere with our demo content migrations.
Additionally, `az_demo_menu_links` migration errors because the bundle is being set to null because there is no `menu_link_content` source field.  So we should change that to use the default_value process plugin instead.
Fixes #1366 
View [this node on probo](https://d092ca03-0bb4-4339-b539-84f6e7cf1071.probo.build/events/weekend-canyon-running-training), see if recurring event info still gets imported correctly.
Updated smart_date to 3.5.1 from 3.4.3
Added patch fixing new issue from 3.5.0
Remove unneeded code from data json file for smart date migration.
Fix menu_link_content migration by setting the bundle on migrated menu_link_content entities. …

Closes #1366 Allow upgrade of smart_date and fix demo menu links migration.

---

composer.json

Adds Drupal core patch from existing d.o. issue: https://www.drupal.org/project/drupal/issues/3102249 that addresses issue with the `DrupalMedia` CKEditor plugin provided by the Drupal media module.
#1322 
1. Create a page
2. Add several text paragraphs with content in them
3. Save your page
4. Edit the page
5. Edit multiple paragraphs and make edits by clicking on "Source" in the ckeditor to edit the source code
6. Make changes to styles in the HTML code (e.g. classes on a paragraph, or heading styles) on multiple paragraphs
7. Save the page
8. Edit the page
9. Add images to two or more of the paragraphs
10. Save the page
11. Edit the page
12. Make changes to the images using the "Edit media" button (change alignment or size or both)
13. Make a text change in source mode to one of the …

Closes #1322: Add core patch to fix issue with CKEditor fields not always saving.

---

modules/custom/az_media/config/install/crop.type.az_full_width_bg_large.yml
modules/custom/az_media/config/install/image.style.az_full_width_bg_large.yml

Changing soft limit width(s) for az_full_width_bg_large image style / crop type.
Closes #1481

Closes #1481: Increase soft limit widths to 1920px for az_full_width_bg_large image style.

---

modules/custom/az_security/config/quickstart/antibot.settings.yml

Added default config overrides (Quickstart config) for optional Antibot module to az_security.
This is blocked by #1471.
Closes #1484 
- Install Antibot module
- Verify config overrides were imported correctly.

Closes #1484: Provide default Antibot module config overrides in Quickstart Security module.

---

CONTRIBUTING.md

Add info about PHPStan to contributing document.

---

.probo.yaml
az_quickstart.install
composer.json
config/install/user.role.az_content_editor.yml

- Adds [Environment Indicator](https://drupal.org/project/environment_indicator) module (included in Quickstart 1) as optional module
- Adds step to `az_quickstart_install()` to automatically install module during Quickstart install on if running on Pantheon
- Adds DB update to automatically install the module on existing sites running on Pantheon
- Adds `access environment indicator` permission to content editor role
- Adds step to enable and configure module in ProboCI
Closes #1501 
1. Login with azcontenteditor, azcontentadmin, or azadmin user
1.  Create sandbox site using AZ Quickstart upstream in Pantheon
3. Install Quickstart with drush (via terminus)
4. Create Pantheon test and live environments
5. Clone Pantheon site git repo
6. Add the [GitHub diff patch for this …

Closes #1501: Add environment_indicator module.

---

composer.json

Updates quick_node_clone to 1.15
Closes #1531 
`composer install`
General QA / regression testing
The security update for SA-CONTRIB-2022-038 checks for access before allowing certain actions.
https://git.drupalcode.org/project/quick_node_clone/-/commit/ae0ee56a23a10b478e135957551bef1d5ed9f2b6

Closes #1531 Update quick_node_clone to 1.15 for SA-CONTRIB-2022-038

---

.probo.yaml
modules/custom/az_core/src/Form/QuickstartCoreSettingsForm.php
modules/custom/az_migration/src/Plugin/migrate/process/ParagraphsExtraInfoFieldMerge.php
modules/custom/az_migration/src/Plugin/migrate/process/ParagraphsFWMediaRowFieldMerge.php
modules/custom/az_migration/src/Plugin/migrate/process/ViewsReferenceMapping.php
modules/custom/az_migration/src/Plugin/migrate/source/AZFileHandle.php
modules/custom/az_migration/src/Plugin/migrate/source/NodeWithFieldCollection.php
modules/custom/az_paragraphs/src/Plugin/Field/FieldFormatter/AZBackgroundMediaFormatter.php

- Addresses existing PHPCS warnings.
- Enabled PHPCS "Show sniff codes in all reports" option on ProboCI (prints rule name for each issue found)
Closes #1555
- Review ProboCI coding standards check reports
- Basic sanity checks of ProboCI site

Closes #1555: Cleanup existing PHPCS warnings ahead of 2.3.0.

---

.ddev/commands/web/install
.github/workflows/security.yml
.lando.yml
.probo.yaml

Step 4 to prepare for 2.3.0 minor release
https://github.com/az-digital/az_quickstart/wiki/Steps-to-create-minor-release
#1561 
ProboCI tests should pass.

#1561: 2.3.x branch-specific changes for CI configs.

---

modules/custom/az_media/config/install/crop.type.az_full_width_bg_large.yml

This was updated in https://github.com/az-digital/az_quickstart/commit/24d5705f02118d9e274699d7c78461f8dfdddddc#diff-2cbaea03aad0944bbea582aed87c2ee10813dd8d175734a0923d2628254b31a9L8
Looks like we forgot to update the description for the crop type when we updated our crop limits.

Update text in description of crop type `az_full_width_bg_large`

---

modules/custom/az_paragraphs/css/az_paragraphs_full_width.css
modules/custom/az_paragraphs/js/az_paragraphs_full_width.es6.js
modules/custom/az_paragraphs/js/az_paragraphs_full_width.js

Closes #1584 by ensuring that bottomMargin is a number and that sidebarTopMargin is a string ending in "px". Previously, when bottomMargin was a string like "48px", the sidebarTopMargin value would be incorrect. As part of this change, a default value of 0 was added for the CSS custom property --sidebar-top-margin.
#1584 
Create a page with fullwidth paragraphs that also have a bottom margin set. Add the page to a menu so that a sidebar will be displayed. The sidebar should be pushed down just below the last fullwidth element.

Closes #1584: Fix sidebar nav top margin calculation

---

composer.json

https://www.drupal.org/sa-contrib-2022-042
Closes #1598 
- Test embedding entities in text areas
- 

Closes #1598: Update embed to 8.x-1.5 for SA-CONTRIB-2022-042.

---

composer.json

Drupal 9.2.x PR for 2.2.x and 2.1.x
#1600 
General QA

#1600: Update Drupal core to 9.2.20 for SA-CORE-2022-010/CVE-2022-29248.

---

modules/custom/az_paragraphs/az_paragraphs.install

Return early if no update is needed instead of dividing by zero.

Closes #1627 Skip az_paragraphs update if there are no paragraphs.

---

.gitpod.yml

Co-authored-by: Joe Parsons <471936+joeparsons@users.noreply.github.com>

Add initial Gitpod yml file

---

modules/custom/az_accordion/templates/az-accordion.html.twig

Adds the `.bg-white` class to the Accordion's `.card-body` to ensure fallback color-contrast is used.
Closes #1443 
Two parter fix with: https://github.com/az-digital/arizona-bootstrap/issues/489
https://7b5e2985-cedf-4a13-ab91-3a35916c835d--pr-1624.probo.build/
- Add a Flexible Block with a couple of Accordions.
- Change the text color in one of the Accordion's body to something obvious.
- Add a Page with a Text with Background component, using a dark background color. Embed your Flexible block within the text editor of that Text with Background component. 
- Save and page and ensure proper text color is used (fallback AND manually changed text color).
- Minor release …

Closes #1443 - Add bg-white to accordion's card-body

---

composer.json
modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_callout.yml
modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_card_deck.yml
modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_carousel.yml
modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_chucks_view.yml
modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_column_image.yml
modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_content_marquee.yml
modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_extra_info.yml
modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_file_download.yml
modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_full_width_bg_wrapper.yml
modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_full_width_media_row.yml
modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_gallery.yml
modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_headed_text.yml
modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_html.yml
modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_jumbotron.yml
modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_panel_group.yml
modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_plain_text.yml
modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_single_card.yml
modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_well.yml
modules/custom/az_migration/src/Plugin/migrate/source/AZParagraphsItem.php

Testing patch for Paragraphs 1.14 migrate plugin issues.
Closes #1544

Closes #1544: Add workaround and patch for Paragraphs 1.14 migrate plugin issues.

---

composer.json

Related to #1660
This also includes drupal 9.3.15 https://www.drupal.org/project/drupal/releases/9.3.15

Security Issue #1660 Update Drupal core to 9.3.16 for SA-CORE-2022-011

---

composer.json

Security Issue #1660  Update Drupal core to 9.2.21 for SA-CORE-2022-011

---

modules/custom/az_person/config/install/field.field.node.az_person.field_az_email.yml
themes/custom/az_barrio/templates/content/node--az-person--az-card.html.twig

Closes #1328 by:
- Adding the Bootstrap `text-truncate` class to the email address when an AZ Person node is displayed as a card
- Adding help text to the AZ Person email field to encourage the use of @arizona.edu addresses
#1328 
- With the demo content enabled, go to the [Directory Grid people page](https://231c0487-1988-4b05-b074-8fc6a909b36d.probo.build/people) and confirm that long email addresses are being truncated with ellipses instead of being wrapped around to the next line
- Create or edit an AZ Person node and confirm that new help text is present under the email text field (suggestions welcome for revisions!)

Closes #1328: Truncate long emails on card displays of AZ Person

---

config/install/user.role.authenticated.yml

This PR is to fix issue #1489  [Media permission denied for authenticated user role](https://github.com/az-digital/az_quickstart/issues/1489)

Closes #1489: Fix media permission denied for authenticated user role.

---

composer.json

https://www.drupal.org/project/drupal/releases/9.3.17
Closes #1690 
- General testing

Closes #1690: Update Drupal core to 9.3.17.

---

.github/workflows/review-site.yml

Use Pantheon's Setup Terminus action to install latest version of Terminus and update PHP versions to 8.1
Closes #1707 
PR will have to be merged and a review site build will have to be triggered.

Closes #1707: Update Terminus and PHP versions in review site GH actions workflow.

---

.lando.yml

Updates the node version to a supported version (16) in the `.lando` file.
Closes #1719 

Closes #1719 - Update node version in `.lando` file

---

modules/custom/az_core/az_core.libraries.yml
modules/custom/az_core/az_core.module
modules/custom/az_core/css/claro-node-form-overrides.css

Adds CSS styles that override some Claro styles that were added in 9.4.x that make the content editing UI layout not ideal, especially for Paragraphs content.
Closes #1716 
Edit content, inspect UI

 Closes #1716: Add overrides for claro node form layout styles.

---

modules/custom/az_demo/data/az_demo_text_media_paragraph.json
modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_content_marquee.yml
modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_full_width_media_row.yml
modules/custom/az_paragraphs/az_paragraphs_text_media/az_paragraphs_text_media.install
modules/custom/az_paragraphs/css/az_paragraphs_az_text_media.css
modules/custom/az_paragraphs/src/Plugin/migrate/process/ParagraphsBehaviorSettings.php
modules/custom/az_paragraphs/src/Plugin/paragraphs/Behavior/AZTextWithMediaParagraphBehavior.php

Closes #1700
1. Add text on media paragraph types with varying content background color selections
2. Observe accessible title and body text colors

Closes #1700: Update text on media transparent classes

---

modules/custom/az_course/az_course.info.yml
modules/custom/az_course/config/install/core.entity_view_display.node.az_course.az_card.yml

- Adds experimental label to az_course module.
- Disables link to course nodes (until we decide what to display on them)
#1749 

#1749: Label az_course as experimental module and disable link to course nodes for now.

---

modules/custom/az_paragraphs/src/Plugin/paragraphs/Behavior/AZTextWithMediaParagraphBehavior.php

In #1727, we made some changes to how and when the full-width library is attached to full-width paragraph items but did not use the correct setting name in the text on media paragraphs behavior.
Thanks @bberndt-uaz for finding the problem (and solution).
Closes #1745 
Verify that full width paragraph items and the sidebar are rendered correctly on ProboCI.

Closes #1745: Use correct full-width setting name when adding full-width library.

---

composer.json

Updates Drupal core to latest bugfix release for 9.3.x.  This is a 2.3.x branch specific PR.  
https://www.drupal.org/project/drupal/releases/9.3.18
Closes #1736 

Closes #1736: Update Drupal core to 9.3.18.

---

composer.json

https://www.drupal.org/project/drupal/releases/9.4.3
Closes #1767 

Closes #1767: Update Drupal core to 9.4.3 (critical security update).

---

composer.json

https://www.drupal.org/project/drupal/releases/9.3.19
Closes #1766 

Closes #1766: Update Drupal core to 9.3.19 (critical security update).

---

modules/custom/az_card/src/Plugin/Field/FieldWidget/AZCardWidget.php
modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_full_width_bg_wrapper.yml
modules/custom/az_paragraphs/src/Plugin/paragraphs/Behavior/AZSplitScreenParagraphBehavior.php
modules/custom/az_paragraphs/src/Plugin/paragraphs/Behavior/AZTextWithBackgroundParagraphBehavior.php

Adds `bg-mesa` as option to background color setting for cards, text on background and split screen components.
Closes #1782
Ensure `Mesa` is a background color option for cards, text on background and split screen components and that it works.

Closes #1782: Add mesa as background color option to cards, text on background, and split screen.

---

composer.json
config/install/user.role.az_user_admin.yml

Adds new Role Delegation module [patch](https://www.drupal.org/project/role_delegation/issues/3299201) that addresses issue with delegated admins being able to remove/cancel full administrator user accounts.
Closes #1382 
1. Add one or more users with the `content editor`, `content admin`, or `user admin` roles
2. Add at least one additional user with the `administrator` role
3. Login as a user with the `user admin` role
4. Ensure that the delegated admin user has access to remove/cancel users with `content editor`, `content admin`, and/or `user admin` roles but _NOT_ users with the `administrator` role.

Closes #1382: Add role_delegation patch for restricting access to cancel/remove admin users

---

composer.json

Adds the Masquerade module to Quickstart. Masquerade allows for testing/debugging of the editors' experience while interacting with Quickstart.
Module is not enabled by default. A site admin must enable the module on the site and place its block.
Review site: https://7b5e2985-cedf-4a13-ab91-3a35916c835d--pr-1833.probo.build/
Closes #177 
1. Enable the Masquerade module
2. Place the Masquerade block in the desired region and configure to be viewable to "administrators" only
3. Masquerade as a lower level account (azcontenteditor or azcontentadmin)
4. Verify admin toolbar has been reduced to masqueraded account's permissions
5. Unmasquerade (button located in admin toolbar)
- Patch release …

Closes #177 - Adds masquerade module

---

modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_html.yml

Full html paragraphs allowed embedded enities, and when we are determining if a paragraph should remain an html paragraph or switched to a text paragraph, we forget to process the embedded entities.
If on az_quickstart 2.4.1 or below.
In an existing migration where the source site contains html paragraphs with embedded entities that should be converted to text paragraphs.
replace this file: https://raw.githubusercontent.com/az-digital/az_quickstart/issues/1839/modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_html.yml
Run the migration.
If on the master branch of az_quickstart, use this patch.
```
https://patch-diff.githubusercontent.com/raw/az-digital/az_quickstart/pull/1840.diff
```
- Minor …

Closes #1839 Add entity_embed_process plugin to field_az_text_area in az_paragraph_html migration.

---

composer.json

https://www.drupal.org/project/ctools/issues/3300682#comment-14647155
Closes #1841 

Closes #1841: "Downgrade" ctools to 8.x-3.11.

---

composer.json

- [drupal.org/project/drupal/releases/9.3.20](https://www.drupal.org/project/drupal/releases/9.3.20)
- [drupal.org/project/drupal/releases/9.3.21](https://www.drupal.org/project/drupal/releases/9.3.21)
Closes #1820 

Closes #1820: Update Drupal core to 9.3.21 (2.3.x only).

---

modules/custom/az_card/src/Plugin/Field/FieldWidget/AZCardWidget.php

Should resolve these PHPstan errors since we merged az-digital/az-quickstart-dev#50:
```
$ /src/az-quickstart-scaffolding/vendor/bin/phpstan analyse --configuration web/profiles/custom/az_quickstart/phpstan.neon web/profiles/custom/az_quickstart
------ ---------------------------------------------------------------------- 
Line   modules/custom/az_card/src/Plugin/Field/FieldWidget/AZCardWidget.php  
------ ---------------------------------------------------------------------- 
123    Call to an undefined method                                           
Drupal\Core\TypedData\TypedDataInterface::isEmpty().                  
166    Access to an undefined property                                       
Drupal\Core\TypedData\TypedDataInterface::$link_title.                
166    Access to an …
```

Closes #1848: Fix PHPstan errors since updating to phpstan-drupal 1.1.25.

---

.github/workflows/security.yml

Updates `symfonycorp/security-checker-action` in our Dependency check GH actions job in the `security.yml` workflow (to a working version).
Closes #1881 
Create a new PR (after this is merged)

Closes #1881: Fix broken Dependency check job in security.yml GH actions workflow.

---

.github/workflows/create-release.yml

Based on the [script steps](https://bitbucket.org/ua_drupal/ua_quickstart/src/7.x-1.0-alpha6/release.sh) we used to use to update info files in Quickstart 1 (a long time ago).  Needs to be tested (probably in a sandbox repo).
Closes #692 

Closes #692: Add version to info.yml during release action.

---

.github/workflows/create-release.yml

Uses GH token associated with a bot user (that we could add additional permissions to) when checking out repo in "Create release" actions workflow so that GH actions is able to push changes to our release branches (bypassing our branch protection rules).
This would also require adding our bot user to a more privileged team.
Closes #1891
We won't be able to test for real until after this is merged and we create another release.

Closes #1891: Use privileged GH token for 'Create Release' workflow.

---

modules/custom/az_paragraphs/az_paragraphs.libraries.yml

Adds `az_barrio/material-design-icons-sharp` as a dependency to the `az_paragraphs.preview` library to fix missing icons in accordions rendered inside paragraph previews.
Closes #937 
- Add some accordion paragraphs to a page.
- Edit the page and see if icons are present in paragraphs previews.

Closes #937: Fix missing icons in accordion previews.

---

config/install/easy_breadcrumb.settings.yml
themes/custom/az_barrio/az_barrio.theme
themes/custom/az_barrio/config/optional/block.block.az_barrio_breadcrumbs.yml
themes/custom/az_barrio/templates/navigation/breadcrumb.html.twig

Adds new breadcrumb class to home item.
Currently contains changes from #1889 as well since changing Easy breadcrumb settings is broken without those changes.
Closes #1864 
- Change Bootstrap version to latest dev
- Enable Easy breadcrumb "Include the current page as a segment in the breadcrumb" and "Include the front page as a segment in the breadcrumb" settings

Closes #1864: Add new breadcrumb-item-home class to front page segment.

---

composer.json

Step 2 from https://github.com/az-digital/az_quickstart/wiki/Steps-to-create-a-minor-release
This change has already been made in the release branches.

Update composer branch alias in preparation for 2.5.0 pre-release.

---

.ddev/commands/web/install
.github/workflows/security.yml
.lando.yml
.probo.yaml

Step 4 from https://github.com/az-digital/az_quickstart/wiki/Steps-to-create-a-minor-release
This PR is targeting the new `2.5.x` release branch.

Update fallback branch references in CI & local dev tools for 2.5.x branch.

---

composer.json

Critical security update for 2.3.x branch (Drupal 9.3): https://www.drupal.org/project/drupal/releases/9.3.22
#1942 

#1942: Update Drupal core to 9.3.22 for SA-CORE-2022-016 (critical security update).

---

composer.json

https://www.drupal.org/sa-core-2022-016
#1942 

#1942: Update Drupal core to 9.4.7 for SA-CORE-2022-016 (critical security update).

---

modules/custom/az_migration/migrations/migrate_plus.migration.az_node_uaqs_basic_page_to_az_page.yml
modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_full_width_media_row.yml
modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_uaqs_basic_page_to_az_page.yml
modules/custom/az_migration/src/Plugin/migrate/process/ViewsReferenceMapping.php

Consolidated migration bugfixes for patch release.

---

modules/custom/az_paragraphs/az_paragraphs_contact/config/install/paragraphs.paragraphs_type.az_contact.yml

Adding default paragraph behavior to contact paragraphs.
#1976 
Create flexible page
Add contact
See if there are bottom spacing options
Use bottom spacing options
See if they are reflected on the front end.

Closes #1976 Add bottom spacing options to contact paragraphs

---

.github/pull_request_template.md

The markdown formatting recently changed and removed the bullets from the checklists under "Types of changes". This PR updates formatting to make scanning the checklists easier.

Update PR template formatting

---

modules/custom/az_paragraphs/az_paragraphs_view/config/install/field.field.paragraph.az_view_reference.field_az_view_reference.yml

Enables the 2 remaining view paragraph argumentsL
- Offset results
- Pagination
There is currently no documentation on the Quickstart website about offsetting and limiting views; it would be good to include these instructions on the Quickstart website once the feature is available on Quickstart.
Review site: https://7b5e2985-cedf-4a13-ab91-3a35916c835d--pr-2026.probo.build/
Closes #2025
- Add a view paragraph that references AZ Person Grid with a limit of 2
- Add another view paragraph that references AZ Person Grid with an offset of 2 and a limit of 3

Closes #2025 - Enable all views options on views paragraphs

---

.probo.yaml
config/install/user.role.administrator.yml
config/install/user.role.az_content_admin.yml
config/install/user.role.az_html_admin.yml
config/install/user.role.az_html_administrator.yml

- Adds the `HTML administrator` role
- Removes the `Use the Full HTML text format` permission from the `Content administrator` role
- Adds the `Use the Full HTML text format` permission to the `HTML administrator` role
This change should be communicated to site owners/administrators so they can ensure they re-assign the the new `HTML` role to those that previously had access.
Review site: https://7b5e2985-cedf-4a13-ab91-3a35916c835d--pr-2024.probo.build/
Closes #2023 

Closes #2023 - Add `HTML administrator` role and shift permissions

---

modules/custom/az_person/config/install/views.view.az_reorder.yml

Adds a notice to the header of the "Reorder People" view display to help provide clarity to content editors that changing sort order overrides alphabetical ordering.
Review site: https://7b5e2985-cedf-4a13-ab91-3a35916c835d--pr-2038.probo.build/admin/az-person/reorder-people?destination=/people
Closes #2035 
Open the Reorder People view and ensure and notice is there.

Closes #2035 - Include notice that "reordering overrides alphabetical sorting"

---

.github/workflows/review-site.yml
.probo.yaml
modules/custom/az_migration/README.md

Replaced drush en with drush install
Closes #1695 

Closes #1695: Replaced drush en with drush install

---

composer.json

Adds Drupal core patch for deprecation errors affecting the system status report on sites using a development version of Quickstart 2 running on PHP 8.1 (e.g. ProboCI sites).
Closes #2045
See also:
- https://www.drupal.org/project/drupal/issues/3255637 (patch comes from this issue)
- https://www.drupal.org/project/drupal/issues/3276589
1. Visit the system status report page (/admin/reports/status)
2. Verify no PHP errors are triggered / logged

Closes #2045: Add patch for Drupal core PHP 8.1 deprecation errors affecting status report.

---

modules/custom/az_migration/migrations/az_node_event.yml

Should fix PHP warnings during migrate:import operations on our `az_node_event` migration:
```
[warning] Undefined array key "url" FieldLink.php:142
[warning] Undefined array key "title" FieldLink.php:144
```
Fixes #2062 

Closes #2062: Skip migrate processing for event link field values if missing.

---

modules/custom/az_global_footer/az_global_footer.install
modules/custom/az_paragraphs/az_paragraphs.install
modules/custom/az_paragraphs/az_paragraphs_photo_gallery/templates/paragraph--az-photo-gallery.html.twig
modules/custom/az_paragraphs/az_paragraphs_text_background/az_paragraphs_text_background.install
modules/custom/az_paragraphs/az_paragraphs_text_media/az_paragraphs_text_media.install

Some of the changes identified in #2080 for Drupal 9.5.x / 10.x compatibility are things that can also be backported to Quickstart releases still using 9.4.x:
- Addressed Twig deprecations (see https://twig.symfony.com/doc/2.x/deprecated.html#tags)
> Adding an `if` condition on a `for` tag is deprecated in Twig 2.10. Use a `filter` filter or an "if" condition inside the "for" body instead (if your condition depends on a variable updated inside the loop). 	
- Added explicit access checks to entity queries for https://www.drupal.org/node/3201242 (deprecation introduced in Drupal 9.2.x)
#1938
- General testing to make sure no regressions introduced
- Test Photo gallery paragraph type since it's template file was updated
- **Other or …

#1938: Backportable changes from Drupal 9.5.x compatibility updates.

---

themes/custom/az_barrio/templates/layout/page.html.twig

This PR makes a small change to the page template in the AZ Barrio theme so that the Content Top region is displayed if items are present in the Content Top region. Currently the template checks the Breadcrumb region instead.
Closes #2140 
1. Add a block to the Content Top region
2. Confirm that it is displayed correctly even when the Breadcrumb block is disabled

Closes #2140 Fix condition for displaying Content Top region in page template

---

composer.json

https://www.drupal.org/sa-core-2023-001
https://www.drupal.org/project/drupal/releases/9.4.10
Closes #2144 

Closes #2144: Update Drupal core to 9.4.10 for SA-CORE-2023-001.

---

.github/workflows/arizona-bootstrap-release.yml
.github/workflows/create-release.yml

Update deprecated actions runner version to `ubuntu-latest`.
Closes #2156
Fixes #2155 
Create a forked copy of this repo
Add all of the secrets
Create a release
CI

Closes #2156, Fixes #2156: Ubuntu 18.04 actions runner is deprecated, update to ubuntu-latest

---

modules/custom/az_core/src/AZConfigOverride.php

Closes #2139 by changing the type for the logger_channel object to Psr\Log\LoggerInterface.
Closes #2139 by changing the type check for the logger_channel object to `Psr\Log\LoggerInterface`. This allows additional types of loggers (like Monolog) to be used.
- #2139
This shouldn't have any user-facing changes. It should allow users to utilize different loggers in code. The most visual change I could see is a Type error when trying to enable the Monolog Drupal contrib module. That error seems to be gone now. The error didn't actually stop me from using the module, but just a pesky error when enabling the module. …

Closes #2139 Update logger_channel object type

---

.github/pull_request_template.md
RELEASES.md

Adding our experimental module policy to the Release policy within this repository
Adding additional checkboxes to the pull-request template that cover this policy update.
Closes #2122
Documentation update, no testing required.

Closes #2122 Update release policy to cover experimental modules.

---

.probo.yaml

See #2110 
On Probo
Enables upgrade status
Generates a report
Closes #2110
Look in probo for the generated report.
CI

Closes #2110 Add Upgrade Status Report Step to Probo.

---

themes/custom/az_barrio/templates/layout/page.html.twig

Closes #2171 with the following changes:
- Remove template code related to the `featured_top`, `featured_bottom_first`, `featured_bottom_second`, and `featured_bottom_third` regions
- Update header description to refer to "Arizona Barrio's theme implementation" instead of Bootstrap Barrio
- Update list of regions in the header to reflect the template code and az_barrio.info.yml
#2171 
Verify that pages display as expected.

Closes #2171 Remove unused regions from AZ Barrio page template

---

.github/dependabot.yml

Enables dependabot for our GitHub actions workflows.
Closes #2157

Closes #2157: Enable dependabot for GitHub actions workflows.

---

modules/custom/az_event/css/az_calendar_filter.css

Adds max-width to select items in the "Category" dropdown filter within AZ Event views.
Closes #2188 
Review site: https://7b5e2985-cedf-4a13-ab91-3a35916c835d--pr-2189.probo.build/
1. Add a long taxonomy term to Event Categories list
2. Verify it doesn't break out of the parent container

Closes #2188 - Category filter exceeds allowed space

---

.github/workflows/create-release.yml
.github/workflows/review-site.yml
.github/workflows/security.yml

This PR updates the workflow files to use major versions of the Pantheon Terminus and Setup PHP community Github Actions.
Closes #2190 
Once merged, dependabot should no longer attempt to create PRs for minor version bumps for these two actions.

Closes #2190 Update workflow files to use major versions

---

modules/custom/az_course/az_course.links.menu.yml
modules/custom/az_course/az_course.routing.yml

Moves 'Import UA Courses' link in admin menu from 'System' to 'AZ Quickstart'.
Closes #2195
1. Login as admin user
2. Install AZ Course module
3. Go to Configuration
4. Verify 'Import UA Courses' link is in 'AZ Quickstart' section instead of 'System'.

Closes #2195: Move Import Courses link to Quickstart section of admin menu.

---

composer.json
themes/custom/az_barrio/includes/common.inc

See https://github.com/az-digital/arizona-bootstrap/releases/tag/v2.0.23

Update Arizona Bootstrap to 2.0.23

---

composer.json

Step 2 from https://github.com/az-digital/az_quickstart/wiki/Steps-to-create-a-minor-release
This change has already been made in the release branches.

Update composer branch alias in preparation for 2.6.0 pre-release.

---

.ddev/commands/web/install
.github/workflows/security.yml
.lando.yml
.probo.yaml

Step 4 from https://github.com/az-digital/az_quickstart/wiki/Steps-to-create-a-minor-release
This PR is targeting the new `2.6.x` release branch.

Update fallback branch references in CI & local dev tools for 2.6.x branch

---

modules/custom/az_event/az_event_trellis/az_event_trellis.info.yml

Adds minimal PHP version (8.0) to experimental Trellis Events integration module since that module's date processing code requires it.
Closes #2222 
- Try installing the experimental az_event_trellis module.  It should only install on environments using PHP 8.0+

Closes #2222: Require PHP 8.0+ for experimental Trellis Events integration module.

---

az_quickstart.install

Forces installation of block_class module since our re-exported config for 2.6.x now has config dependencies on the module.
Closes #2229 
- Ensure config_distro updates work without errors on an existing site that _does not_ have block_class installed before applying a 2.6.x pre-release.

Closes #2229: Ensure block_class module is installed.

---

composer.json

Still not entirely sure why dependabot hasn't created this PR automatically so I created it manually.
(Did not get generated in my local testing using the dependabot CLI either)
Closes #2234 

Closes #2234: Update drupal/smart_date from 3.6.1 to 3.7.0.

---

modules/custom/az_flexible_page/src/Form/AzFlexiblePageSettingsForm.php

Deleted three unused imports in AzFlexiblePageSettingsForm.php.
#2245
Confirm that the "AZ Page" form in Quickstart Settings works as expected.

Closes #2245 Unused imports in flexible page settings form

---

themes/custom/az_barrio/az_barrio.theme
themes/custom/az_barrio/config/optional/block.block.az_barrio_search.yml
themes/custom/az_barrio/css/style.css

Quickstart should not add  classes that the theme relies via block class configuration, unless a reasonable fallback exists.
Block class should be reserved for site builders, and not used for distribution managed css classes, because if a block is edited through the course of normal site building, the merge config strategy will no longer work, and Quickstart can no longer manage those classes.
#2251
Patch a site with composer
```
"extra": {
"patches": {
"az-digital/az_quickstart": {
"Quickstart issue #2251 ": "https://patch-diff.githubusercontent.com/raw/az-digital/az_quickstart/pull/2252.diff"
}
}
}
```
See if it resolves the issue. …

Closes #2251 Remove block_class config for `az_barrio_search` block and add `az-search-block` class via preprocess hook.

---

modules/custom/az_migration/migrations/az_node_event.yml
modules/custom/az_migration/migrations/az_node_news.yml

The migration process config for the `field_uaqs_link` source field in the news and events migrations are currently generating PHP warnings.
- The [core `field_link` process plugin](https://api.drupal.org/api/drupal/core%21modules%21link%21src%21Plugin%21migrate%21process%21FieldLink.php/class/FieldLink/9) used in these migrations expects both `url` and `title` keys to exist on the value it is processing.  We are currently passing `uri` instead of `url` and not always including a `title` value.
- The `title` value issue may be a source site content problem, at least in the case of the D7 kitten site used for our Probo migration tests.  See problematic D7 demo content here: https://bitbucket.org/ua_drupal/ua_quickstart/src/3bf9f9b4116144655178dde6c21c572273686411/modules/custom/uaqs_demo/im …

Closes #2249: Fix migration config for link field on news and events that is generating PHP warnings.

---

modules/custom/az_core/config/install/smart_title.settings.yml

AZ Page's Card and Row display modes are configured to use Smart Title. However, Page was never added to Smart Title's config. PR adds `az_page` node type to Smart Title config. The problem appears more prominently on migrated sites for some reason, more so than it does fresh builds (like on Probo sites).
Review site: https://7b5e2985-cedf-4a13-ab91-3a35916c835d--pr-2254.probo.build/page-grid
Closes #2253
Visit /page-grid and ensure titles are displaying inside the card and not outside of the card

Closes #2253 - Add az_flexible_page to smart_title settings

---

modules/custom/az_migration/src/Plugin/migrate/process/ParagraphsExtraInfoFieldMerge.php

Get past an error when migrating extra info paragraphs.
Closes #2259 
Migrate from QS1 site with extra info paragraphs with incomplete field data.

Closes #2259 use null coallesce operator when creating strings to print from deeply nested array values (ParagraphsExtraInfoFieldMerge).

---

modules/custom/az_event/az_event_trellis/az_event_trellis.module
modules/custom/az_event/az_event_trellis/src/Form/TrellisEventImportForm.php

Fixes coding standards issues for experimental az_events_trellis module that are showing up in our automated checks.
Closes #2273 
Review output of automated coding standards checks,
Note that the "manual" accessCheck warning will still show up in the Upgrade Status report for the entity query in the az_events_trellis.module file because that check only finds entity queries but can't actually verify whether they have the appropriate `accessCheck()` or not.

Closes #2273: Fix az_events_trellis coding standards issues.

---

modules/custom/az_migration/README.md

Updating Readme to help anyone following the migration guide.

Documentation: Add pre-migration task to menu links migration docs.

---

modules/custom/az_migration/migrations/az_node_event.yml
modules/custom/az_migration/migrations/az_node_news.yml
modules/custom/az_migration/migrations/az_node_person.yml

Related, https://github.com/az-digital/az_quickstart/pull/2250/files  got us half way there.
Update news, event, and person node migration yml files to fix `field_uaqs_link` -> `field_az_link` migration.
In Quickstart 1 there is a feature that allows linking to external content in listings (views) using the `field_uaqs_link` field.
Three content types are affected by this.
https://bitbucket.org/ua_drupal/ua_quickstart/src/1dd588782bc1467d2669b0ef9147aff5ed06e61f/modules/custom/uaqs_person/uaqs_person.features.field_instance.inc#lines-502
https://bitbucket.org/ua_drupal/ua_quickstart/src/1dd588782bc1467d2669b0ef9147aff5ed06e61f/modules/custom/uaqs_news/uaqs_news.features.field_instance.inc#lines-449
https://bitbucket.org/ua_drupal/ua_quickstart/src/1dd588782bc1467d2669b0ef9147aff5ed06e61f/m …

Fixes #2282 News, Event, Person external links do not migrate.

---

composer.json

[drupal.org/sa-core-2023-002](https://www.drupal.org/sa-core-2023-002)
[drupal.org/sa-core-2023-003](https://www.drupal.org/sa-core-2023-003)
[drupal.org/sa-core-2023-004](https://www.drupal.org/sa-core-2023-004)
https://www.drupal.org/project/drupal/releases/9.5.5
Closes #2294 

Closes #2294: Update Drupal core to 9.5.5 (moderately critical security update).

---

composer.json

[drupal.org/sa-core-2023-002](https://www.drupal.org/sa-core-2023-002)
[drupal.org/sa-core-2023-003](https://www.drupal.org/sa-core-2023-003)
[drupal.org/sa-core-2023-004](https://www.drupal.org/sa-core-2023-004)
https://www.drupal.org/project/drupal/releases/9.4.11
https://www.drupal.org/project/drupal/releases/9.4.12
Closes #2295 

Closes #2295: Update Drupal core to 9.4.12 (moderately critical security update).

---

az_quickstart.info.yml
az_quickstart.install
composer.json
modules/custom/az_media/az_media.info.yml
modules/custom/az_media/config/install/core.entity_form_display.media.az_document.default.yml

PR adds media_entity_file_replace module. This module will enable editors to replace and rename their files, as they were able to do in Quickstart 1.
Review site: https://7b5e2985-cedf-4a13-ab91-3a35916c835d--pr-2311.probo.build/
Closes #1528 
1. Upload a PDF
2. Re-edit that PDF and replace it with a new file, select the option to keep the same filename.
3. Repeat step 2, but rename the file this time.

Closes #1528: Allow users to replace files, also rename files through re-upload

---

modules/custom/az_migration/README.md

Let migrators know that they should check pathauto settings before running certain migrations.

Documentation: Update various pre-migration suggestions to include checking pathauto settings

---

modules/custom/az_person/config/install/field.field.node.az_person.field_az_attachments.yml

Enables Person content type's "description" on the CV field.
Review site: https://7b5e2985-cedf-4a13-ab91-3a35916c835d--pr-2343.probo.build/
Closes #2341 

Closes #2341: Enable use of description on Person's CV field

---

modules/custom/az_event/config/install/core.entity_view_display.node.az_event.az_card.yml
modules/custom/az_event/config/install/core.entity_view_display.node.az_event.az_row.yml

Changes event link styles from `.text-red` to `.text-chili` to better align with default link styling on Bootstrap & Quickstart.
Review site: https://7b5e2985-cedf-4a13-ab91-3a35916c835d--pr-2344.probo.build/
Closes #2342 

Closes #2342: Change links to chili on Event displays

---

composer.json

https://www.drupal.org/sa-core-2023-005
https://www.drupal.org/project/drupal/releases/9.4.14
https://www.drupal.org/project/drupal/releases/9.4.13
Closes #2350 

Closes #2350: Update Drupal core to 9.4.14 for SA-CORE-2023-005 (2.5.x only)

---

modules/custom/az_migration/migrations/az_redirects.yml

Modifies existing `az_redirects` migration:
- Processes redirect `source` value with `az_migrated_path_lookup` migrate plugin
- Previously just the redirect `redirect` (destination) value was being processed with `az_migrated_path_lookup`
This will allow node or term IDs in both the redirect source path and destination path values to be transformed to the corrected migrated IDs.
Closes #2371

Closes #2371: Transform IDs in both source and destination paths for migrated redirects.

---

.lando.yml

Replaces the `drupal-ci/webdriver-chromedriver` docker image we have been using in our lando config with `seleniarm/standalone-chromium`, which provides both `amd64` and `arm64` builds.  This should make it possible to run functional Javascript tests using lando on arm64 systems (e.g. Mac M1/M2 systems). 
Closes #2363
Run `lando phpunit`

Closes #2363: Use arm64-compatible webdriver image for lando.

---

az_quickstart.info.yml
az_quickstart.install

Splitscreen module is a frequent request to site admins to enable. Given that Splitscreen has been available and stable for a few months, it should be enabled by default to remove the burden from site admins and empower site editors.
Closes #2395 
- Ensure module is installed and usable upon fresh build.
- Ensure module is installed on existing site using DB update (where it was previously uninstalled)

Closes #2395 - Enable Splitscreen by default

---

CONTRIBUTING.md

Updates Slack channel information (displays correct channels) and meeting information (removes in-person since we no longer meet in person).
Closes #2437 

Closes #2437 - Fix Slack channel and meeting information in CONTRIBUTING.md

---

composer.json

We haven't yet updated Quickstart 2.5.x with the latest Drupal core 9.4.x release (9.4.15).
drupal.org/project/drupal/releases/9.4.15
Closes #2418

Closes #2418: Update drupal/core-recommended to 9.4.15 (2.5.x only)

---

modules/custom/az_core/tests/src/Functional/QuickstartFunctionalTestBase.php
modules/custom/az_core/tests/src/FunctionalJavascript/QuickstartFunctionalJavascriptTestBase.php
modules/custom/az_core/tests/src/Traits/AllowDrupalLoginSetupTrait.php

Updates `AllowDrupalLoginSetupTrait` for tests to _not_ override the `parent::setup()` method because individual test classes may also need to override the setup method.
#2403
`lando phpunit`

#2403: Refactor AllowDrupalLogin test trait to not override parent::setup().

---

config/install/user.role.az_content_admin.yml

Added `administer url aliases` to the permission list in `user.role.az_content_admin.yml`
Closes #2431 
Log in as content administrator
Navigate to /admin/config/search/path/add
See form for adding url aliases.

Closes #2431 Allow content administrators to manage their own url aliases.

---

modules/custom/az_news/az_news_marketing_cloud/az_news_marketing_cloud.libraries.yml
modules/custom/az_news/az_news_marketing_cloud/az_news_marketing_cloud.module
modules/custom/az_news/az_news_marketing_cloud/css/az-marketing-cloud-admin.css
modules/custom/az_news/az_news_marketing_cloud/js/az-marketing-cloud-admin.js

Add click to copy functionality.

---

composer.json

Step 2 from https://github.com/az-digital/az_quickstart/wiki/Steps-to-create-a-minor-release

Update composer branch alias in preparation for 2.7.0 pre-release.

---

.ddev/commands/web/install
.github/workflows/security.yml
.lando.yml
.probo.yaml

Step 4 from https://github.com/az-digital/az_quickstart/wiki/Steps-to-create-a-minor-release

2.7.x default branch changes

---

composer.json

Adds patch for viewsreference module that addresses an issue that causes exceptions on views with Ajax enabled on Drupal 10.0+:
https://www.drupal.org/project/viewsreference/issues/3326841
>This is thrown by \Symfony\Component\HttpFoundation\InputBag::get(). This is a BC break in Symfony 6...
Closes #2499 
Test Ajax functionality on views, e.g. the calendar exposed filter widget or other views with Ajax pagers, etc.

Closes #2499: Add viewsreference patch to address Ajax failures.

---

composer.json

Added a patch to resolve this issue from https://www.drupal.org/project/draggableviews/issues/3252365.
#2497
1. Go to the Directory Grid page
2. Click the pencil icon to reorder the view
3. Click Show row weights
4. Enter values into the row weight fields

Closes #2497 Reorder people row weight input boxes don't show values

---

modules/custom/az_google_tag/az_google_tag.module

Closes #2502
Log in as content admin or admin or content editor
Click the Quickstart link in toolbar
Click the analytics dashboard link described here:  https://quickstart.arizona.edu/site-admin/analytics
See if the link takes you to the correct place.

Closes #2502: Update Analytics Dashboard link in toolbar.

---

composer.json

https://www.drupal.org/project/xmlsitemap/issues/3323148
Closes #2516
Try loading XML sitemap settings form (/admin/config/search/xmlsitemap) and verify no fatal errors happen.

Closes #2516: Apply patch for XML sitemap D10 incompatibility issue.

---

modules/custom/az_person/config/install/core.entity_view_display.node.az_person.default.yml

Updates display on AZ Person to have Links heading included in card.
Closes #2503 
Follow up to #2473
1. Create a person with links field completed
2. View person default display to see Links heading and content within the card
3. Verify Links heading and content are in card on default display
Example: https://7b5e2985-cedf-4a13-ab91-3a35916c835d--pr-2501.probo.build/person/jose-anersen

Closes #2503: Update view display for AZ Person

---

config/install/user.role.az_content_editor.yml
modules/custom/az_digital_asset_library/az_digital_asset_library.install

User role `az_content_editor` is dependent on entity_browser due to this permission.
Remove the portion of the database update that uninstalls entity browser.
This is not BC with rc1, and requires an update from 2.6.x
Any sites that previously installed rc1 and had az_digital_asset_library installed and ran database updates will need to manually import the az_content_editor role and assign it to users.
Fixes #2509 
Possible #2515
Apply to existing quickstart site 
Run database updates 
See role still exists

Fixes #2509 Content editor role unintentionally deleted.

---

modules/custom/az_news/az_news.install
modules/custom/az_news/az_news.post_update.php

Adds a database update for AZ News to set the Use Featured Image as Thumbnail field (field_az_featured_image_as_thumb) to true (1) for all existing news nodes. This change also causes the Thumbnail Image field (field_az_media_thumbnail_image) to be populated with the same media ID as the Photo field (field_az_media_image) due to the presave hook in az_news.module.
#2504

Closes #2504 News articles are not displaying thumbnail images on view displays

---

themes/custom/az_barrio/templates/blocks/block--system-menu-block.html.twig

This PR updates the system menu block template to wrap the entire template content in a conditional to test if the menu is empty or not. The screen reader `sr-only` class is also restored to the heading element.
#2518 
Confirm that the space (the empty h2 element) above the primary nav and the utility links is removed. Verify that no other system menu blocks are negatively affected.
- [View Probo site](https://7b5e2985-cedf-4a13-ab91-3a35916c835d--pr-2520.probo.build/)

Closes #2518 RC2 Bug Fixes introduced extra space to the main navigation

---

composer.json

Closes #2552 by temporarily adding a patch for the [Smart Date](https://www.drupal.org/project/smart_date) module. When the next version of Smart Date is released, we should be able to remove this patch.
**This change depends on Quickstart using version 4.0 of Smart Date, so this PR is a branch off of the [dependabot PR to update Smart Date to 4.0.2.](https://github.com/az-digital/az_quickstart/pull/2494)**
Closes #2552 
Link to Probo site: https://7b5e2985-cedf-4a13-ab91-3a35916c835d--pr-2553.probo.build/
1. Go to an event with multiple instances.
2. Click on the Manage Instances button.
3. In the pop-up that appears, find an event to remove and click the arrow next to "Override" to open the dropdown.
4. Click Remove Instance in the dropdown.
5. Confirm that the instance has been removed …

Closes #2552 Cannot remove instances of recurring events

---

az_quickstart.info.yml
modules/custom/az_digital_asset_library/az_digital_asset_library.info.yml

During QA testing of this on existing sites our testers found that they had a lot of trouble logging in.
Closes #2541 
You must now enable az_digital_asset_library in order to use it.

Closes #2541 Downgrade az_digital_asset_library back to experimental due to login issues.

---

composer.json

Adds a patch for the [Search Exclude](https://www.drupal.org/project/search_exclude) module to make the "Search Keywords" filter available for views in Quickstart. 
#2300 
Link to Probo site:
- https://7b5e2985-cedf-4a13-ab91-3a35916c835d--pr-2544.probo.build/
Example page with test view block:
- https://7b5e2985-cedf-4a13-ab91-3a35916c835d--pr-2544.probo.build/person-grid-filter
Views using the Search Keywords filter should return the same results as the main site search (the search box in the top red banner of the site).
To test with your own view:
1. Create a view to show Content of one or all types. (Creating a view page instead of a block will be easiest for testing.)
2. In the Filter criteria section for the view, add the Search Keywords filter. Check the box to expose the filter to …

Closes #2300 Enable Search Keywords view filter

---

config/install/block.block.az_barrio_main_menu.yml
config/install/block.block.az_utility_links.yml
config/install/block.block.claro_breadcrumbs.yml
config/install/block.block.claro_content.yml
config/install/block.block.claro_help.yml
config/install/block.block.claro_local_actions.yml
config/install/block.block.claro_messages.yml
config/install/block.block.claro_page_title.yml
config/install/block.block.claro_primary_local_tasks.yml
config/install/block.block.claro_secondary_local_tasks.yml
modules/custom/az_alphabetical_listing/config/install/views.view.az_alphabetical_listing.yml
modules/custom/az_event/az_event_trellis/config/install/migrate_plus.migration.az_trellis_events.yml
modules/custom/az_flexible_page/config/install/core.entity_view_display.node.az_flexible_page.default.yml
modules/custom/az_media/config/install/core.entity_form_display.media.az_audio.default.yml
modules/custom/az_media/config/install/core.entity_form_display.media.az_audio.media_library.yml
modules/custom/az_media/config/install/core.entity_form_display.media.az_document.media_library.yml
modules/custom/az_media/config/install/core.entity_form_display.media.az_image.default.yml
modules/custom/az_media/config/install/core.entity_form_display.media.az_image.media_library.yml
modules/custom/az_media/config/install/core.entity_form_display.media.az_video.default.yml
modules/custom/az_media/config/install/core.entity_form_display.media.az_video.media_library.yml

Re-exported all config using @tadean's sweet new drush command.  Tried to capture only actual configuration drift changes.  Omitted optional/override changes related to metatag, multilingual, etc.
Closes #2491 

Closes #2491: Re-exported configuration files for 2.7.x

---

.ddev/commands/web/theme-debug
.lando.yml
CONTRIBUTING.md

Retires ddev/lando `theme-debug` tooling since it relied on Drupal console.
Closes #2543

Closes #2543 Retire theme-debug lando/ddev tooling.

---

modules/custom/az_media/config/install/filter.format.az_standard.yml

Moves the "Display embedded entities" filter to the last place in the filter processing order for the az_standard text format.
#2576 
Comparison page showing the extra spaces in the menu block:
- https://pre-release-azs-quickstart.pantheonsite.io/brian-test-page
Probo page with the fix (steps 1-3 below completed):
- https://7b5e2985-cedf-4a13-ab91-3a35916c835d--pr-2577.probo.build/pages/text/text-child-page/text-grandchild-page
1. Create a test menu block (e.g., Second Level Menu)
2. Create a test flexible block and embed the test menu block in the text area, leaving the text format as Standard
3. Add the test flexible block to the site's block layout in a sidebar region
4. Visit a page where the menu block should be displayed and where the page will be linked within a nested list of …

Closes #2576 Line breaks converted to HTML in embedded entities

---

modules/custom/az_publication/az_publication.install

Enable the `az_curated_views` supporting module for sites that already have `az_publication` installed.
Closes #2570 
On an existing site with az_publication module installed 
Upgrade to 2.7.0-rc3
Run `drush updb`
Run `drush config-distro-update`
~~Run `drush cis profiles/custom/az_quickstart/modules/custom/az_news/config/install/views.view.az_news.yml`~~

Closes #2570 Adding update to install az_curated_views

---

themes/custom/az_barrio/az_barrio.info.yml

Adding the arizona-bootstrap css to the az_barrio theme info file using the ckeditor5 library api.
#2446 
Looks like this 

Closes #2446 Allow CKEditor5 to use arizona-bootstrap CSS

---

modules/custom/az_mail/config/quickstart/smtp.settings.yml

Changed port number to pantheon recommended port for AWS SES 
Pantheon strongly encourages using ports other than 25, 465 or 587 to send email because those ports are often blocked by service providers as an anti-spam measure
Closes #2604 
Enable az_mail module
see port change in config
Documentation change for https://quickstart.arizona.edu/emailhandler-webform-settings: 
We should add a note about AWS SES Credentials: If you would like to use the shared credentials, please contact the webteam.
Additionally, possibly add a link to [docs.pantheon.io/email#smtp-providers--configurations](https://docs.pantheon.io/email#smtp-providers--configurations)
- …

Closes #2604 Change port number in az_mail module from 587 to 2587

---

modules/custom/az_core/config/install/core.entity_view_mode.node.az_row_with_background.yml
modules/custom/az_event/config/install/core.entity_view_display.node.az_event.az_row_with_background.yml
modules/custom/az_event/config/install/views.view.az_events.yml
modules/custom/az_news/config/install/core.entity_view_display.node.az_news.az_row_with_background.yml
modules/custom/az_news/config/install/views.view.az_news.yml

Initial view displays and content type displays

---

modules/custom/az_marketing_cloud/az_marketing_cloud.module
modules/custom/az_marketing_cloud/config/install/views.view.az_marketing_cloud.yml

Update Marketing Cloud module
-  Add publication date field to content page
- Update content page to show unpublished content
- Make header filters and info work on admin/content/marketing-cloud
Closes #2644 
- Enable Quickstart for Marketing Cloud module
- Verify changes work as expected

Closes #2644: Marketing Cloud module initial feedback

---

composer.json

A D10 compatible release is available for `drupal/background_image_formatter` so we can switch back to it and archive our fork.
Closes #2656
- Verify composer install still works
- Verify background images still work

Closes #2656: Switch back to d.o. version of background_image_formatter module.

---

composer.json
modules/custom/az_google_tag/config/install/google_tag.container.az_comprehensive.yml

Applies patch to google_tag module to fix issue with module-provided DB update that broke Google Tag container configs on sites upgrading from AZQS 2.6.x to 2.7.x.
https://www.drupal.org/project/google_tag/issues/3382757
Closes #2677
- Create a Quickstart 2.6.x site
- Upgrade to Quickstart 2.7.x using this PR branch
- Verify that GTM config works the same way

Closes #2677: Fix broken Google Tag config upgrade.

---

modules/custom/az_news/config/install/core.entity_form_display.node.az_news.default.yml
modules/custom/az_seo/config/quickstart/core.entity_form_display.node.az_news.default.yml

This PR sets the News content type enterprise attributes field to allow only the Topic and Audiences attributes.
Closes #2680 
- enable `az_enterprise_attributes_import`
- enable `az_news_export`
- visit `admin/structure/types/manage/az_news/form-display`
- verify that only Topic and Audiences are allowed as attributes on the enterprise attributes widget
- Create news content
- Verify that only the Topic and Audiences attributes are selectable

Fixes #2680 News Content Topic and Audiences Attributes only

---

modules/custom/az_marketing_cloud/az_marketing_cloud.info.yml
modules/custom/az_marketing_cloud/az_marketing_cloud.module
modules/custom/az_marketing_cloud/config/install/core.entity_view_display.node.az_event.az_marketing_cloud_event_layout.yml
modules/custom/az_marketing_cloud/config/install/core.entity_view_mode.node.az_marketing_cloud_event_layout.yml
modules/custom/az_marketing_cloud/config/install/views.view.az_marketing_cloud.yml
modules/custom/az_marketing_cloud/templates/node--view--az-marketing-cloud--event-layout.html.twig

Need help with adding link to title
Closes #2645 
1. Enable the Quickstart for Marketing Cloud module
2. Add events to the website
3. View new Content for email page
4. Click on Event layout for an event
5. View event rendered for email
6. Verify link goes to site or external link

Closes #2645: Add events to Quickstart for Marketing Cloud module

---

composer.json
modules/custom/az_google_tag/config/install/google_tag.container.az_comprehensive.yml
modules/custom/az_marketing_cloud/az_marketing_cloud.info.yml
modules/custom/az_marketing_cloud/az_marketing_cloud.module
modules/custom/az_marketing_cloud/config/install/core.entity_view_display.node.az_event.az_marketing_cloud_event_layout.yml
modules/custom/az_marketing_cloud/config/install/core.entity_view_mode.node.az_marketing_cloud_event_layout.yml
modules/custom/az_marketing_cloud/config/install/views.view.az_marketing_cloud.yml
modules/custom/az_marketing_cloud/templates/node--view--az-marketing-cloud--event-layout.html.twig
modules/custom/az_news/az_news_export/az_news_export.services.yml
modules/custom/az_news/az_news_export/src/AZNewsDataEmpty.php
modules/custom/az_news/az_news_export/src/Normalizer/AZNewsDataEmptyNormalizer.php
modules/custom/az_news/az_news_export/src/Plugin/views/row/AZNewsDataFieldRow.php
modules/custom/az_news/config/install/core.entity_form_display.node.az_news.default.yml
modules/custom/az_seo/config/quickstart/core.entity_form_display.node.az_news.default.yml
themes/custom/az_barrio/css/az-barrio-off-canvas-nav.css
themes/custom/az_barrio/templates/layout/page.html.twig

Merge main into issue/2646

---

modules/custom/az_global_footer/az_global_footer.install
modules/custom/az_global_footer/data/az_global_footer.json

- Updates Campus Safety link in data used to build Global Footer menus on new module installs
- Adds DB update to Global Footer module for updating Campus Safety links on sites that already installed the module.
Closes #2683
- Install Global Footer module
- Verify that Campus Safety Link is correct in Global footer
- Apply PR (e.g. as composer patch)
- Run DB updates
- Verify that Campus Safety Link is correct in Global footer

Closes #2683: Update Campus Safety link in Global footer

---

modules/custom/az_person/config/install/core.entity_form_display.node.az_person.default.yml
modules/custom/az_person/config/install/core.entity_view_display.node.az_person.az_row.yml
modules/custom/az_person/config/install/core.entity_view_display.node.az_person.default.yml

Update Person default and row displays so they don't show the caption for the images. 
Closes #1436 
1. Add a person with image
2. Add a caption/credit to the used image
3. Verify caption/credit does not appear on any views or people pages
4. Verify extra space does not appear on a person page

Closes #1436: Remove photo caption from AZ Person displays

---

themes/custom/az_barrio/az_barrio.info.yml
themes/custom/az_barrio/az_barrio.theme

Set's the AZ Barrio theme default logo and updates theme logic to use that logo is used when "Use the logo supplied by the theme" is checked.
Closes #1152 
- Visit theme settings for AZ Barrio.
- Expand Logo Image accordion.
- Clear "Path to custom logo"
- Checkmark "Use the logo supplied by the theme"
- Save
The logo should remain the same.

Closes #1152: Use default theme logo when "Use the logo supplied by the theme"  is checked

---

config/install/user.role.az_content_editor.yml

In-place editing of content is no longer provided by Drupal core or Quickstart.
See https://git.drupalcode.org/project/quickedit/-/blob/1.0.x/quickedit.permissions.yml?ref_type=heads
Closes #2703 
Check that in-place editing is not a thing.

Closes #2703 Remove permission for deleted quickedit module.

---

composer.json

Replaces patch used for DraggableViews weights issue with a new version submitted by @joshuasosa 
Closes #2688
1. On a reordering admin page, remove all field labels from the view and save.
2. Ensure the reordering admin page still works (no errors / white screen).

Closes #2688: Replace DraggableViews weights issue patch.

---

modules/custom/az_paragraphs/az_paragraphs_splitscreen/css/az_splitscreen.css

I want my content to be full width of the text container.
Closes #2728 
1. Add split screen paragraph
2. Add content with bootstrap grid, image left
3. Verify all content is full width of the container.
Example page: https://b09606ef-d32b-4429-acd6-3e7120e60fdb.probo.build/dana
Expected changes could result in visual changes which may be perceived as breaking changes if content was relying on previous broken functionality. For example, a button with the `btn-block` class could now span the full area width rather than a smaller percentage of the area.

Closes #2728: Allow split screen paragraph content to span full width.

---

modules/custom/az_marketing_cloud/templates/node--view--az-marketing-cloud--text-layout.html.twig

Remove extra breaks under summary field
Closes #2723
1. Enable QS for Marketing Cloud module
2. Add a news item with summary text
3. View Text Layout in "Content for email"
4. Verify added space is no longer present between summary and link text
Example page: https://a0cf1cd2-5d4b-40d9-88e3-8aa1fae6c6cf.probo.build/export/marketing-cloud/text-layout/58

Closes #2723: Update marketing cloud template text layout

---

composer.json

https://www.drupal.org/sa-core-2023-006
Closes #2750

Closes #2750: Update Drupal core to 10.0.11 for SA-CORE-006 (critical security update).

---

composer.json

https://www.drupal.org/sa-core-2023-006
#2750 

#2750: Update Drupal core to 9.5.11 for SA-CORE-006 (critical security update).

---

modules/custom/az_person/config/install/views.view.az_person.yml

I want the modal display in 3 cols instead of 4 cols
Closed #2733 
1. Add person content
2. Add Grid - Modal 3 cols view to a page
3. View page with people in 3 cols instead of 4 cols
Example page: https://f0450e56-df55-44dd-b891-1fed3396b4e9.probo.build/person-views
Addition: New AZ Person display of Grid - Modal 3 col added
Change: AZ Person displays of Grid 3 col and Grid changed from `col-sm-12` to `col-sm-6`

Closes #2733: Add AZ Person View Display

---

modules/custom/az_core/css/claro-node-form-overrides.css

Increases the specificity of our CSS rule to restore the full width of the node edit form.
#2770
https://7b5e2985-cedf-4a13-ab91-3a35916c835d--pr-2777.probo.build/
Edit an existing or new page and confirm that the page elements take up the full width of the left side of the screen.

Closes #2770 Page edit form too narrow on wide screens

---

modules/custom/az_media/config/install/core.entity_view_display.media.az_remote_video.az_background.yml
modules/custom/az_media/config/install/core.entity_view_display.media.az_remote_video.az_large.yml
modules/custom/az_media/config/install/core.entity_view_display.media.az_remote_video.az_medium.yml
modules/custom/az_media/config/install/core.entity_view_display.media.az_remote_video.az_natural_size.yml
modules/custom/az_media/config/install/core.entity_view_display.media.az_remote_video.az_small.yml
modules/custom/az_media/config/install/core.entity_view_display.media.az_remote_video.az_square.yml
modules/custom/az_media/config/install/core.entity_view_display.media.az_remote_video.default.yml
modules/custom/az_person/config/install/core.entity_view_display.node.az_person.az_card.yml

Re-exported config in preparation for 2.8.0 now that we've merged #2587.
Closes #2767
https://7b5e2985-cedf-4a13-ab91-3a35916c835d--pr-2768.probo.build/

Closes #2767 Re-export config ahead of 2.8.0 release.

---

.github/workflows/create-release.yml

Moved some steps around to allow a more streamlined release process.
1. Switched from the archived action https://github.com/actions/create-release to a maintained action [softprops/action-gh-release](https://github.com/softprops/action-gh-release)
2. Updated  peter-evans/repository-dispatch to v2
3. Consolidated the create release, upload zip, and upload tar steps into one.
4. Moved back to dev step to the end.
Closes #2755 
Create a release.

Closes #2755 Update create release workflow ahead of API changes.

---

.github/workflows/prepare-for-minor-release.yml

#1710: Fix new GH actions workflow for preparing a minor release

---

az_quickstart.install
composer.json

Adds a more formal mechanism for deprecating modules prior to removal from Quickstart.
Closes #2685 
1.  Install one of the deprecated modules (background_image_formatter, ckeditor (4), entity_browser)
2. Verify that warning shows up on site status report

Closes #2685: Deprecate background_image_formatter module and add AZQS deprecated modules warning to status report.

---

modules/custom/az_news/az_news_export/config/install/views.view.az_news_export.yml
modules/custom/az_news/az_news_export/src/Plugin/views/row/AZNewsDataFieldRow.php

Adds additional fields to Quickstart News Export view:
- Node UUID
- FID, UUID, and alt text values for media image fields
#2584 
1. Install Quickstart News Export module
2. Inspect contents of [/az_quickstart/export/az_news/v1/az_news.json](https://17be01a0-3a71-4a8b-9810-6646d593e1bf.probo.build/az_quickstart/export/az_news/v1/az_news.json)

#2584: Add missing fields to news export for feature parity with legacy news feed

---

composer.json

Adds patch to fix bug introduced in Linkit 6.1.1.
https://www.drupal.org/project/linkit/issues/3212820#comment-15259763
Closes #2802
Add/edit card paragraphs on flexible pages

Closes #2802: Add patch for Linkit 6.1.1 regression.

---

.github/workflows/prepare-for-minor-release.yml

Refactor to let peter-evans/create-pull-request does all of the work in prepare branch for minor release workflow.

---

RELEASES.md

Update RELEASES.md with information about beta and rc releases

---

composer.json

Prepare main branch for 2.8.x release.

---

modules/custom/az_event/az_event_trellis/az_event_trellis.install

Add a hook to install the `views_remote_data` dependency for `az_trellis_events`.
Closes #2825 
Closes #2827

Closes #2825, Closes #2827 Add module installer for views_remote_data in update hook.

---

config/install/extlink.settings.yml

Updates the settings for the External Links module to remove the list of whitelisted domains and instead use a regular expression to open external URLs in a new tab/window only if they start with one of the following:
- https://arizona.box.com
- https://docs.google.com
- https://dropbox.com
- https://www.dropbox.com
- https://emailarizona-my.sharepoint.com
- https://events.trellis.arizona.edu
#2829
Link to Probo site:
Confirm that the only links to open in a new tab/window are links to PDFs on the website and the external URLs listed above.

Closes #2829 All external links opening in new tab instead of only intended external links

---

.github/workflows/create-release.yml

Should fix problem with recently updated `create-release` GH actions workflow due to steps for creating release assets (tar, zip files) being moved to before the actual release (and tag) exist.
Closes #2838
Hard to test without forking the repo, merging the change and running the action on your fork.

Closes #2838 Fix failing create-release workflow.

---

.github/workflows/prepare-for-minor-release.yml

Fixes the naming convention used for some of the PR branches generated by the `prepare-for-minor-release` workflow conflict with our branch protection rules so they are unable to be deleted as expected after being merged.
Closes #2836 
This is hard to test without creating a fork of Quickstart and running the workflow on your fork.

Closes #2836: Fix PR branch naming convention in prepare-for-minor-release workflow.

---

modules/custom/az_core/css/claro-node-form-overrides.css
modules/custom/az_paragraphs/az_paragraphs.libraries.yml

Removes AZ Barrio global-styling dependency from az_paragraphs.preview and adds a table row striping rule to the Claro node form overrides CSS library (since it is overriding a Claro style for tables).
I briefly reviewed the [AZ Barrio global-styling CSS](https://github.com/az-digital/az_quickstart/blob/main/themes/custom/az_barrio/css/style.css) and didn't notice other styling that should cause issues on node edit pages.
#2849 
Link to Probo site: https://7b5e2985-cedf-4a13-ab91-3a35916c835d--pr-2850.probo.build/
1. Create/edit a page and add a bulleted list in a new Text paragraph.
2. Collapse the paragraph or have it automatically collapse by adding a new paragraph.
3. In the preview of the Text paragraph content, verify that the list is indented properly (the left margin should NOT be …

Closes #2849 CKEditor preview styling overridden by AZ Barrio styling in 2.8 beta2

---

modules/custom/az_carousel/config/quickstart/blazy.settings.yml

Adds Quickstart config to `az_carousel` module to override default blazy module settings to enable a setting that suppresses an error in the site status report.
Closes #2843 
[Probo site](https://7b5e2985-cedf-4a13-ab91-3a35916c835d--pr-2844.probo.build/)
We mainly just need to make sure our Carousel feature is still working as expected since that's the only thing in Quickstart that relies on Blazy/Slick.

Closes #2843: Address blazy module status report error in 2.8.x.

---

modules/custom/az_paragraphs/config/optional/editor.editor.az_standard.yml

Updates the az_standard text format to add class to the allowed attributes for div elements.
#2872
Link to Probo site: https://7b5e2985-cedf-4a13-ab91-3a35916c835d--pr-2873.probo.build/
1. Switch to source mode in the text editor while using the Standard text format.
2. Add a div element with one or more classes (such as `<div class="bg-dark">Test</div>`).
3. Switch back to normal mode and confirm that the text is styled appropriately.
4. Switch to source mode again and confirm that the class attribute remains.

Closes #2872 CKEditor 5 strips classes from div elements

---

composer.json

See https://www.drupal.org/i/3364963
Closes #2869 
Please test the linkit fix on this probo build https://2aa7b7a4-a1dc-49fe-a6b8-59ce094c6ed4.probo.build/user
Add a Text Box paragraph to a page
Type some text
Add an internal link
Approve link by clicking green checkmark
Do not see the following:
>  Error message appears until text is added after link (error will not appear if text you are adding link to is in the middle of a pagagraph - i.e. has text after it

Closes #2869 Linkit CKEditor5 fix for adding urls.

---

.probo.yaml

- Adds symlink to Quickstart provided drush executable in `/usr/local/bin` so that the ProboCI Drush plugin's bare `drush` invocations work
- Removes old `DRUSH_LAUNCHER_FALLBACK` workaround since the Drush launcher no longer seems to be installed on the ProboCI containers (Probo confirmed it has been removed in their response)
Closes #2884 

Closes #2884: Address ProboCI drush issues

---

modules/custom/az_paragraphs/az_paragraphs_splitscreen/css/az_splitscreen.css

Closes #2732 by adding a right margin to non-full-width az_splitscreen paragraphs when no sidebars are present. Also adjusts indentation in az_splitscreen.css to match our other CSS files.
#2732
Probo site: https://7b5e2985-cedf-4a13-ab91-3a35916c835d--pr-2882.probo.build
1. Visit the [Split Screen No Sidebar](https://7b5e2985-cedf-4a13-ab91-3a35916c835d--pr-2882.probo.build/pages/split-screen-no-sidebar) demo page and confirm that the center line is aligned for all Split Screen paragraphs (both full-width and non-full-width).
2. Verify that mobile view is unaffected.
3. Compare the [Split Screen](https://7b5e2985-cedf-4a13-ab91-3a35916c835d--pr-2882.probo.build/pages/split-screen) page with the [Split Screen](https://demo.quickstart.arizona.edu/pages/split-screen) page on the demo site …

Closes #2732 Alternating Split Screen paragraphs don't line up in the center

---

composer.json

https://www.drupal.org/sa-contrib-2023-049
Closes #2890 

Closes #2890: Update paragraphs_admin to 8.x-1.5 for SA-CONTRIB-2023-049.

---

modules/custom/az_event/config/install/field.field.node.az_event.field_az_body.yml
modules/custom/az_news/config/install/field.field.node.az_news.field_az_body.yml
modules/custom/az_paragraphs/az_paragraphs_splitscreen/config/install/field.field.paragraph.az_splitscreen.field_az_text_area.yml
modules/custom/az_paragraphs/az_paragraphs_text/config/install/field.field.paragraph.az_text.field_az_text_area.yml
modules/custom/az_paragraphs/az_paragraphs_text_background/config/install/field.field.paragraph.az_text_background.field_az_text_area.yml
modules/custom/az_paragraphs/az_paragraphs_text_media/config/install/field.field.paragraph.az_text_media.field_az_text_area.yml
modules/custom/az_person/config/install/field.field.node.az_person.field_az_body.yml
themes/custom/az_barrio/css/ckeditor5.css

Adds a gray background color to white text within CKEditor to allow editors to see their content (when text is white). Also adds corresponding help text to "body" fields for AZQS content types and paragraph types.
Closes #2896 
- Add white text to various content types and paragraph types
- Ensure it becomes highlighted in gray text (from within CKEditor only)
- Ensure help text is present under body fields

Closes #2896 - Make white text visible while editing

---

modules/custom/az_core/az_core.libraries.yml

Adds AZ Bootstrap library dependency to node form overrides library included in AZ Core to ensure Arizona Bootstrap is properly loaded for CKEditor on node text area fields (e.g. News, Event, Person).
Closes #2918 
Link to Probo site: https://7b5e2985-cedf-4a13-ab91-3a35916c835d--pr-2919.probo.build
1. Create a new News item
2. Ensure AZ Bootstrap styles are applied to content in the CKEditor as expected before and after saving the node.

Closes #2918: Add AZ Bootstrap library dependency to node form overrides library.

---

az_quickstart.info.yml
az_quickstart.install

Excludes the Drupal core BigPipe module from installing by default on Pantheon environments.
#2916
Confirm that the BigPipe module is installed in Probo and not installed on a Pantheon environment.

Closes #2916 Exclude BigPipe module from Quickstart installs on Pantheon

---

modules/custom/az_core/src/Plugin/migrate/process/ManualMigrationLookup.php

I'm using this patch for a migration I am currently running that has two source databases.
Closes #2907 
Edit you manual migration lookup config to set the new `source_db_key` confguration key.

Closes #2907 Make Manual Migration Lookup DB configurable.

---

modules/custom/az_marketing_cloud/az_marketing_cloud.module
modules/custom/az_marketing_cloud/config/install/views.view.az_marketing_cloud.yml
modules/custom/az_marketing_cloud/templates/node--view--az-marketing-cloud--30-70-layout.html.twig
modules/custom/az_marketing_cloud/templates/node--view--az-marketing-cloud--50-50-layout.html.twig
modules/custom/az_marketing_cloud/templates/node--view--az-marketing-cloud--event-layout.html.twig
modules/custom/az_marketing_cloud/templates/node--view--az-marketing-cloud--hero-layout.html.twig
modules/custom/az_marketing_cloud/templates/node--view--az-marketing-cloud--text-layout.html.twig

An alternate solution for PR #2782 to display custom content for unpublished news and events on Marketing Cloud content pages. The desired content for the unpublished display replaces the node's original content in the `az_marketing_cloud_preprocess_node__view__az_marketing_cloud()` hook function. Reverts changes to the twig templates and restores the "View published content" access restriction for the AZ Marketing Cloud view.
Link to Probo site: https://7b5e2985-cedf-4a13-ab91-3a35916c835d--pr-2931.probo.build/

PR for issue/2702: Use preprocess hook for Marketing Cloud unpublished layout

---

modules/custom/az_core/src/Plugin/ConfigProvider/QuickstartConfigProvider.php
modules/custom/az_core/src/Plugin/Field/FieldWidget/AZAttributeWidget.php
modules/custom/az_digital_asset_library/az_digital_asset_library.module
modules/custom/az_marketing_cloud/src/Plugin/views/field/AzDropbutton.php
modules/custom/az_paragraphs/az_paragraphs_text_media/az_paragraphs_text_media.install

Resolves various PHPCS warnings in the Quickstart code.
#2905 

Closes #2905 Clean up PHPCS warnings

---

modules/custom/az_card/src/Plugin/Field/FieldFormatter/AZCardDefaultFormatter.php
modules/custom/az_card/src/Plugin/Field/FieldWidget/AZCardWidget.php

Allows documents (and any public file) to be linked in the Card Link URL field. If the link starts with the public files base path (which is what Linkit autocomplete uses for file links), the form validation will verify that the file exists.
Previous clarifying questions:
1. Is it OK to ignore validation for public files?
- Users can already get around the validation by using absolute URLs.
- If not, how could we check if a file exists at the URL?
- (Update Nov 6, 2023) Validation added for file links to confirm that the files do exist.
2. Could/should we use the [Linkit field formatter](https://git.drupalcode.org/project/linkit/-/blob/6.1.x/src/Plugin/Field/FieldFormatter/LinkitFormatter.php) instead? [Here is the Quickstart az_card …

Closes #2102 Error upon save when linking to a document in a Card Link URL field

---

modules/custom/az_marketing_cloud/az_marketing_cloud.module
modules/custom/az_marketing_cloud/config/install/core.entity_view_display.node.az_event.az_marketing_cloud_event_layout.yml
modules/custom/az_marketing_cloud/config/install/views.view.az_marketing_cloud.yml

Some followup commits added to @danahertzberg 's branch:
Currently, display of marketing cloud events are not aware of their recurrence relationship, meaning that when you create the marketing cloud output for a view, it is always displayed as the first occurrence in the series, even if the item they copied was a later event in the series.
This happens because the view in question is not delta-aware. Events are preprocessed by `az_event` to modify the field values if a valid views delta relationship is detected. The calendar views pass along the delta relationship, but the `az_marketing_cloud` views do not.
This PR adds the delta relationship to the event display of the marketing cloud view.
Closes #2888 
- enable `az_marketing_cloud`
- proceed to …

Fixes #2888 Marketing Cloud Event Specificity

---

modules/custom/az_card/templates/az-card.html.twig

A bug emerged causing whitespace to show under cards with no body or link. This PR restores the proper behavior. Now, whitespace will only show if a body and/or link is present.
fixed check for body and/or link. code written by @mrbeiley, @joshuasosa, @bberndt-uaz
Closes: https://github.com/az-digital/az_quickstart/issues/2736

Closes #2736: Remove whitespace on cards with no body or link. 

---

themes/custom/az_barrio/css/style.css

Closes #2944
1. Install Webform module.
2. Visit the default Contact form.
3. See that fields on the form have initial widths instead of full widths.
4. Optionally create a new webform and add fields to test.

Closes #2944 Update style.css text field widths

---

modules/custom/az_core/az_core.libraries.yml

Adds button-no-conflict.js as a dependency for the `arizona-bootstrap-node-form-overrides` CSS library. This fixes the missing close icon on modals (such as the "Add or select media" pop-up).
#2169
Link to Probo review site: https://7b5e2985-cedf-4a13-ab91-3a35916c835d--pr-2956.probo.build
Confirm that the X close icon is visible on all modals (such as adding or editing media items on content types or paragraphs).

Closes #2169 Close icon broken in media library edit module's modal

---

modules/custom/az_event/config/install/field.field.node.az_event.field_az_link.yml

Closes #2933
Add or edit an event
See new help text near the external link field.

Close #2933 Update external link field help text to mention University calendar, and to be more concise.

---

modules/custom/az_event/config/install/field.field.node.az_event.field_az_summary.yml
modules/custom/az_flexible_page/config/install/field.field.node.az_flexible_page.field_az_summary.yml
modules/custom/az_news/config/install/field.field.node.az_news.field_az_summary.yml

Recommend a character limit in the summary help text based on best practice for metatags.
Closes #2930 
Add or edit news/event/page and see help text.

Close #2930 Add suggested character limit of 160 to all az_summary fields.

---

modules/custom/az_card/src/Plugin/Field/FieldWidget/AZCardWidget.php

This PR is intended to be merged to #2967 to fix an issue encountered in testing. The newly-added core field delete button conflicts with the existing implementation of our custom card delete button.
This PR takes the approach of removing our existing custom button for card removal and falling back on the core behavior. The core button is attempt to be relocated and styled such that it appears similar to the original custom button, but it is now powered by the core functionality.
An extra form element wrapper is introduced around the collapse and remove buttons to make it compatible with the same AJAX callbacks that fire for the core delete button.
Note that this PR does **not** attempt to address another recent card issue, #3010 , as it's not directly related, but it does resolve some …

Fixes #3025 Use Core Field Delete Button for Cards

---

modules/custom/az_card/az_card.services.yml
modules/custom/az_cas/az_cas.services.yml
modules/custom/az_core/az_core.services.yml
modules/custom/az_core/drush.services.yml
modules/custom/az_course/az_course.services.yml
modules/custom/az_event/az_event_trellis/az_event_trellis.services.yml
modules/custom/az_mail/drush.services.yml
modules/custom/az_metrics/az_metrics.services.yml
modules/custom/az_news/az_news_feeds/az_news_feeds.services.yml
modules/custom/az_publication/az_publication.services.yml
modules/custom/az_publication/az_publication_import/az_publication_import.services.yml

The aim of this change is to simplify the process of reviewing changes in these files. The PR includes modifications across various modules like az_card, az_cas, az_core, and others, where the syntax for arguments in service definitions is altered from a single line to a multiline format, making each argument distinctly visible.
Closes #3022
Nothing should change.

Close #3022 Change argument array syntax in .service.yml files to make it easier to review changes.

---

composer.json

Adds a patch from [this Quick Node Clone issue](https://www.drupal.org/project/quick_node_clone/issues/3342710) to allow a user's access to the clone operation to reflect access changes from other modules.
#2952 
Link to Probo site: https://7b5e2985-cedf-4a13-ab91-3a35916c835d--pr-2953.probo.build/
1. Install the Quick Node Clone, Workbench Access, and Masquerade modules. (already installed in Probo)
2. Set up a Workbench Access scheme to restrict a Content Editor user from editing certain nodes and/or content types.
3. Masquerade as the user.
4. Confirm that the user can clone nodes which they can edit and cannot clone nodes which they cannot edit.
- …

Closes #2952 Clone permissions in the Quick Node Clone module do not reflect custom access rules

---

.ddev/commands/web/install
.github/workflows/create-release.yml
.github/workflows/security.yml
.lando.yml
.probo.yaml
composer.json

Copy of #3041 with a non-numeric branch name.

Prepare repository for new minor release branch 2.9.x

---

.github/workflows/prepare-for-minor-release.yml

Branch names starting with a number wreak havoc on our composer build processes in CI configs.

Fix branch naming convention for minor release workflow and add new release branches.

---

az_quickstart.install

Media Library Theme Reset is unsupported as of Dec 1.  We should really ensure it's uninstalled on all Quickstart sites ASAP so we can remove it in the next minor release.
#2084

#2084: Add DB update to uninstall now unsupported media_library_theme_reset module.

---

modules/custom/az_publication/az_publication.module

Remove `text-decoration-none` class
Closes #3065 
1. Enable the publications module
2. Add publication with links
3. Add view of publications to a page
4. Ensure page with publications has underlined links

Closes #3065: Remove text decoration from links in az_publication.module

---

README.md

Corrected typo "areneeded" -> "are needed"
Closes #2757 

Closes #2757: Fix typo in README.md

---

composer.json

Fixes the styling of vertical tabs on the Media Library modal by adding the patch from [comment 41](https://www.drupal.org/project/drupal/issues/3404866#comment-15383390) on this Drupal core issue: Media Type links in [Media Library modal missing vertical tabs styling in Claro](https://www.drupal.org/project/drupal/issues/3404866). This patch can be removed once the issue has been resolved and a new Drupal core version has been released.
#3082
Link to Probo review site: https://7b5e2985-cedf-4a13-ab91-3a35916c835d--pr-3083.probo.build
Click the Insert Media button in the CKEditor and confirm that the vertical tabs are styled as usual.
- **Other or …

Closes #3082 Vertical tabs in Media Library modal are missing styling

---

config/install/editor.editor.basic_html.yml
modules/custom/az_paragraphs/config/optional/editor.editor.az_standard.yml
themes/custom/az_barrio/css/ckeditor5.css

Corrects the CKEditor toolbar to match the editor experience from the previous version (reducing confusion):
- Does not show disabled styles
- Corrects button ordering
Adds CSS and modifies text editor config to accomplish this.
Closes #3060 
https://7b5e2985-cedf-4a13-ab91-3a35916c835d--pr-3072.probo.build/
- Use "Standard" text editor and verify "source" and "remove styles" buttons are at the end of the toolbar
- Use "Standard" text editor and verify the "Styles" dropdown no longer shows disabled styles (based on currently selected element)
- Use "Basic" text editor and verify the "source" and "remove styles" buttons are at the end of the toolbar
- …

Closes #3060 - Fix CKEditor editor experience to match previous version

---

composer.json

Adds a patch from [this issue for the Smart Date module](https://www.drupal.org/project/smart_date/issues/3409287) to resolve a User deprecated function error message displayed on the event edit page.
#3084
Link to Probo review site: https://7b5e2985-cedf-4a13-ab91-3a35916c835d--pr-3085.probo.build
Edit an event or add a new event and confirm that no error message is displayed on the page.

Closes #3084 Event edit page displays User deprecated function error

---

modules/custom/az_news/config/install/views.view.az_news.yml

Updates the link text for the "previous page" and "next page" links in the pagers of two AZ News view displays to be consistent with other Quickstart and Drupal full pagers.
#3079
Link to Probo review site: https://7b5e2985-cedf-4a13-ab91-3a35916c835d--pr-3080.probo.build
1. (already completed in Probo) If necessary, enable the Quickstart News Feeds module and import more news articles for testing.
2. Create a test page with two view paragraphs, one displaying the AZ News Paged Row View display and the other displaying the AZ News Teaser Grid Page display.
3. On the test page, confirm that the previous and next page links are displayed as `‹ Previous` and `Next ›` instead of `‹‹` and `››`. …

Closes #3079 Standardize Previous and Next links in full pagers of views

---

composer.json

https://www.drupal.org/sa-core-2024-001
#3099 

#3099 Update Drupal core to 10.2.2 for SA-CORE-2024-001

---

modules/custom/az_news/az_news_feeds/config/schema/az_news_feeds.schema.yml

Change the key name for `uarizona_news_feed_path` to `uarizona_news_content_path` in modules/custom/az_news/az_news_feeds/config/schema/az_news_feeds.schema.yml
Closes #3104 
Enable az_news_feeds
Configure az_news_feeds
Import 

Close #3104 fix typo in az_news_feeds schema.

---

modules/custom/az_media/config/install/core.entity_view_display.media.az_image.az_very_small.yml
modules/custom/az_media/config/install/core.entity_view_mode.media.az_very_small.yml
modules/custom/az_media/config/install/filter.format.az_standard.yml
modules/custom/az_media/config/install/image.style.az_very_small.yml

Provides config for a Very Small media display that site editors can use when embedding images in paragraph body content. The new display is equivalent to the existing Square media display except that it is unbounded in the vertical direction.
Closes #2301 
Create a new paragraph and embed an image using the WYSIWYG editor. Select "Very Small (220px)" from the media embed dialog.

Closes #2301 Add Very Small media display

---

modules/custom/az_cas/az_cas.info.yml
modules/custom/az_core/az_core.info.yml
modules/custom/az_core/az_enterprise_attributes_import/az_enterprise_attributes_import.info.yml
modules/custom/az_publication/az_publication.info.yml

Closes #3035: Add 'Configure' Links to Quickstart Modules

---

modules/custom/az_core/css/az-bef-sidebar.css
modules/custom/az_core/includes/az_core.theme.inc
modules/custom/az_core/templates/az-bef-nested-elements.html.twig

This branch of the `issue/2997-finder-demo-content` branch (for [PR #2998](https://github.com/az-digital/az_quickstart/pull/2998)) makes significant changes to the az-bef-sidebar.css file to style the sidebar to be closer to the [Adobe XD mockup](https://xd.adobe.com/view/223ea53b-daf0-42c7-a500-60c0eda3fddc-776d/screen/ae93ab30-2ad1-4bab-9746-f7417b1f73de).
https://7b5e2985-cedf-4a13-ab91-3a35916c835d--pr-3164.probo.build/pages/page-list-finder

[Branch for issue/2997-finder-demo-content] Update sidebar styling

---

modules/custom/az_publication/az_publication.module
modules/custom/az_publication/az_publication_bibtex/migrations/az_publication_bibtex_import.yml
modules/custom/az_publication/config/install/core.entity_form_display.node.az_publication.default.yml
modules/custom/az_publication/config/install/core.entity_view_display.node.az_publication.az_card.yml
modules/custom/az_publication/config/install/core.entity_view_display.node.az_publication.az_publication_reference.yml
modules/custom/az_publication/config/install/core.entity_view_display.node.az_publication.default.yml
modules/custom/az_publication/config/install/core.entity_view_display.node.az_publication.teaser.yml
modules/custom/az_publication/config/install/core.entity_view_mode.node.az_publication_reference.yml
modules/custom/az_publication/config/install/field.field.node.az_publication.field_az_publication_isbn.yml
modules/custom/az_publication/config/install/field.field.node.az_publication.field_az_publication_issn.yml
modules/custom/az_publication/config/install/field.field.node.az_publication.field_az_publication_pmcid.yml
modules/custom/az_publication/config/install/field.storage.node.field_az_publication_isbn.yml
modules/custom/az_publication/config/install/field.storage.node.field_az_publication_issn.yml
modules/custom/az_publication/config/install/field.storage.node.field_az_publication_pmcid.yml

This PR adds additional identifiers to Publications, notably `issn`, `isbn`, and `pmcid`. This adds the listed identifiers to the content type, the mapping that converts the content type into citation style schema, and the list of fields available in migration import.
Closes #3071 
- enable `az_publication`
- Create a publication
- verify that ISBN, ISSN, and PMCID appear on the edit screen
- Optionally, verify that the identifiers appear in a citation. Note that these identifiers are generally not used by the citation styles shipped with Quickstart. Some that do use them are `national-library-of-medicine-grant-proposals` (PMCID) and `bibtex` for ISSN and ISBN. You will need to add these via `/admin/config/az-quickstart/settings/az-publication/az_citation_style` to test this portion
- …

Fixes #3071 Add additional Publication Identifiers

---

composer.json

Adds patch for viewsreference module from https://www.drupal.org/project/viewsreference/issues/3017716 to address cache issues affecting views without empty handling added to views reference fields.
Closes #3120 
- Ensure core Dynamic Page Cache module is installed
- Ensure Quickstart views paragraph type is still using original ViewsReferenceFieldFormatter
- Ensure the Browser and proxy cache minimum age setting is not set to <no caching> (preferably 1 hour or higher)
1. Create a new content type
2. Create a new view that displays content of your new type with a filter to only show published content and do not add any no results settings to the view
3. Create a flexible page with a views paragraph that displays your new view
4. Load the flexible page as an anonymous user (e.g. in a …

Closes #3120: Adding viewsreference patch to fix cache issues for views without empty handling.

---

modules/custom/az_person/config/install/core.entity_view_display.node.az_person.default.yml

Updates the AZ Person Default display to remove a duplicate h1 node title element (the "Mobile Node Title" field group) and update the CSS classes for the remaining title element (the Smart Title element).
#3153
Link to Probo review site: https://7b5e2985-cedf-4a13-ab91-3a35916c835d--pr-3154.probo.build
1. On the Probo site, visit a person page from the demo content, such as [Wilbur Wildcat](https://7b5e2985-cedf-4a13-ab91-3a35916c835d--pr-3154.probo.build/person/wilbur-wildcat).
2. View the source of the page and search for `<h1`. Confirm that only one h1 element is present.
3. For both desktop and mobile screens, confirm that the page appears identical to the same page on a current Quickstart site (see [Wilbur Wildcat on the demo …

Closes #3153 Duplicate H1 on person pages tripping up some crawlers

---

modules/custom/az_carousel/az_carousel.info.yml

Closes #3162
https://7b5e2985-cedf-4a13-ab91-3a35916c835d--pr-3167.probo.build
Ensure az_carousel still works as expected

Closes #3162: Remove hard-coded slick_ui dependency from az_carousel.

---

modules/custom/az_carousel/config/install/slick.optionset.center_mode.yml
modules/custom/az_carousel/css/az_carousel.css

Adjusts the visual display of carousel items so that the maximum slide width is no larger than the width of the largest breakpoint.
Closes #1428 
1. On a vanilla QS2 site, enable the Quickstart Carousel Item module (it is not enabled by default).
2. Add at least two Carousel item nodes (include background images that are greater than 1110x500).
3. Carousel slides are not restricted to the max width of the page container:

Closes #1428 Carousel off center at display size above 1750 px wide

---

composer.json

Removing a patch that breaks linkit functionality within the ckeditor.
This PR will remove the previously added patch intended to address the issue described at https://www.drupal.org/project/linkit/issues/3364963 and #2869
The [update to CKEditor version 40 (Introduced in 10.2)](https://www.drupal.org/project/drupal/issues/3393557) has resolved the primary concern. However, I’ve encountered a persistent issue: CKEditor erroneously inserts an <a> element without an href attribute directly before an existing <a> element. This causes a notification to appear when using keyboard navigation to reach the position immediately preceding the start of the link. I am still working on a solution for this remaining problem.
#3125 
#2869
1. Using the AZ Standard text format via CKEditor
2. Create a …

Partially fixes #3125 Linkit creating node based link paths (2.9.x only)

---

composer.json

Removes a patch in composer.json for a closed issue on Drupal.org.
See https://www.drupal.org/project/drupal/issues/3163925#comment-14962591
Close #3191 

Closes #3191 Remove patch for drupal.org/i/3163925

---

composer.json

Adds Drupal core patch from drupal.org issue that addresses problem with big_pipe module Javacript code which causes `Cannot read properties of null (reading 'nodeType')` JS error(s) on node add/edit pages.
Closes #3190 
Drupal core issue: https://www.drupal.org/project/drupal/issues/3416141
Steps to reproduce the behavior:
1. Go to add a node (e.g., Event, Page, etc.).
2. Review browser's JavaScript console and verify no errors.

Closes #3190: Add core patch for BigPipe Javascript error(s) on node add/edit pages.

---

modules/custom/az_core/az_core.services.yml
modules/custom/az_core/src/Routing/Routes.php

Updates AZ Core's Routes.php class to use the new AutowireTrait added in Drupal 10.2.x.
Associated Drupal 10.2.x change record: https://www.drupal.org/node/3396179
Closes #3019 

Closes #3019: Update AZ Core Routes.php class to use AutowireTrait.

---

modules/custom/az_news/config/install/core.entity_view_display.node.az_news.default.yml

Changes max content width for News default display.
Closes #3204 
1. View a News item in default view display
2. Verify body content is same width as author content

Closes #3204: Change News content max-width

---

modules/custom/az_core/config/install/views.view.az_taxonomy.yml
modules/custom/az_event/config/install/views.view.az_events.yml
modules/custom/az_flexible_page/config/install/views.view.az_page_by_category.yml
modules/custom/az_news/config/install/views.view.az_news.yml
themes/custom/az_barrio/css/style.css

Adds a CSS rule to AZ Barrio which allows for adding a top margin to the pager of a view display. The new CSS class is applied to four Quickstart view displays: AZ Events - Full Calendar, AZ News - Paged Row View, AZ Pages - Row Page, and Taxonomy List Pages - Page.
Feedback is welcome on this approach!
#3201 
Probo review site: https://7b5e2985-cedf-4a13-ab91-3a35916c835d--pr-3202.probo.build
1. Visit the Calendar page and confirm that there is white space above the pager.
2. Create a page or [visit this test page](https://7b5e2985-cedf-4a13-ab91-3a35916c835d--pr-3202.probo.build/brian-test-page) and confirm that there is white space above the pagers for the AZ News Paged Row view display and the AZ Pages Row Page view display. You may have to set the items per page option to get the …

Closes #3201 Add a top margin to the pager on certain view displays

---

.ddev/commands/web/install
.lando.yml
.probo.yaml
CONTRIBUTING.md

Updates test account passwords for ProboCI, lando and ddev to address Google Chrome warnings.
- az-digital/az-quickstart-scaffolding#145
- az-digital/azqs_module_project#14
Closes #3223
- Login to ProboCI on Google Chrome (using new password(s))
- Verify no browser warnings appear

Closes #3223: Update test account passwords for ProboCI, lando, and ddev.

---

.github/workflows/create-release.yml

#3242, #3244: Ensure any existing version info removed from .info.yml file before adding new version.

---

themes/custom/az_barrio/css/style.css

Visually distinguishes Webform `<label>` from description text and `<legend>`, to make the hierarchy less confusing for visual users. Checkboxes and radio buttons are excluded from this change due to their inline behavior.
[Figma mockup](https://www.figma.com/file/VYeWWbUFTfkUfNOaAyioHV/Untitled?type=design&node-id=1%3A138&mode=dev) from @bearwithbob .
Increases font-size and boldness of non-checkbox/radio `<label>`s.
Closes #3247 
Screenshots of examples of the problem are included on the issue ticket.
1. Install Webform and Webform UI modules.
2. Create a new webform.
3. Include a variety of input options.
4. Include some descriptive text and some fieldsets to make the fix more apparent. …

Closes #3247 - Make Webform labels visually distinguishable from description text

---

modules/custom/az_cas/README.md

Updated the README in modules/custom/az_cas with current information on who needs to request special WebAuth access. Added link to current ServiceNow form for requesting SSO support.
Closes #3257
N/A

Closes #3257 Updated az_cas README with current WebAuth info

---

modules/custom/az_paragraphs/az_paragraphs_photo_gallery/templates/paragraph--az-photo-gallery.html.twig

This PR changes the display of photo galleries to render credit if one is available.
Closes #3253 
1. Add a Caption and Credit to an image
2. Place those images into a photo gallery paragraph
3. Verify that the credit displays in both the slider and grid view.

Fixes #3253 Add Image Credit to Photo Galleries.

---

modules/custom/az_event/config/install/views.view.az_events.yml

Added a 'Past Events' views display withing the existing Calendar view
Closes #1327 
[ ] After enabling the AZ Demo content module, update a few of the AZ Events nodes' dates to have occurred prior to todays date: /admin/content?title=&type=az_event&status=All&langcode=All
[ ] Create a flexible page: node/add/az_flexible_page
[ ] Add a new Page Element of type View 
[ ] Add a Title
[ ] Dropdown set "View*" = "AZ Events"
[ ] Dropdown set "Display*" = "Grid Past with Images"
[ ] Save

Closes #1327: Added a new block display to Events view for past occurrences.

---

modules/custom/az_google_tag/az_google_tag.install
modules/custom/az_google_tag/az_google_tag.module

Adds status report check for Google Tag settings:
- Status is reported as "OK" if all Google Tag containers have the consent mode setting disabled
- Status is reported as "Warning" if any Google Tag containers have the consent mode setting enabled
Closes #3248 
On a clean Quickstart install (e.g. ProboCI):
1. Visit status report page (/admin/reports/status)
2. Verify that no "Google Tag consent mode setting(s)" warning exists
3. Go to the Google Tag containers listing (/admin/config/services/google-tag/containers)
4. Edit the AZ Comprehensive Google Tag container
5. Enable the "Enforce Privacy Consent Policy" setting.  Save.
6. Go back to the status report (/admin/reports/status)
7. Verify that  the "Google Tag consent mode setting(s)" requirement's status is now "Warning"
- **Patch …

Closes #3248: Adds status report check for Google Tag consent mode settings.

---

modules/custom/az_core/az_core.module

Close #3272 
Go to '/admin/help/az_core'
Locate the section that describes settings and configuration common to Quickstart components.
Notice the typographical error in the description gone.

Close #3272 fix typo in az_core help.

---

config/install/system.cron.yml

The current amount of logging that cron does on most quickstart sites is unreasonable and devalues the log.
Close #3282 
Go to /admin/config/system/cron
See Detailed cron logging checkbox unchecked.

Close #3282 Turn Off Detailed Cron Logging By Default.

---

modules/custom/az_demo/data/az_demo_image_file.json
modules/custom/az_demo/data/az_demo_page_node.json
modules/custom/az_demo/data/az_demo_paragraph_gallery.json
modules/custom/az_demo/migrations/az_demo_image_file.yml
modules/custom/az_demo/migrations/az_demo_page_node.yml
modules/custom/az_demo/migrations/az_demo_paragraph_gallery.yml

Adding demo content for easier QA and Acceptance testing for Photo Gallery paragraphs.
Closes #3268
Go to /pages/photo-galleries and see new galleries.

Closes #3268 Add Photo Gallery Demo Content

---

CONTRIBUTING.md

See https://www.drupal.org/node/3359728
See https://www.drupal.org/docs/develop/development-tools/disabling-and-debugging-caching
Closes #3270
Follow the instructions in the pull request.

Closes #3270 Update CONTRIBUTING.md developer docs to reflect changes for Drupal 10.1 

---

.github/CODEOWNERS

We updated the template repo to add Sec Policy.
- https://github.com/az-digital/template/pull/3
- Closes #3142
- https://github.com/az-digital/template/issues/1
N/A

Closes #3142 - Adding SECURITY.md from template repository

---

.github/workflows/security.yml

Fixes workflow syntax in GH actions security workflow so that it is triggered for branches/PRs again.
Closes #3315
Verify that the security workflow jobs/checks are run on this PR and on the main branch when merged.

Closes #3315: Fix security GH actions workflow.

---

composer.json

Updates dev-main alias in main branch.

Prepare repository for new minor release branch 2.10.x

---

modules/custom/az_media/config/install/image.style.az_carousel_item.yml

Reduces the max width of a carousel item to 1110px (down from 1400px).
#3218 
1. Create a carousel item and add an image larger than 1110x500.
2. Verify that aspect ratio is maintained. _My understanding is that the image would first be sized down to 1110px across and then any extra height > 500px would be cropped from the vertical center point. For example, if you had a scaled image at 1110x600, 50 pixels from the top and 50 pixels from the bottom of the scaled image would not be visible to the user._
- [] Patch or minor level update

Closes #3218 Reduce carousel item width to 1110px

---

modules/custom/az_carousel/config/install/field.field.node.az_carousel_item.field_az_media_image.yml

Updates the help text to indicate the correct minimum dimensions 1110x500. This allows editors to easily create a 1:1 between this element and whatever source is generating the image.
#3214
Verify that help text has been updated.

Closes #3214 Update carousel image help text

---

modules/custom/az_demo/az_demo.install

Closes #3375
Install on a site with az_demo already enabled.

Close #3375 Install AZ Finder module if AZ Demo module is already installed.

---

composer.json
modules/custom/az_carousel/config/install/views.view.az_carousel.yml
modules/custom/az_person/config/install/views.view.az_reorder.yml

Adds reset button to draggable reorder view via patch.
Adds button definitions to footer of view.
Closes #3307 
1. Add person content
2. Reorder view display of people on `/admin/az-person/reorder-people`
3. Observe save/reorder button help text
4. Ensure order is reflected on front end
5. Click the reset button
6. Ensure order is reset to alphabetical on the front end

Closes #3307: Add reset order button to draggable views.

---

modules/custom/az_paragraphs/az_paragraphs_text_background/config/install/field.field.paragraph.az_text_background.field_az_text_area.yml

Remove requirement of text area, in order to create banners of color without any text. These elements are just to add space to a page. Still allows users to add Text with Backgrounds.
Closes #3174 
Closes #3174 
Create Text with Background elements that include text and don't include text. Make sure both elements appear as expected and don't cause any issues.

Closes #3174. Made text area not required on az_text_background.

---

modules/custom/az_flexible_page/config/install/core.entity_view_display.node.az_flexible_page.az_row_with_background.yml
modules/custom/az_paragraphs/az_paragraphs_views_side_by_side/config/install/views.view.az_side_by_side_views.yml
modules/custom/az_person/config/install/core.entity_view_display.node.az_person.az_row_with_background.yml

Adds AZ Page and AZ Person content type displays and two view displays to the AZ Side-by-side Views, to be used with Views Side-by-side paragraphs.
Open questions:
1. For the AZ Person view display, should person nodes be linked with the text "View person" or "View profile"?
#2735 
Probo review site: https://7b5e2985-cedf-4a13-ab91-3a35916c835d--pr-3275.probo.build
1.  (already completed in Probo) Enable the Quickstart Paragraphs - Views Side-by-Side module.
2. Add a Views Side-by-Side paragraph to a page. Use the Page Rows with Background and Person Rows with Background view displays.
3. Test the view displays with various page and person content. See [Brian Test Page](https://7b5e2985-cedf-4a13-ab91-3a35916c835d--pr-3275.probo.build/brian-test-page) for example test content.
- **Patch …

Closes #2735 Additional content type displays for AZ Side-by-Side Views

---

composer.json

Adds patch for config_readonly module to make ConfigEntityListBuilder forms (e.g. the admin block listing form) to be accessible if their corresponding entity type is ignored/whitelisted (e.g. `block.block.*`).
See https://www.drupal.org/project/config_readonly/issues/3042241
Closes #3405
(Hard to test in ProboCI.  Easier to test locally in lando.)
1. Install the config staging workflow modules added to Quickstart in 2.10.0 (`config_ignore`, `config_readonly`, `config_ignore_readonly`)
2. Ensure `config_readonly` is active in the site's `settings.php` file (or that you are using a site environment where `config_readonly` is active).
3. Navigate to Structure > Blocks
4. Ensure the warning (`This form will not be saved because the configuration active store is read-only.`) is not present …

Closes #3405: Add config_readonly patch for ConfigEntityListBuilder forms.

---

.github/workflows/prepare-for-minor-release.yml

Update array syntax in workflow file
Add main to the matrix that creates pull requests for updating the dev branch alias.
Add           `- 2.10.x` and `main` branches to auto PR creation matrix.
Close #3329
Build up a quickstart ecosystem under your own github namespace, and create a minor release (or just wait until 2.11.x)

Close #3329 Update prepare repository for minor release action so that it updates the main branch version alias as a pull request.

---

modules/custom/az_paragraphs/az_paragraphs_text_media/js/az_paragraphs_az_text_media_youtube.es6.js
modules/custom/az_paragraphs/az_paragraphs_text_media/js/az_paragraphs_az_text_media_youtube.js

Closes #3424 Update for changes in the YouTube API to fix videos not playing automatically

---

.probo.yaml

Install terminus in probo.

---

themes/custom/az_barrio/templates/layout/page.html.twig

Updates the requirements on drupal/menu_block to permit the latest version.
---
updated-dependencies:
- dependency-name: drupal/menu_block
dependency-type: direct:production
...
Signed-off-by: dependabot[bot] <support@github.com>

Removing ghost block fix for menu_block 1.11.0 update.

---

.github/pull_request_template.md

Adds a section for Release notes in the PR template
Closes #3404
Review template for changes

Closes #3404: Add release notes section to PR template

---

modules/custom/az_paragraphs/az_paragraphs_link_group/az_paragraphs_link_group.info.yml
modules/custom/az_paragraphs/az_paragraphs_link_group/az_paragraphs_link_group.install
modules/custom/az_paragraphs/az_paragraphs_link_group/config/install/core.entity_form_display.paragraph.az_link_group.default.yml

Updates form display settings for experimental link group paragraph type to use linkit widget for link field instead of default core link widget.
Closes #3482

Closes #3482: Update link group paragraph type to use linkit widget.

---

composer.json

Fixes multiple php warnings in the log by adding the patch from this drupal.org issue for the CKEditor Bootstrap Grid module:
- [Warning: Undefined array key "default_layout"](https://www.drupal.org/project/ckeditor_bs_grid/issues/3442400)
#3493
Probo review site: https://7b5e2985-cedf-4a13-ab91-3a35916c835d--pr-3494.probo.build
1. Edit any page containing a text area using the Standard text format
2. Click the "Bootstrap Grid" button in the editor toolbar
3. Click the Next button in the Select Columns modal
4. Save the grid or cancel out of it
5. Go to the Recent Log Messages at `/admin/reports/dblog`
6. Confirm that no `Warning: Undefined array key "default_layout"` PHP warnings are shown …

Closes #3493 PHP warnings logged upon inserting a new Bootstrap grid

---

modules/custom/az_course/az_course.module

Delete debug code from module that prints into the log during each import.
Close #3501
Import courses, notice no messages in the log with large array of links.

Close #3501 remove logging code from az_course importer.

---

modules/custom/az_core/az_enterprise_attributes_import/src/EventSubscriber/AZEnterpriseAttributesMigrationSync.php

Most (all?) of the work for #2781 was completed before we upgrade to 10.3.0 which introduced a new PHPCS coding standard related to how strict types are declared in PHP files.
This should fix the PHPCS issue that now exists for that file.
#2778 
#3290 
Ensure PHPCS checks pass

#2778: Fix 10.3.x specific PHPCS issue in AZEnterpriseAttributesMigrationSync

---

modules/custom/az_paragraphs/src/Plugin/Field/FieldFormatter/AZBackgroundMediaFormatter.php

`AZBackgroundMediaFormatter` does not check if its media entity's file actually exists before attempting to make use of it. This leads to crashes on rendering if the file has somehow gone missing. This can also lead to problems with CAS and Cron on the site since content is sometimes rendered internally during those processes.
#3544 
- build site
- Delete the file entity (not media) for `lynx.jpg`
- Visit the front page which uses that associated media entity, and verify the background media is rendered as a blank space rather than crashing.
- **Other or …

Fixes #3544 AZBackgroundMediaFormatter Breaks with Missing Files

---

.lando.yml

Updates file paths for PHPUnit testing in .lando.yml to resolve fatal errors when running PHPUnit testing locally with the `lando phpunit` and `lando phpunit-fastest` commands.
#3546 
1. Clone a local copy of Quickstart
2. Run `lando start`
3. Run `lando phpunit` or `lando phpunit-fastest`
4. Confirm that the command does not result in fatal errors and the tests begin to run. (These tests can take a long time, so once you confirm that they have started successfully, you may want to cancel out of them with `Ctrl+C`.)
Note: `lando phpunit` will still result in `Deprecated: mb_strtolower()` warnings, as noted in Quickstart issue #2403. …

Closes #3546 PHPUnit tests cannot be run locally using lando

---

modules/custom/az_finder/src/Form/AZFinderSettingsForm.php

This PR refactors the ajax and submit callbacks in #3420 in an attempt to resolve one of the remaining issues discovered. It changes the form logic approach such that all logic happens in the submit handlers rather than the ajax callbacks with rebuilds happening after each submit.
If found to resolve the issue, this PR should be merged to `issue/3262` and not `main`.
#3262 
Verify if issue mentioned in [remaining steps on primary PR](https://github.com/az-digital/az_quickstart/pull/3420#:~:text=Issue%20Recreation%20Steps) is resolved.

Refactor Finder Settings Form.

---

modules/custom/az_person/config/install/core.entity_form_display.node.az_person.default.yml
modules/custom/az_person/config/install/core.entity_view_display.node.az_person.az_card.yml
modules/custom/az_person/config/install/core.entity_view_display.node.az_person.az_row.yml
modules/custom/az_person/config/install/core.entity_view_display.node.az_person.az_row_with_background.yml
modules/custom/az_person/config/install/core.entity_view_display.node.az_person.default.yml
modules/custom/az_person/config/install/core.entity_view_display.node.az_person.teaser.yml
modules/custom/az_person/config/install/field.field.node.az_person.field_az_netid.yml
modules/custom/az_person/config/install/field.storage.node.field_az_netid.yml
modules/custom/az_seo/config/quickstart/core.entity_form_display.node.az_person.default.yml

Adds optional NetID field to AZ Person.  Will be useful/needed for proposed/future enhancements and integrations for AZQS.
```
A new _NetID_ field has been added to the AZ Person content type. Sites that have added additional fields to the AZ Person content type may need to adjust the field display and form display settings for the AZ Person content type after applying configuration changes from the distribution.  This new field will be needed for planned future AZQS integrations and enhancements.
```
Closes #3561
- Ensure new NetID field is available when creating/editing Person content nodes
- Ensure new NetID field is not displayed on any node displays …

Closes #3561: Add NetID field to AZ Person.

---

modules/custom/az_core/src/Drush/Commands/AZEntityListCommands.php
modules/custom/az_core/tests/src/Functional/MonitoringPageTest.php
modules/custom/az_demo/tests/src/Functional/AZDemoContentTest.php
modules/custom/az_event/az_event_trellis/src/Plugin/migrate/source/AZTrellisEventSource.php
modules/custom/az_finder/src/AZFinderIcons.php
modules/custom/az_finder/src/Plugin/better_exposed_filters/filter/AZFinderTaxonomyIndexTidWidget.php
modules/custom/az_finder/src/Plugin/views/exposed_form/QuickstartExposedFilters.php
modules/custom/az_http/src/Plugin/migrate_plus/data_fetcher/AzHttp.php
modules/custom/az_news/az_news_feeds/src/EventSubscriber/AzNewsFeedsMigrateSubscriber.php
modules/custom/az_news/az_news_feeds/src/Form/AzNewsFeedsAdminForm.php
modules/custom/az_paragraphs/src/Plugin/Field/FieldFormatter/AZBackgroundMediaFormatter.php

Applies fixes for updated coding standards that became effective when we switched from `drupal/core-dev-pinned` to `drupal/core-dev` in `az-digital/az-quickstart-dev`.
- Ran `lando phpcbf`
- Applied fix to address phpstan error Re: `AZDemoContentTest` (fix copied from changes made in main/2.11.x branches)
- Removed unnecessary `t()` call in `MonitoringPageTest`
Closes #3581 
Originated from #3290 and the associated changes to az-digital/core-dev in az-digital/az-quickstart-dev#111
```
lando phpcs 
```
(Or look at GitHub Actions / Probo results)

Closes #3581: Apply updated coding standards to 2.10.x branch.

---

modules/custom/az_core/tests/src/Functional/MonitoringPageTest.php
modules/custom/az_demo/tests/src/Functional/AZDemoContentTest.php
modules/custom/az_event/az_event_trellis/src/Plugin/migrate/source/AZTrellisEventSource.php
modules/custom/az_news/az_news_feeds/src/EventSubscriber/AzNewsFeedsMigrateSubscriber.php
modules/custom/az_news/az_news_feeds/src/Form/AzNewsFeedsAdminForm.php
modules/custom/az_paragraphs/src/Plugin/Field/FieldFormatter/AZBackgroundMediaFormatter.php

Applies fixes for updated coding standards that became effective when we switched from `drupal/core-dev-pinned` to `drupal/core-dev` in `az-digital/az-quickstart-dev`.
- Ran `lando phpcbf`
- Applied fix to address phpstan error Re: `AZDemoContentTest` (fix copied from changes made in main/2.11.x branches)
- Removed unnecessary `t()` call in `MonitoringPageTest`
Closes #3581 
Originated from #3290 and the associated changes to az-digital/core-dev in az-digital/az-quickstart-dev#111
```
lando phpcs 
```
(Or look at GitHub Actions / Probo results)

#3581: Apply updated coding standards to 2.9.x branch.

---

modules/custom/az_core/az_enterprise_attributes_import/az_enterprise_attributes_import.info.yml
modules/custom/az_course/az_course.info.yml
modules/custom/az_curated_views/az_curated_views.info.yml
modules/custom/az_demo/az_demo.info.yml
modules/custom/az_digital_asset_library/az_digital_asset_library.info.yml
modules/custom/az_event/az_event_trellis/az_event_trellis.info.yml
modules/custom/az_finder/az_finder.info.yml
modules/custom/az_http/az_http.info.yml
modules/custom/az_marketing_cloud/az_marketing_cloud.info.yml
modules/custom/az_migration/az_migration.info.yml
modules/custom/az_news/az_news_export/az_news_export.info.yml
modules/custom/az_news/az_news_feeds/az_news_feeds.info.yml
modules/custom/az_paragraphs/az_paragraphs_link_group/az_paragraphs_link_group.info.yml
modules/custom/az_paragraphs/az_paragraphs_views_side_by_side/az_paragraphs_views_side_by_side.info.yml
modules/custom/az_publication/az_publication.info.yml
modules/custom/az_publication/az_publication_bibtex/az_publication_bibtex.info.yml
modules/custom/az_publication/az_publication_doi/az_publication_doi.info.yml
modules/custom/az_publication/az_publication_import/az_publication_import.info.yml

Added `lifecycle: experimental` attribute to the following modules:
- `az_core/az_enterprise_attributes_import`
- `az_course`
- `az_curated_views`
- `az_demo`
- `az_digital_asset_library`
- `az_event/az_event_trellis`
- `az_finder`
- `az_http`
- `az_marketing_cloud`
- `az_migration`
- `az_news/az_news_export`
- `az_news/az_news_feeds`
- `az_paragraphs/az_paragraphs_link_group`
- `az_paragraphs/az_paragraphs_views_side_by_side`
- `az_publication`
- `az_publication/az_publication_bibtex`
- `az_publication/az_publication_doi`
- `az_publication/az_publication_import`
Close #3586 
Enable an experimental module and see a warning that says to use at your own risk.
- **Minor release …

Close #3586 Set lifecycle key in info files if not stable.

---

modules/custom/az_person/az_person.module

This PR applies a constraint for Uniqueness on the NetId field.
#3561 
#3591 
- Edit a person and add a NetID, and save them.
- Edit a second person and verify that attempting to save them with an identical netID causes an error.
- Verify that attempting to add a netID that is not identical does not cause an error
- Verify that two people can both be saved with empty netIDs.

Fixes #3591 Add NetID Unique Constraint

---

modules/custom/az_card/js/az-card-no-follow.js
modules/custom/az_finder/js/active-filter-count.js
modules/custom/az_paragraphs/az_paragraphs_text_media/js/az_paragraphs_az_text_media_youtube.js
modules/custom/az_select_menu/js/az-select-menu.js

Updated JS 
Close #3602 
Close #3087 

Close #3602 transpile JS with build tools `lando yarn run build`

---

modules/custom/az_publication/src/AZAuthorListBuilder.php

This PR changes the entity list builder of author entities such that they are ordered by name rather than by id.
Ideally, I think it would be preferable to sort them by last name, first name, but that may be challenging in an entity list builder context because first and last names are fields, rather than properties of the entity itself. Currently, this PR sorts by overall name.
#3639 
- enable `az_publication` and `az_publication_doi`
- visit `/admin/content/az-publication/import/doi`
- import doi `10.1001/jama.2013.284427`
- visit `/admin/structure/az_author`
- verify that authors are sorted by name
- …

Fixes #3639 Order Authors by Name

---

CONTRIBUTING.md

This PR adds some documentation for the `az-core-distribution-config` and  `az-core-config-export-single` commands to the contributing document.
#3619
No code changes included. Inspect the contents of `CONTRIBUTING.md`

Fixes #3619 Add Documentation for az-core-distribution-config

---

modules/custom/az_paragraphs/az_paragraphs_photo_gallery/templates/paragraph--az-photo-gallery.html.twig

Resolves an issue with the Quickstart Photo Gallery paragraph type originating from a potential vulnerability in the Bootstrap carousel component.
This PR replaces `href` attributes on links in the photo gallery template with `data-target` attributes instead. It does not change `<a>` elements to `<button>` elements (as recommended by the [Bootstrap 4 documentation on carousels](https://getbootstrap.com/docs/4.6/components/carousel/#with-controls)) since this could introduce unwanted styling changes. Changing those elements to buttons could be a future improvement, however.
If this change requires release notes: provide a summary of changes, how to 
use this change, and any related links. This content will be pasted in the 
[release …

Closes #3666 Update Photo Gallery to prevent potential XSS vulnerability

---

themes/custom/az_barrio/templates/layout/page.html.twig

#3686 
If this change requires release notes: provide a summary of changes, how to 
use this change, and any related links. This content will be pasted in the 
[release notes](https://github.com/az-digital/az_quickstart/releases). Use 
markdown format to ensure proper pasting of information.
```
Add markdown of release notes here.
```

Closes #3686 Empty view blocks causing sidebar region to render.

---

composer.json

https://www.drupal.org/project/drupal/releases/10.3.4
https://www.drupal.org/project/drupal/releases/10.3.3
```
Updates Drupal core to 10.3.4.  Includes update for twig/twig package that addresses [CVE-2024-45411](https://github.com/advisories/GHSA-6j75-5wfj-gh66).
```
Closes #3700

Closes #3700: Update drupal/core-recommended to 10.3.4.

---

modules/custom/az_event/az_event_trellis/az_event_trellis.libraries.yml
modules/custom/az_publication/az_publication.libraries.yml
themes/custom/az_barrio/az_barrio.libraries.yml

This pull request aims speed up first page load after updates for logged in users.
Drupal attempts to minify javascript on the fly, and in order to do that it needs to know which js is already minified so that it can be skipped.
Close #3730 
Determine page load speed before and after this PR.
Also, here are some troubleshooting steps.
> If you get 8 second load times with core aggregation and no advagg, the following would be useful:
> 
> 1. Can you look in the dev tools network tab and identify which aggregates are taking long to process (or if it's all of them).
> 
> 2. Can you check your js and css folders to check how many aggregates are being created - i..e is it one or two dozen or many dozens of aggregates?
> 
> 3. If a particular aggregate is taking longer to produce, can you …

Close #3730 mark minified JS as minified.

---

modules/custom/az_finder/css/taxonomy-index-tid-widget.css
modules/custom/az_finder/src/Plugin/better_exposed_filters/filter/AZFinderTaxonomyIndexTidWidget.php

This PR makes the following changes to the styling of the AZ Finder exposed form:
1. Adjusts the spacing between each fieldset element to provide a better display of multiple vocabulary filters.
2. Slightly reduce the font size of top-level vocabulary terms, to provide a distinction between the blue vocabulary labels and the blue collapsible top-level terms.
3. Move the top margin for the form from the h2 block title to the main div for the exposed form (to provide consistency in case the block title is not displayed).
4. Other minor adjustments to improve spacing and remove redundant styling rules.
- #3718
Probo review site: https://7b5e2985-cedf-4a13-ab91-3a35916c835d--pr-3719.probo.build
Compare the exposed form (the left sidebar) of the demo Finder pages on the Probo site for this PR …

Closes #3718 Improve styling of AZ Finder exposed form, especially for multiple vocabulary filters

---

themes/custom/az_barrio/templates/layout/page.html.twig

This PR removes the extra `role="main"` from the AZ Barrio page template since [there should only be one `main` role on a page](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/main_role#accessibility_concerns).
```
Note: This release removes div[role=main] from every page since a <main> element already exists with that role. If your site's CSS or JS depend on this landmark to function, you'll need to target that div in another way.
```
- #3714
Probo review site: https://7b5e2985-cedf-4a13-ab91-3a35916c835d--pr-3715.probo.build/
Confirm that pages on the review site only have one instance of `role="main"` in the source.
- **Other or …

Closes #3714 Extra main landmark role in page template

---

composer.json

https://www.drupal.org/project/drupal/releases/10.3.6
```
_Note: Updates Drupal core to 10.3.6 that addresses [CVE-2024-45411](https://github.com/advisories/GHSA-mg8j-w93w-xjgc)._
```
Closes #3751 

Closes #3751: Update drupal/core-recommended to 10.3.6 (addresses CVE-2024-45440).

---

modules/custom/az_event/az_event_trellis/az_event_trellis.libraries.yml
modules/custom/az_finder/az_finder.libraries.yml
modules/custom/az_publication/az_publication.libraries.yml
themes/custom/az_barrio/az_barrio.libraries.yml

Addresses various discrepancies in various library definitions for external and already minified assets.
Closes #3758

Closes #3758: Ensure all external and minified library assets are properly configured.

---

modules/custom/az_mail/config/quickstart/smtp.settings.yml

Updates SMTP settings config included in `az_mail` module that was updated in the 2.11.x branch but not 2.10.x.
See #3589
Closes #3780

Closes #3780: Add missing SMTP module config to address test failures in 2.10.x

---

composer.json

https://www.drupal.org/sa-core-2024-002
```
Updates Drupal core to 10.2.10. Includes updates that address [SA-CORE-2024-002](https://www.drupal.org/sa-core-2024-002) and [CVE-2024-45440](https://github.com/advisories/GHSA-mg8j-w93w-xjgc).
```
Closes #3777

Closes #3777: Update drupal/core-recommended to 10.2.10 for SA-CORE-2024-002 and CVE-2024-45440

---

.github/pull_request_template.md

Updates Release notes section in PR template
UPDATES THIS SECTION
If this change requires release notes: provide a summary of changes, how to 
use this change, and any related links. This content will be pasted in the 
[release notes](https://github.com/az-digital/az_quickstart/releases). Use 
markdown format to ensure proper pasting of information.
```
Add markdown of release notes here.
```
Closes #3787 

Closes #3787: Update release notes section in pull_request_template.md

---

modules/custom/az_carousel/config/install/views.view.az_carousel.yml

Closes #3784 with these changes:
1. Updates the Reorder Carousel Items view display to use the "Access Draggableviews" permission for governing access.
2. Removes the access override for the Carousel Block view display (since it already matches the Default display).
#3784 
Probo review site: https://7b5e2985-cedf-4a13-ab91-3a35916c835d--pr-3785.probo.build
1. Install the Quickstart Carousel Item module (if it isn't already installed).
3. Go to the Reorder Carousel Items view display at `/admin/structure/views/view/az_carousel/edit/reorder_carousel_items`.
4. Confirm that that the Access permission for the display is "Access Draggableviews" instead of "View published content".
5. Go to the Carousel Block view display.
6. Click on "Permission" next to Access and confirm that "All displays …

Closes #3784 Incorrect access permission for Reorder Carousel Items view display

---

composer.json

Prepare 2.11.x branch for new minor release branch 2.12.x

---

.github/workflows/prepare-for-minor-release.yml

Close #3838 Update prepare-for-minor-release.yml with new release branches

---

composer.json

CSL Group elements operate as an implicit conditional and are intended to not display if child elements are empty. `seboettg/citeproc-php` presently has an issue where this conditional test fails for label elements. This can be seen in the APA style, where the unused `number-of-volumes` group is displayed for book-like citations:
`Wildcat, W. (2024). History of Wildcats. In Wildcat Anthology (Version V1, 1–, Issues 4, pp. 200-230). The University of Arizona Press.`
This PR adds a patch from the dev branch of `seboettg/citeproc-php` that causes groups with labels to not display if the label is empty.
Fixes #3852 
- enable `az_publication`
- set APA as the default citation style at `/admin/config/az-quickstart/settings/az-publication`
- Create a **BOOK** publication
- Set version to `V1`
- …

Fixes #3852 Citation Style Group Rendering

---

modules/custom/az_migration/migrations/az_node_flexible_page.yml

Update the flexible page migration so that it migrates summary field formats correctly.
```
This release changes the flexible page migration so that summary fields are migrated to use the plain_text text format instead of the format set on the source site.
```
Close #3813 

Close #3813 set default format to plain_text in flexible page summary field migration.

---

modules/custom/az_digital_asset_library/az_digital_asset_library.info.yml
modules/custom/az_finder/az_finder.info.yml
modules/custom/az_google_tag/az_google_tag.info.yml
modules/custom/az_seo/az_seo.info.yml

This PR adds dependencies to `az_core` for modules with configuration overrides. These modules have a defacto dependency on az_core because of their need for the `QuickstartConfigProvider`. This is a new regression in Drupal 10.3 that appear linked to some changes in profile or module dependency resolution - previously it appears that maybe we were reliant on on the listed order of the modules in the install profile.
#3874 
- install site
- log in as admin
- verify that `/admin/config/services/google-tag` gives the tag id of the `az_comprehensive` tag
- Verify that other modules using overrides work correctly. This includes:
- `az_google_tag`
- `az_seo`
- `az_security`
- `az_finder`
- `az_cas`
- `az_mail`
- `az_digital_asset`
- …

Fixes #3874 Modules using Configuration Overrides should declare az_core dependency

---

composer.json
modules/custom/az_paragraphs/az_paragraphs.info.yml
modules/custom/az_paragraphs/az_paragraphs.install
modules/custom/az_paragraphs/az_paragraphs.module
modules/custom/az_paragraphs/config/optional/editor.editor.az_standard.yml

This PR proposes to revert the addition of the CKEditor Anchor Link module due to some issues discovered as part of Quickstart 2.12 testing, including one that could result in data loss: [IDs are stripped from links](https://www.drupal.org/project/anchor_link/issues/3443785).
This reverts commit ae8c35ff0f31ad33f9f0f92a13a7cd97fdb10ede from pull request #3219.
- #3870
Probo review site: https://7b5e2985-cedf-4a13-ab91-3a35916c835d--pr-3872.probo.build

Closes #3870 Revert #3219: Add anchor link plugin for CKEditor5

---

.probo.yaml
composer.json

https://www.drupal.org/project/drupal/releases/10.2.11
```
_Note: Updates Drupal core to 10.2.11. Includes updates that address [SA-CORE-2024-003](https://www.drupal.org/sa-core-2024-003), [SA-CORE-2024-004](https://www.drupal.org/sa-core-2024-004), [SA-CORE-2024-006](https://www.drupal.org/sa-core-2024-006), [SA-CORE-2024-007](https://www.drupal.org/sa-core-2024-007), and [SA-CORE-2024-008](https://www.drupal.org/sa-core-2024-008).
```
#3893

#3893: Update drupal/core-recommended from 10.2.10 to 10.2.11 (addresses multiple security vulnerabilities).

---

.probo.yaml
composer.json

https://www.drupal.org/project/drupal/releases/10.3.7
https://www.drupal.org/project/drupal/releases/10.3.8
https://www.drupal.org/project/drupal/releases/10.3.9
```
_Note: Updates Drupal core to 10.3.9. Includes updates that address [SA-CORE-2024-003](https://www.drupal.org/sa-core-2024-003), [SA-CORE-2024-004](https://www.drupal.org/sa-core-2024-004), [SA-CORE-2024-006](https://www.drupal.org/sa-core-2024-006), [SA-CORE-2024-007](https://www.drupal.org/sa-core-2024-007), and [SA-CORE-2024-008](https://www.drupal.org/sa-core-2024-008).
```

#3893: Update drupal/core-recommended from 10.3.6 to 10.3.9 (addresses multiple security advisories).

---

composer.json
modules/custom/az_seo/az_seo.info.yml
modules/custom/az_seo/az_seo.install

Add schema_metatag module to composer.json
Retroactively install schema_metatag module on existing sites.
Set schema_metatag as a dependency of az_seo so it is installed by default.
Closes #3903
Go to https://ba798ad1-83eb-423b-a219-b0e900cdfa18.probo.build/
Ensure that az_seo module is enabled. (Likely)
Ensure that schema_metatag is enabled.

Close #3903 Add schema_metatag module as dependency of az_seo

---

.github/workflows/review-site.yml

Update "Update Review Site" workflow to use the latest commit message when rebuilding demo.quickstart.arizona.edu
Closes #3277 

Closes #3277: Update "Update Review Site" workflow to add a more descriptive commit message when rebuilding demo.quickstart.arizona.edu

---

modules/custom/az_news/config/install/core.entity_view_display.node.az_news.az_marquee.yml

Removes the image caption on Recent News Marquee view paragraphs.
If this change requires release notes: provide a summary of changes, how to use this change, and any related links. This content will be pasted in the [release notes](https://github.com/az-digital/az_quickstart/releases). Use markdown format to ensure proper pasting of information. [Release notes example](https://github.com/az-digital/az_quickstart/releases/tag/2.11.0)
```
Image captions are no longer displayed on the top AZ News story when using the Recent News Marquee display option of the View paragraph.
```
#3438 
1. Navigate to the [Pages > News Views page](https://7b5e2985-cedf-4a13-ab91-3a35916c835d--pr-3937.probo.build/pages/news-view-paragraphs) and scroll to …

Closes #3438: Image captions visible in AZ News - Recent News Marquee paragraph

---

modules/custom/az_publication/az_publication.install

Resolves an issue where an AZ Publication database update can fail when no publication nodes exist by updating the assignment of `$sandbox['#finished']` at the end of the `az_publication_update_1021002()` function in az_publication.install.
I followed the example [here in Drupal core](https://git.drupalcode.org/project/drupal/-/blob/11.x/core/lib/Drupal/Core/Extension/module.api.php#L829) and was able to run the update successfully on a local site with no publication nodes.
- #3949 
Run the database update on a site that has AZ Publication installed but does not have any publication nodes.
- **Minor …

Closes #3949 AZ Publication database update fails if no publication nodes exist

---

composer.json

https://www.drupal.org/project/drupal/releases/10.3.10
Closes #3942 
- General / smoke testing

Closes #3942: Update drupal/core-recommended to 10.3.10.

---

composer.json

Let's try to get this feature merged into the module and released.
Close #3954
Log into probo
Go to `/node/42/edit` to edit a node with paragraphs that use a viewsreference field .
See that the label formatter works.

Close #3954 Update patch for viewsreference label field formatter.

---

modules/custom/az_core/az_core.module

Apply a form layout style for menu links form
this file specifically: claro-node-form-overrides.css
Closes #3697 
Edit any menu link and compare the layout of the form with the layout when editing a page, event, or any other node.

Closes #3697 Layout of the menu link edit form does not match the node edit form

---

modules/custom/az_news/templates/field--node--az-news.html.twig

Updated line 54 in _field--node--az-news.html.twig_, replacing \<div\> element with \<h2\> element.
Closes #1831
1. Create AZ News article, include an added contact
2. Confirm field label is now wrapped by an h2 element

Close 1831 Update AZ News default display to fix contacts heading tags

---

composer.json

https://www.drupal.org/project/drupal/releases/10.3.11
Closes #3976

Closes #3976: Update drupal/core-recommended to 10.3.11

---

modules/custom/az_paragraphs/config/optional/editor.editor.az_standard.yml

Updates the "Zero Margin Top" and "Zero Margin Bottom" CKEditor styles for the Standard text format as follows:
- Zero Margin Top (`span.mt-0`): Removed this style from the list as it has no effect when combined with any other styles that users may select from the CKEditor toolbar.
- Zero Margin Bottom (`span.mb-0`): Changed this style from `span.mb-0` to `p.mb-0` to allow editors to remove the bottom margin on `<p>` elements from Arizona Bootstrap.
This will not change any existing content: the updated Zero Margin Bottom style will only be applied when users manually select them while creating or updating text content.
- #3994
Probo review site: https://7b5e2985-cedf-4a13-ab91-3a35916c835d--pr-3995.probo.build
1. Add a new Text paragraph to a page
2. Type two lines of text into the …

Closes #3994 Zero margin styles in CKEditor have no effect

---

modules/custom/az_migration/migrations/az_menu_links.yml

This PR allows menu links which are to nodes which were originally UAQS Basic pages (which have been converted to flexible pages in the migration) to work.
The migration for this type of node was not previously included in the allowed migration lookup for link processing.
Closes #4003 
- Migrate a site which contains menu links to basic pages

Fixes #4003 Allow Converted UAQS Basic Pages in Menu link migration.

---

modules/custom/az_accordion/src/Plugin/Field/FieldType/AZAccordionItem.php
modules/custom/az_card/src/Plugin/Field/FieldType/AZCardItem.php

Remove FieldType category from Accordian and Card FieldTypes. Closes #3992.
Removed the "category" from the Field Type definitions for Accordion and Card Field Types. Without a `.field_type_categories.yml` file that defines the  Field Type category, the attribute in Field Type definition causes an assertion error.  
#3992 
Since QS local builds don't have ASSERT_ACTIVE set to true the way I tested was to add the following to `settings.php` inside the local development container:
```
assert_options(ASSERT_ACTIVE, TRUE);
```
Then try adding a new field to any content type. Previously this would have resulted in an error. Now it should not.
- **Other or …

Closes #3992: Remove FieldType Categories

---

composer.json

Upgrades the google_tag module from 2.0.7 to 2.0.8: https://www.drupal.org/project/google_tag/releases/2.0.8.
It looks like we didn't upgrade Quickstart 2.11 to version 2.0.7, so for 2.11 the module will go from 2.0.6 to 2.0.8:
- #3926
```
_Note: This release contains a security update for the Google Tag module addressing two moderately critical security vulnerabilities ([SA-CONTRIB-2025-011](https://www.drupal.org/sa-contrib-2025-011) and [SA-CONTRIB-2025-012](https://www.drupal.org/sa-contrib-2025-012))._
```
- #4011

Closes #4011: Upgrade google_tag for SA-CONTRIB-2025-011, SA-CONTRIB-2025-012

---

.github/workflows/security.yml

Replaces usage of symfony security checker GH action in the `Dependency check` of our GH Actions `Security` workflow with the built-in `composer audit` command.
Closes #4031 

Closes #4031 Replace symfony security checker with composer audit in GH actions security workflow

---

modules/custom/az_demo/config/install/views.view.az_finder.yml

This pull request adds a result summary that appears at the top of every finder view.
Close #3990 
On the Probo demo site,navigate to any of the finder views.
Example `/finders/news`

Close #3990 Add result summary to finder in az_demo.

---

composer.json

Adds a patch to allow the conversion of animated gifs to animated webp if the `advanced.coalesce` setting is enabled in the imagemagick toolkit configuration.
Close #4017 
Close #1606
https://drupal.org/i/3295470
```
Site owners are now able to request enabling the imagemagick toolkit on their site to support animated gifs and better image processing. https://uarizona.service-now.com/sp?id=sc_cat_item&sys_id=af0469a4db5db4109627d90d689619f6
```

Close #4017 Imagemagick fails to convert animated gifs into animated webps Close #1606 enable animated gifs.

---

modules/custom/az_card/templates/az-card.html.twig
modules/custom/az_demo/data/az_demo_card_paragraph.json

This PR does the following:
1. Resolves #4024 by updating the AZ Card template to prevent the `card-body` class from being included on the div below the card image when the card title is on the image, the body is empty, and a link is present with the "Hidden link title" link style.
2. Changes the card link to use an aria-label for the link text instead of actual text inside the `<a>` element. I believe this method is accessible according to https://www.w3.org/WAI/WCAG21/Techniques/aria/ARIA8. This change is necessary as a follow-up to the first change to prevent an additional issue where the card image is not clickable.
- **(Update Feb 5, 2025)** I checked with @accesswatch and he was OK with this change. Thanks Jeff!
3. Adds a minor fix for the AZ Card template to correctly skip creating …

Closes #4024: Extra white space on title-on-image cards having an empty body and a hidden link

---

composer.json

https://www.drupal.org/project/drupal/releases/10.4.2
> 
> Drupal 10.4.x will receive security support until December 2025.
> 
> **All changes in this release**
> 
> - [Issue #3495881 by godotislate, bkosborne, catch, kushagra.goyal: Firefox retains form_build_id on form reloads, causing old form cache entry to be used and creating weird behavior for the Media Library widget](https://git.drupalcode.org/project/drupal/commit/a5b584460462362c9a24002d5f73edc3acea4ed0)
> - [Issue #3503556 by tom konda: Wrong Regular Expression for string comparison in Nightwatch.js …

Closes #4042: Update Drupal core from 10.4.1 to 10.4.2

---

composer.json

https://www.drupal.org/project/drupal/releases/10.3.12
> 
> Drupal 10.3.x will receive security coverage until June 2025.
> 
> The Twig templating library has issued a [security advisory](https://github.com/twigphp/Twig/security/advisories/GHSA-3xg3-cgvq-2xwr). Drupal core is not vulnerable, but previous versions of the drupal/core-recommended package only allowed insecure versions of Twig to be installed. This patch release upgrades Twig to 3.19.0 as a public security hardening.
> 
> All changes in this release
> 
> - [Issue #3503195 by alexpott, longwave, loopy1492: Twig needs updating for …

#4044: Update Drupal core from 10.3.11 to 10.3.12 (2.12.x)

---

composer.json

https://www.drupal.org/project/drupal/releases/10.3.12
> 
> Drupal 10.3.x will receive security coverage until June 2025.
> 
> The Twig templating library has issued a [security advisory](https://github.com/twigphp/Twig/security/advisories/GHSA-3xg3-cgvq-2xwr). Drupal core is not vulnerable, but previous versions of the drupal/core-recommended package only allowed insecure versions of Twig to be installed. This patch release upgrades Twig to 3.19.0 as a public security hardening.
> 
> All changes in this release
> 
> - [Issue #3503195 by alexpott, longwave, loopy1492: Twig needs updating for …

#4044: Update Drupal core from 10.3.11 to 10.3.12 (2.11.x)

---

modules/custom/az_publication/config/install/views.view.az_publications.yml

Adds a new "List" display to the AZ Publications view which is a simple listing of publications on the site. Editors can filter the view using taxonomy term IDs.
Questions:
1. Is "List" an acceptable name for this new display?
2. Currently, to filter the list of publications based on a Publications Categories taxonomy term, site editors need to specify the citation style and then the taxonomy term ID in the Argument field of the view paragraph (such as `az_mla/54`). Should we simplify this and remove the citation style contextual filter so that editors would only need to enter the taxonomy term ID? Then the display would always use the site's default citation style.
3. The new display does not specify a taxonomy vocabulary for validation of taxonomy term values so that custom sites using …

Closes #4049: Add a general view display to AZ Publications view without exposed filters

---

modules/custom/az_core/az_enterprise_attributes_import/config/install/migrate_plus.migration.az_enterprise_attributes_import.yml

Adds a skip_on_value process to the name field.
Skips the entire row if the value is '-'
Close #4071 
Enable the Quickstart Enterprise Attributes Import module
Look in the taxonomy terms for the hyphen.

Close #4071 Skip hyphen when importing enterprise attributes.

---

modules/custom/az_global_footer/az_global_footer.install
modules/custom/az_global_footer/data/az_global_footer.json
themes/custom/az_barrio/az_barrio.theme

Removing the "Diversity" link found in the Global Footer and update land acknowledgement statement by removing "Committed to diversity and inclusion ,".  
Closes #4065

Close #4065 Remove "Diversity" link from global footer and update land acknowledgement.

---

modules/custom/az_core/az_core.libraries.yml
modules/custom/az_core/az_core.module
modules/custom/az_core/config/quickstart/chosen.settings.yml
modules/custom/az_core/css/az-core-chosen.css

Adjusts the default width setting in Chosen and adds admin-specific style overrides.
Closes #3997
Visit a page with Chosen enabled to see the selector and dropdown box sizing.

Closes #3997 Adjust default Chosen width

---

modules/custom/az_publication/config/install/views.view.az_publications.yml

Removes the taxonomy vocabulary validation from the AZ Publications Search and Person view displays so that terms from any vocabulary can be used for filtering.
- #4067
```
Use any taxonomy vocabulary to filter publications in publication views.
```
Probo review site: https://7b5e2985-cedf-4a13-ab91-3a35916c835d--pr-4069.probo.build
- Confirm that AZ Publications Search and Person view displays still work as expected.

Closes #4067: Remove taxonomy vocabulary validation from AZ Publications view displays

---

composer.json

Adds metatag module patch to prevent persistent fatal error condition that breaks all authenticated web requests / site search requests.
Root cause of error and steps to reproduce still being investigated.
Closes #4080
See https://www.drupal.org/project/metatag/issues/3503253
Steps to reproduce error condition still unknown

Closes #4080: Add patch for preventing persistent metatag module TypeError.

---

composer.json

https://www.drupal.org/sa-core-2025-001
https://www.drupal.org/sa-core-2025-002
https://www.drupal.org/sa-core-2025-003
```
_Note: Updates Drupal core to 10.3.13. Includes updates that address [SA-CORE-2025-001](https://www.drupal.org/sa-core-2025-001), [SA-CORE-2025-002](https://www.drupal.org/sa-core-2025-002), [SA-CORE-2025-003](https://www.drupal.org/sa-core-2025-003)._
```
#4085

#4085: Update drupal/core-recommended to 10.3.13 for SA-CORE-2025-001, SA-CORE-2025-002, SA-CORE-2025-003 (2.11.x)

---

composer.json

https://www.drupal.org/sa-core-2025-001
https://www.drupal.org/sa-core-2025-002
https://www.drupal.org/sa-core-2025-003
```
_Note: Updates Drupal core to 10.3.13. Includes updates that address [SA-CORE-2025-001](https://www.drupal.org/sa-core-2025-001), [SA-CORE-2025-002](https://www.drupal.org/sa-core-2025-002), [SA-CORE-2025-003](https://www.drupal.org/sa-core-2025-003)._
```
#4085

#4085: Update drupal/core-recommended to 10.3.13 for SA-CORE-2025-001, SA-CORE-2025-002, SA-CORE-2025-003 (2.12.x)

---

modules/custom/az_accordion/az_accordion.module
modules/custom/az_accordion/src/Plugin/Field/FieldFormatter/AZAccordionDefaultFormatter.php

Follow-up to #3808.  Removes deprecated variable from az_accordion theme implementation.
Closes #3812
Ensure az_accordion fields still work, e.g. in AZ Accordion paragraphs.

Closes #3812: Remove deprecated aria_controls variable from az_accordion theme implementation.

---

modules/custom/az_publication/az_publication_bibtex/src/Plugin/migrate_plus/data_parser/AZBibtex.php
modules/custom/az_publication/az_publication_bibtex/src/Processor/AZStripHtmlProcessor.php

This PR applies additional Processors to Bibtex entries to handle cases where the Bibtex source injected HTML into the bibtex entry, or where the bibtex entry had tags in an unexpected case (usually this is the DOI field).
Closes #4097 
Closes #4098 
Closes #4099 
- enable `az_publication` and `az_publication_doi`
- visit `/admin/content/az-publication/import`
- import DOI `10.1021/acs.est.1c01919`
- View and verify that the imported publication does not have `&amp;` in its journal title
- Verify that the imported publication node has a value in the `Digital Object Identifier (DOI)` field on the edit page
- Import DOI `10.5334/cstp.253`
- View and verify that the imported publication does not have HTML or other entities in its title …

Fixes #4097, Fixes #4098, Fixes #4099 Handle HTML and tag case in AZBibtex

---

config/install/user.role.az_content_admin.yml
modules/custom/az_google_tag/az_google_tag.module
modules/custom/az_google_tag/az_google_tag.permissions.yml

Add a new permission for accessing the Quickstart Analytics toolbar menu link.
Closes #2764
Log in as a user with toolbar access (e.g., Content Editor), click Quickstart in the toolbar menu, and observe they no longer have a link to Quickstart Analytics.
Log in as a user with Access Quickstart Analytics permission (e.g., Content Administrator), click Quickstart in the toolbar menu, and observe they have a link to Quickstart Analytics.

Closes #2764 Add Quickstart Analytics permission and toolbar link check.

---

composer.json

**NOTE:** Wednesday, March 19 is the scheduled Core Security release window.
https://www.drupal.org/project/drupal/releases/10.4.4
> 
> Drupal 10.4.x will receive security support until December 2025.
> 
> **All changes in this release**
> 
> - [Issue #3508733 by gábor hojtsy, griffynh: Add griffynh as provisional core team facilitator](https://git.drupalcode.org/project/drupal/commit/2a2b4a415a61c14f612e808e061b479b292fb5f0)
> - [Issue #3487014 by liam morland, nod_, smustgrave, quietone: Fix documentation for optional params in MessengerInterface](https://git.drupalcode.org/project/drupal/commit/957c16fc138b7d528320b2 …

Closes #4128: Update Drupal core from 10.4.3 to 10.4.4

---

composer.json

https://www.drupal.org/sa-core-2025-004
```
_Note: Updates Drupal core to 10.3.14. Includes an update that addresses [SA-CORE-2025-004](https://www.drupal.org/sa-core-2025-004)._
```
- #4132

#4132: Update drupal/core-recommended to 10.3.14 for SA-CORE-2025-004 (2.12.x)

---

composer.json

https://www.drupal.org/sa-core-2025-004
```
_Note: Updates Drupal core to 10.3.14. Includes an update that addresses [SA-CORE-2025-004](https://www.drupal.org/sa-core-2025-004)._
```
- #4132

#4132: Update drupal/core-recommended to 10.3.14 for SA-CORE-2025-004 (2.11.x)

---

modules/custom/az_person/az_person_profiles_import/migrations/az_person_profiles_import.yml
modules/custom/az_person/az_person_profiles_import/src/Plugin/migrate/process/AZPersonEmptyCoalesce.php

Profiles integration does not currently use Preferred Names, only given names. This PR updates the migration to use preferred names where available. A Process plugin is included that does empty coalesce checking because the json parser from migrate plus returns empty rather than null for missing keys.
#4142 
**Note: Testing this PR requires a profiles API Token!**
- enable `az_person_profiles_import`
- If you intend to test MANY Persons, enable `az_http`
- visit `/admin/config/az-quickstart/settings/az-person-profiles-import` and add your profiles API token.
- visit `/admin/content/profiles/import`
- Import some test users that use a mix of preferred or default names.
- Verify that users are imported with either their preferred name, or if they do not have one, their default name.
- …

Fixes #4142 Profiles Integration Use Preferred Names

---

modules/custom/az_news/config/install/core.entity_view_display.node.az_news.az_marquee.yml

Updates the Marquee display of the AZ News content type to use the thumbnail image instead of the featured image.
(draft)
```
In the Recent News Marquee view, the first article's Thumbnail Image is now displayed instead of the Featured Image. The Marquee display of the AZ News content type was updated for this change: please review any custom views which may use this display.
```
- #3500 
Probo review site: https://7b5e2985-cedf-4a13-ab91-3a35916c835d--pr-4147.probo.build
Confirm that the first article in an AZ News Recent News Marquee view display can be set to a specific thumbnail image.
- **Minor …

Closes #3500: Modify Marquee display of News to use the Thumbnail Image instead of the Featured Image

---

modules/custom/az_event/az_event_trellis/config/install/az_event_trellis.settings.yml
modules/custom/az_event/az_event_trellis/config/install/migrate_plus.migration.az_trellis_events.yml
modules/custom/az_event/az_event_trellis/src/TrellisHelper.php

This PR is based on #4053 to test the Trellis Event v3 API, which presents the attributes in this fashion (note that the attributes are true JSON arrays, a change over v2)
```
"Attributes" : [ {
"Audiences" : [ "Undergraduate Student", "Graduate Student" ],
"Topic" : [ "Health & Wellness" ],
"Category" : [ "Lectures, Workshops & Panels" ]
} ],
```
#4040 
- enable `az_event_trellis`, `az_enterprise_attributes_import`, and `az_http`
- clear cache
- visit `/admin/trellis-event-importer`
- search for and import events with known attributes
- edit the event and verify the attributes are imported correctly
- …

Fixes #4040 Map enterprise attributes (v3 API)

---

composer.json

Applies latest updates to Config Synchronizer + associated modules.  Creating as a combined PR for easier testing.
Closes #4166 
- General testing
- Apply configuration updates on an existing site

Closes #4166: Update Config Synchronizer + dependencies.

---

modules/custom/az_flexible_page/config/install/core.entity_view_display.node.az_flexible_page.az_card.yml
modules/custom/az_flexible_page/config/install/core.entity_view_display.node.az_flexible_page.az_row.yml

On AZ Page row and card view displays, the following changes are made.
1. Added `aria-hidden="true"` on "read more" links
2. Added underline to title of page on hover
If this change requires release notes: provide a summary of changes, how to use this change, and any related links. This content will be pasted in the [release notes](https://github.com/az-digital/az_quickstart/releases). Use markdown format to ensure proper pasting of information. [Release notes example](https://github.com/az-digital/az_quickstart/releases/tag/2.11.0)
```
New hover style for AZ Pages in display of Row or Card is added -- underline title on hover. Read more link of these displays are hidden from screen readers.
```
Closes #4163 …

Closes #4163: Updates AZ Page Card and Row Displays

---

phpstan.neon

After the inclusion of Drush 13, phpstan fails with the following errors:
```
------ ------------------------------------------------------------------------------------------------------ 
Line   web/profiles/custom/az_quickstart/modules/custom/az_core/src/Drush/Commands/AZCoreConfigCommands.php  
------ ------------------------------------------------------------------------------------------------------ 
140    Call to method confirm() on an unknown class Drush\Style\DrushStyle.                                  
💡 Learn more at https://phpstan.org/user-guide/discovering-symbols                                   
251    Call to method confirm() on an unknown class Drush\Style\DrushStyle.                                  
💡 Learn more at https://phpstan.org/user-guide/discovering-symbols …
```

Fixes #4169 Resolve Drush 13 phpstan errors

---

modules/custom/az_event/az_event_trellis/az_event_trellis.views.inc

Presently, the Trellis Event views integration is not translatable. This also causes an issue with an unrelated views hook in `az_publication`. The combination of these two factors prevents adding new views when both `az_event_trellis` and `az_publication` are active.
#4211 
- enable `az_event_trellis`
- enable `az_publication`
- drush cr
- visit `/admin/structure/views/add`
- verify that no whitescreen error occurs
- Visit `/admin/trellis-event-importer` and verify that trellis event imports are not affected.

Fixes #4211 Trellis Events views integration not translatable.

---

modules/custom/az_paragraphs/css/az_paragraphs_full_width.css
modules/custom/az_paragraphs/src/Plugin/Field/FieldFormatter/AZBackgroundMediaFormatter.php

Updates az-aspect-ratio stylings and checks to no longer specifically target full-width-background. The change allows content-width backgrounds to properly display with the az-aspect-ratio setting.
```
_Notes: Fix az-aspect-ratio setting with content-width Text on Media paragraphs.
```
Closes #1546 

Closes #1546 Fix az-aspect-ratio setting with content-width Text on Media paragraphs.

---

composer.json

Fix the ability to disable fields
Close #4230
to fix https://www.drupal.org/project/field_group/issues/3491233
Go to an entity view display that uses field groups and has a field enabled.
Try to disable the enabled field.

Close #4230 Add patch for field_group module

---

composer.json
modules/custom/az_migration/az_migration.info.yml
modules/custom/az_migration/migrations/az_media.yml
modules/custom/az_migration/src/Plugin/migrate/source/AzFileEntity.php

We use the media_migration module exclusively to migrate from Drupal 7 file_entity module to Drupal 8+ media entity.
At the moment the media migration module development appears to be stalled.
- https://www.drupal.org/project/media_migration/issues/3431903
- https://www.drupal.org/project/media_migration/issues/3494209
```
The Quickstart Migration module (`az_migration`) and by extension Arizona Quickstart no longer depends on Media Migration module (`media_migration`).  
This module has been deprecated as a Quickstart dependency and will be removed in a future minor release of Quickstart. Site owners should uninstall this module or add it to their site-specific composer.json files to continue using it.
```
#1640 
- **Other or …

Close #1639 remove dependency on media_migration contrib module. (#4217)

---

composer.json

Adds drupal/migmag (MIgrate Magician) module, which is still a dependency of az_migration.  Follow-up to #4217 and #4245.
- #1639

#1639: Add missing drupal/migmag module.

---

.github/workflows/ci.yml
modules/custom/az_cas/tests/src/Functional/AzCasAdminSettingsTest.php
modules/custom/az_cas/tests/src/Functional/AzCasDisableLoginFormTest.php
modules/custom/az_cas/tests/src/Functional/AzCasDisablePasswordResetTest.php
modules/custom/az_demo/tests/src/Functional/AZDemoContentTest.php
themes/custom/az_barrio/tests/src/Functional/AzBarrioAdminTest.php
themes/custom/az_barrio/tests/src/Functional/AzBarrioTest.php

- Updates `CI` Github Actions workflow to employ a `matrix` strategy for running PHPUnit tests concurrently
- Consolidates (or splits up) existing PHPUnit tests to optimize for concurrency
Closes #4251

Closes #4251: Use GitHub Actions matrix for PHPUnit + optimize existing tests for concurrency.

---

composer.json

https://www.drupal.org/sa-contrib-2025-043
https://www.drupal.org/project/block_class/releases/4.0.1
```
_Note: This release contains an [update for the Block Class module](https://www.drupal.org/project/block_class/releases/4.0.1) that addresses a moderately critical issue that allowed an XSS vulnerability ([SA-CONTRIB-2025-043](https://www.drupal.org/sa-contrib-2025-043))._
```
Closes #4270 

Closes #4270: Update drupal/block_class from 4.0.0 to 4.0.1 (addresses SA-CONTRIB-2025-043)

---

modules/custom/az_person/az_person_profiles_import/az_person_profiles_import.module

This PR updates the revision log messages that are created when importing from the profiles API. Currently, they do not reflect the user or time they were created, instead reflecting the time and user from last time someone updated the node (though a new revision is created).
Closes #4262 
- enable `az_person_profiles_import`
- **important:** comment out the following line 84 in `az_person.module`: `$form[$field]['#disabled'] = TRUE;`
- This is necessary to test easily because otherwise you will not be able to overwrite a field to simulate that the person has changed on a field that the profiles API will import to. (Alternatively, you can import a user that you **know** has changed since last time they were imported). The data changing is a requirement of a revision.
- Add your profiles …

Fixes #4262 Profiles Import revision log message does not reflect current time and user

---

modules/custom/az_course/az_course.routing.yml
modules/custom/az_course/src/Form/CourseImportForm.php

This PR provides additional instructions on the import page for `az_course`.
- Some instructions are given as to how the form functions
- A placeholder attribute is added showing expected format
- Warn users about the potential for timeouts and mention the potential solution of `drush` or `az_http`
- give each submit button a title attribute that describes what it does
#4263 
- enable `az_course` and `az_http`
- visit `/admin/config/az-quickstart/courses`
- review form changes for usability or documentation issues
- test that form functions as expected

Fixes #4263 Course Import Instructions

---

config/install/user.role.az_user_admin.yml

We forgot to add the `assign az_auto_expiring_user role` permission to the `az_user_admin` role in #3665.
This adds it.
This might be blocked by #4276.
Closes #4281
Verify that a user with the `az_user_admin` role can assign the `az_auto_expiring_user_role`

Closes #4281: Add missing 'assign az_auto_expiring_user role' permission to az_user_admin role.

---

themes/custom/az_barrio/az_barrio.theme

Changes University to university in the global footer
If this change requires release notes: provide a summary of changes, how to use this change, and any related links. This content will be pasted in the [release notes](https://github.com/az-digital/az_quickstart/releases). Use markdown format to ensure proper pasting of information. [Release notes example](https://github.com/az-digital/az_quickstart/releases/tag/2.11.0)
```
Global footer is updated to say "The university..."
```
Closes #4307
Observe footer says "...Yaqui. The university strives to build..." with a lowercase `u` …

Closes #4307: Update global footer to use lowercase U in "The university"

---

themes/custom/az_barrio/az_barrio.libraries.yml

Adds `az_barrio/global-styling` library as a dependency to `az_barrio/az-barrio-off-canvas-nav` library to force the `az_barrio/az-barrio-off-canvas-nav` CSS to load after the `az_barrio/global-styling` CSS to fix problem introduced by #1250.
Closes #4330
1. Disable `Institutional header wordmark logo` AZ Barrio theme setting
2. Ensure height of arizona_header redbar element does not change

Closes #4330: Fix red bar height when institutional wordmark is disabled.

---

composer.json

https://www.drupal.org/project/drupal/releases/10.4.7
> 
> Drupal 10.4.x will receive security support until December 2025.
> 
> **All changes in this release**
> 
> - [Issue #3511434 by juandhr, dimpalmangrulkar20@gmail.com, sivaji_ganesh_jojodae, alberto56, quietone, ghost of drupal past, quadrexdev: There are leftover references in comments to long ago renamed ListDefinitionInterface](https://git.drupalcode.org/project/drupal/commit/c5aac1766a719354b8dee761532b42e3f4b15937)
> - [Issue #3511186 by grimreaper: Media Library currentSelection not reset properly](https://git.drupalcode.org/project/drupal/commit/3ff0b26d97 …

Closes #4328: Update Drupal core from 10.4.6 to 10.4.7

---

modules/custom/az_demo/config/install/views.view.az_finder.yml
modules/custom/az_event/az_event.module

- Update the logic of hook_preprocess_views_view() to include az_finder event view
- Update the config yml file to enable `delta` field so that EntityRow can render correct date for recurring events in `/finders/events`
Closes #4278
1. Launch a az_quickstart site locally
2. Go to `\finders\events` and check if recurring events are split into individual rows with correct date (see screenshot)

Closes #4278: events show wrong date in view listings other than calendar

---

modules/custom/az_person/az_person.module

This PR attempts to prepopulate the alphabetical index character on AZ Persons where:
- The content type has the field (`field_az_alphabetical_index`) added
- A last name is available
- The person is saved with `field_az_alphabetical_index` as empty, e.g. the editor did not add one themselves.
- Some special characters are supported, via [PhpTransliteration::removeDiacritics](https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Component%21Transliteration%21PhpTransliteration.php/function/PhpTransliteration%3A%3AremoveDiacritics/10)
```
In circumstances where field_az_alphabetical_index has been added to the AZ Person content type, Quickstart will attempt to prepopulate the index letter field where possible.
```
#4338 
- Log in
- Enable `az_alphabetical_listing`
- Visit …

Fixes #4338 Prepopulate Alphabetical index letters on AZ Person

---

modules/custom/az_event/az_event.views.inc

Addresses a minor PHPCS coding standard that started showing up on all new Quickstart builds (created from the main branch) since a new version of the Druapal Coder module was released early this week.
Closes #4354

Closes #4354: Address PHPCS failure caused by updated Drupal coding standard.

---

az_quickstart.install
composer.json

Resolves #3796. Remove modules jquery_ui_slider, jquery_ui_touch_punch, and media_migration and related media_migration patch. Also remove them from the AZ QS deprecated warning.
Remove jquery_ui_slider, jquery_ui_touch_punch modules, and media_migration. Also remove them from deprecated module warning list and remove related media_migration patch. 
#3796 
Check the list of installed modules.

Closes #3796 Remove modules deprecated as of 2.12.x

---

modules/custom/az_paragraphs/az_paragraphs_photo_gallery/templates/paragraph--az-photo-gallery.html.twig

Sets paragraph photo gallery paragraph sliders to use the carousel image style. This change mirrors the usage of the carousel image style in the Quickstart Carousel Item module.
```
_Notes: Changes Photo Gallery paragraph sliders to use a cropped carousel image style._
```
Closes #4222
1. Create a Page and add a Photo Gallery paragraph.
2. Leave the "Photo Gallery Display" as 'Slider'.
3. Add some images and save.
4. Observe the slider using a cropped carousel image.
https://7b5e2985-cedf-4a13-ab91-3a35916c835d--pr-4359.probo.build/test

Closes #4222 Use carousel image style for paragraph photo gallery slider

---

.github/CODEOWNERS
.github/dependabot.yml

https://github.blog/changelog/2025-04-29-dependabot-reviewers-configuration-option-being-replaced-by-code-owners/
Closes #4321

Closes #4321: Replace dependabot reviewers config option with updated CODEOWNERS config.

---

modules/custom/az_paragraphs/src/Plugin/paragraphs/Behavior/AZPhotoGalleryParagraphBehavior.php

Changes photo gallery to use grid by default.
Closes #4418
1. Create a new Page
2. Add a Photo Gallery paragraph
3. Observe the Photo Gallery Display is set to Grid by default.

Closes #4418 Set photo gallery default to grid

---

composer.json

Adds patch to fix known issue with Bootstrap Barrio's JS library that extends core/tabledrag.js which is causing test failures for all PRs targeting `bootstrap5` branch.
- Closes #4456 
- https://www.drupal.org/project/bootstrap_barrio/issues/3519060

Closes #4456: Add bootstrap_barrio patch to fix tabledrag.js issue causing test failures.

---

modules/custom/az_cas/az_cas.module

Disables the email hostname field on the Bulk Add CAS Users page.
Closes #4453
1. Log in as a user admin and visit the [Bulk Add CAS Users](https://7b5e2985-cedf-4a13-ab91-3a35916c835d--pr-4454.probo.build/admin/people/create/cas-bulk) page.
2. See the email hostname is disabled.
3. Enter a username and click to create new accounts.
4. Review the newly-created user and see the email is still registered with the correct format of username@arizona.edu

Closes #4453 Disable email hostname on CAS bulk add user form.

---

modules/custom/az_paragraphs/az_paragraphs_splitscreen/az_paragraphs_splitscreen.install

Moves the splitscreen text width db update to a different function to reflect a change in release version. Leaves the original update function empty.
Closes #4364

Closes #4364 Update the splitscreen update functions for changed release version.

---

.lando.yml

**(2.x version)**
Removes hard-coded `dev-` prefix from `composer require` command used to install dev dependencies in Lando config.
Also updated build config to use YML multiline syntax to combine all the commands related to getting the correct scaffolding repo branch and correct dev package version into single, more readable lando "command"s which fixed problems we were seeing with variables set in earlier lando command steps not persisting to the next step.
This also changes the default branches used for the scaffolding repo (`2.x`) and dev repo (`1.x`) in this version so that builds based on the `2.x` branch of this repo are using the correct versions.
This bug was introduced in #4448 (mea culpa 🤦🏻‍♂️).
#4446 
Try using lando locally with this PR branch
- …

#4446: Fix broken .lando.yml file (follow-up to #4448) (2.x version).

---

modules/custom/az_paragraphs/az_paragraphs_photo_gallery/templates/carousel-gallery.html.twig
modules/custom/az_paragraphs/az_paragraphs_photo_gallery/templates/carousel.html.twig
modules/custom/az_paragraphs/az_paragraphs_photo_gallery/templates/grid-gallery.html.twig
modules/custom/az_paragraphs/az_paragraphs_photo_gallery/templates/paragraph--az-photo-gallery.html.twig
modules/custom/az_paragraphs/css/az_paragraphs_az_photo_gallery.css

…mpatibility. (#4226)
Co-authored-by: Joe Parsons <471936+joeparsons@users.noreply.github.com>

#4225 Upgrade Photo Gallery and Carousel Javascript components with Arizona Bootstrap 5 code.

---

modules/custom/az_media/config/install/core.entity_form_display.media.az_image.default.yml
modules/custom/az_media/config/install/core.entity_form_display.media.az_image.media_library.yml

Should fix invalid configs introduced due to faulty merge of #4538 into 2.13.x release branch:
ESlint errors:
```
/home/runner/work/az_quickstart/az_quickstart/modules/custom/az_media/config/install/core.entity_form_display.media.az_image.default.yml
66:6  error  Parsing error: Map keys must be unique
/home/runner/work/az_quickstart/az_quickstart/modules/custom/az_media/config/install/core.entity_form_display.media.az_image.media_library.yml
60:6  error  Parsing error: Map keys must be unique
```
drush site:install error:
```
In FileStorage.php line 118:
[Drupal\Core\Config\UnsupportedDataTypeConfigException]                      
Invalid data type in config core.entity_form_display.media.az_image.default  
, found in file profiles/custom/az_quickstart/modules/custom/az_media/confi …
```

#3657: Fix invalid config resulting from faulty merge of #4538 into 2.13.x

---

.github/workflows/ci.yml

This PR disables usage of `/dev/shm` for chromedriver in CI jobs. This is a potential fix for the recent issues we've seen with javascript-based tests failing.
#4518 
Check if javascript-based tests **consistently** pass in CI. (multiple runs)

Fixes #4518 Disable /dev/shm usage for chromedriver in CI

---

composer.json

(cherry picked from commit 61b6cee48e1615274c3859a3426625ebc1f28bcc)
Back-port of #4482 for 2.x.
Back-port of #4482 dependabot update.
https://7b5e2985-cedf-4a13-ab91-3a35916c835d--pr-4584.probo.build

Update drupal/media_library_form_element requirement from 2.1.1 to 2.1.2 (2.x back-port of #4482)

---

.github/workflows/ci.yml

(cherry picked from commit 49a3f1451f95e2c0dd69251330a2793fd9478776)
Backport of #4576 for 2.x
2.x backport of #4576 originally for #4518 

Fixes #4518 Disable /dev/shm usage for chromedriver in CI (2.x backport of #4576)

---

.github/workflows/prepare-for-minor-release.yml

2.x backport of #4593 for #4592

Closes #4592: Update prepare-for-minor-release workflow to support dynamic source branch. (2.x back-port of #4593)

---

themes/custom/az_barrio/templates/layout/page.html.twig

(cherry picked from commit b6805083be8507fb340925d967292703a789dd08)
2.x backport of #4580 for #4571

Closes #4571: VoiceOver Double Speak issue for accessibility tools. (2.x back-port of #4580)

---

modules/custom/az_paragraphs/az_paragraphs_photo_gallery/templates/paragraph--az-photo-gallery.html.twig
modules/custom/az_paragraphs/css/az_paragraphs_az_photo_gallery.css

Adds Bootstrap photo gallery carousel indicators.
Closes #1885
1. Install a new site with demo content and visit the Photo Galleries demo page.
2. Click on an image in the photo gallery grid format or look at a photo gallery slider.
3. See the carousel indicators at the bottom of the modal slider and click between them to see the slide change accordingly.
https://7b5e2985-cedf-4a13-ab91-3a35916c835d--pr-4474.probo.build/pages/photo-galleries
Note: Probo/local testing should be set to AZ Bootstrap stable CSS and JS to test. Grid won't work due to markup being already updated for BS5. Carousel testing should work ok. …

Closes #1885 Adds photo gallery carousel indicators (2.x version)

---

.github/workflows/prepare-for-minor-release.yml

First attempt using the updated workflow failed.
This should fix the validation failures we encountered.

Closes #4597: Fix validation logic in prepare-for-minor-release workflow.

---

.github/workflows/prepare-for-minor-release.yml

(cherry picked from commit 949ade645521254afc6061c7ead35d1bd03810fd)
2.x back-port of #4598 for #4597

Closes #4597: Fix validation logic in prepare-for-minor-release workflow. (2.x back-port of #4598)

---

.github/workflows/prepare-for-minor-release.yml

Fix more errors in `prepare-for-minor-release` workflow.

#4597: Fix more errors in prepare-for-minor-release workflow.

---

.github/workflows/prepare-for-minor-release.yml

#4597: Another fix for prepare-for-minor-release workflow (2.x)

---

.github/workflows/prepare-for-minor-release.yml

#4597: Another fix for prepare-for-minor-release workflow

---

.github/workflows/prepare-for-minor-release.yml

Applies additional fixes that were made directly to the `2.x` version of the `prepare-for-minor-release` workflow to the version in the `main` branch.
These changes were made directly to `2.x` to facilitate and expedite creation of the new `2.14.x` release branch and `2.14.0-alpha1` release.
#4597 

#4597: Update main branch version of prepare-for-minor-release workflow.

---

.github/workflows/pr-backport.yml

The [delete-branch option](https://github.com/marketplace/actions/create-pull-request#delete-branch) that was enabled for the action used to create PRs in the `pr-backport` workflow was not an option we actually want to use.
See https://github.com/az-digital/az_quickstart/actions/runs/16837403040/job/47700152535:
```
Branch 'backport-2.x/pr-4624' no longer differs from base branch '2.x'
Deleting branch 'backport-2.x/pr-4624'
/usr/bin/git push --delete --force origin refs/heads/backport-2.x/pr-4624
```
Followup to #4626 for #4537.

#4537: Remove delete-branch option from pr-backport workflow.

---

.github/workflows/pr-backport.yml

`pr-backport` workflow is still not working.
This replaces the usage of the `peter-evans/create-pull-request` GH action with GH CLI commands.  This is actually what the maintainer of that action recommends for situations like ours where we have already created a branch with commits:
https://github.com/peter-evans/create-pull-request/blob/main/docs/common-issues.md#create-using-an-existing-branch-as-the-pr-branch
Follow up to #4626 & #4628 for #4537.

#4537: Use GH CLI for PR creation in pr-backport workflow.

---

composer.json

(cherry picked from commit 0da08a871e2224f84f224ccb8e7627077c123379)
2.x backport of #4614 

Update drupal/linkit requirement from 7.0.7 to 7.0.8 (2.x back-port of #4614)

---

.github/workflows/arizona-bootstrap-release.yml

Updates existing workflow that automates creation of PRs for updating Arizona Bootstrap version when new Bootstrap releases are created to also support Arizona Bootstrap 5.x releases.
Closes #4618 
Hard to test without merging and creating another Arizona Bootstrap 5 release.

Closes #4618: Enable automated update PRs for Arizona Bootstrap 5.x releases.

---

modules/custom/az_finder/az_finder.module
themes/custom/az_barrio/templates/layout/html.html.twig

In this PR I am updating two instances in quickstart where we use the skip-link functionality.
1. is the main skip-link functionality found on every page.
2. is the skip-link functionality enable-able on the finder.
For the first one, I changed the link to use btn-dark and other bootstrap placement classes for an absolutely positioned button.
For the finder, I made set the button position to fixed in order to appear in the same place the other one does.
Uploading Screen Recording 2025-08-15 at 9.21.20 AM.mp4…
Close #4653 
On the front page hit the tab button. See text.
On the finder pages hit the tab button, skip to main content and click tab again.
- …

Close #4653 Replace visually-hidden focusable class with visually-hidden-focusable

---

modules/custom/az_flexible_page/config/install/core.entity_view_display.taxonomy_term.az_page_categories.az_badge.yml
modules/custom/az_person/config/install/core.entity_view_display.taxonomy_term.az_person_categories.az_badge.yml
modules/custom/az_person/config/install/core.entity_view_display.taxonomy_term.az_person_categories_secondary.az_badge.yml

Replace instances of `badge-light` with `text-bg-light`
See https://digital.arizona.edu/arizona-bootstrap/v5/docs/5.0/components/badge/
Closes #4697

Close #4697 Update taxonomy badge displays to use Arizona Bootstrap 5 classes

---

modules/custom/az_person/az_person_eds_import/az_person_eds_import.info.yml

Follow-up for #3472 and #4424:
az_person_eds_import module got merged before most of the D11 compatibility changes were made.
- #3471 
- #4167

#3471, #4167: Add D11 compatibility for az_person_eds_import.

---

modules/custom/az_news/az_news_export/src/Normalizer/AZNewsDataEmptyNormalizer.php

The `az_news_export` rest API uses a custom normalizer for stdclass objects to make them appear as empty objects. There was a change in Drupal 11 that altered how Normalizer services declare their support for an object: [Normalizers/Denormalizers should implement ::getSupportedTypes() instead of ::hasCacheableSupportsMethod() or using protected $supportedInterfaceOrClass](https://www.drupal.org/node/3359695)
This PR implements the new `getSupportedTypes()` for our normalizer.
Closes #4713 
- enable `az_news_export`
- visit path `/az_quickstart/export/az_news/v1/az_news.json`
- Verify the json feed displays without PHP errors
- **Other or …

Fixes #4713 az_news_export REST endpoint fails with NotNormalizableValueException

---

modules/custom/az_paragraphs/az_paragraphs_photo_gallery/templates/photo-gallery-carousel.html.twig

Changes the Material symbol for the "previous" button in Photo Gallery displays from arrow_back_ios to arrow_back_ios_new. This ensures that both the previous and next buttons use horizontally centered glyphs.
- #4727
Review site: https://ab040b26-03e8-4113-94a7-49908cbffc79.probo.build/pages/photo-galleries
Compare the review site with https://demo.quickstart.arizona.edu/pages/photo-galleries or another Probo site.

Closes #4727: Chevron in Photo Gallery previous button is misaligned

---

composer.json

Adds a patch to fix the embed media dialog box width.
Closes #4725
1. Log in and edit a page
2. Click the embed media icon
3. Observe the dialog box is as wide as on Drupal 10.x

Closes #4725 Add regression patch for embed media dialog boxes.

---

.github/workflows/prepare-for-minor-release.yml

Just looked over our `prepare-for-minor-release` workflow since we're almost ready to create `3.0.0-alpha1` and realized that the workflows validations steps will fail when asked to create the first minor release branch of a new major release.
"Fortune favors the bold"

Update prepare-for-minor-release workflow to support creating initial minor release branch for a major release (e.g. 3.0.x).

---

.github/workflows/prepare-for-minor-release.yml

Problem:
The original code used `wc -l` to count lines returned by `git ls-remote`, which can be unreliable because:
- Empty output from git ls-remote could still result in wc -l returning 1 in some cases
- The variable $NEW_VERSION wasn't quoted, which could cause parsing issues (the biggest problem?)
- Using command substitution with wc -l in a conditional is error-prone
Solution:
- Replaced it with `git ls-remote --exit-code`, which uses git's built-in exit codes: returns 0 if the branch exists, 2 if it doesn't
Is more reliable than counting lines
- Properly quoted the variable "$NEW_VERSION"
- Redirected output to null since we only care about the exit code
- Handled errors more gracefully with 2>&1
- …

More fixes/cleanup for prepre-for-minor-release workflow.

---

modules/custom/az_core/src/Utility/AZBootstrapMarkupConverter.php

Adds most of the old UA Bootstrap classes deprecated in Arizona Bootstrap 2 to the AZBootstrapMarkupConverter class mappings.
See https://github.com/az-digital/arizona-bootstrap/blob/2.x/scss/_deprecated.scss
Does not contain `panel-*`, `well-*`, `thumbnail` or `bg-` wrapper classes currently.
Closes #4748 

Closes #4748: Add mappings for UA Bootstrap classes deprecated in AZ Bootstrap 2 to AZBootstrapMarkupConverter.

---

modules/custom/az_core/css/arizona-bootstrap-node-form-overrides.css

New left padding was added to all list elements by reboot styling from Arizona Bootstrap 5. This PR is intended to remove unwanted instances of this left padding that users can encounter on node edit forms.
- #4730
https://7b5e2985-cedf-4a13-ab91-3a35916c835d--pr-4731.probo.build

Closes #4730: Undo Arizona Bootstrap 5 reboot list styling in node form elements

---

composer.json

https://www.drupal.org/project/drupal/releases/10.5.3
> This is a patch (bugfix) release of Drupal 10 and is ready for use on production sites. [Learn more about the latest version of Drupal](https://www.drupal.org/about/10).
> 
> Drupal 10.5.x will receive security support until June 2026. Drupal 10.4.x will continue to receive security support until December 2025.
> 
> Drupal 10.3.x security support has ended. Sites on any Drupal version prior to 10.4.x should upgrade to a supported release as soon as possible.
> 
> ### Important update information
> 
> - CKEditor5 is updated from v45.2.0 to v45.2.2 to fix a Cross-Site Scripting (XSS) vulnerability that does not directly effect Drupal core. If your site enables the [HTML embed …

Closes #4778: Update Drupal core to 10.5.3 (2.x branch)

---

.ddev/commands/web/install
.github/workflows/ci.yml
.lando.yml

Adds `--ignore-scripts` CLI option to `yarn install` command used in various CI / local dev configuration files
Should help to mitigate/minimize risks of NPM supply chain attacks which are becoming all to common lately.
https://classic.yarnpkg.com/lang/en/docs/cli/install/#toc-yarn-install-ignore-scripts
[Drupal.org PSA Re: recent supply chan attacks](https://www.drupal.org/psa-2025-09-17)
Ensure Quickstart builds still work local dev tools (Lando, DDEV) and CI (GitHub Actions).

Add --ignore-scripts option to yarn install commands in configs for CI and a local dev.

---

modules/custom/az_core/src/Drush/Commands/AZCoreConfigCommands.php

Fixes broken az-core-config-add-permissions Drush command.
Closes #4850

Closes #4850: Fix broken az-core-config-add-permissions Drush command.

---

modules/custom/az_media/az_media_trellis/az_media_trellis.libraries.yml
modules/custom/az_media/az_media_trellis/css/az-media-trellis.css
modules/custom/az_media/az_media_trellis/js/az-media-trellis.js
modules/custom/az_media/az_media_trellis/src/Plugin/Field/FieldFormatter/AzMediaRemoteTrellisFormatter.php
modules/custom/az_media/az_media_trellis/templates/az-media-trellis.html.twig

In this suggestion, I am commenting out much of the added styles as we want our forms to match university styles.
I also add some JS to remove all inline styles from the forms and any added CSS files from trellis.
I added some JS to remove the privacy link since most sites using QS already have that link.
I added some JS to add the arizona bootstrap spinner for when the form is loading.
I am not really sure what those empty text areas are that are added  now that I strip the styles.

Issue #3660 more suggestions.

---

modules/custom/az_core/css/claro-node-form-overrides.css

Unsets `.form-select` width in Claro from AZ Bootstrap styling.
Closes #4811
Edit a page and check that select dropdowns in paragraphs are not full width.

Closes #4811 Unset width on Claro form-select

---

modules/custom/az_core/src/AZContentFieldUpdater.php

Replaces hard-coded `paragraph` reference in some AZContentFieldUpdater log messages with actual entity type ID.
Closes #4887
- Run database updates on Quickstart 2.14.x site containing az_course, az_event, az_news, or az_publication content with legacy Bootstrap classes in a CKEditor field.
- Ensure no messages are logged that describe updated az_course, az_event, az_news, or az_publication content entities as paragraphs.

Closes #4887: Fix incorrect entity type used in some AZContentFieldUpdater log messages.

---

themes/custom/az_barrio/az_barrio.libraries.yml

Updates deprecation messages for deprecated az_barrio libraries that haven't actually been removed yet as of 3.0.x:
- `az_barrio/arizona-bootstrap`
- `az_barrio/material-design-icons-sharp`
```
TODO
```
Closes #4889
- Install Quickstart
- Look for deprecation messages in system status report

Closes #4889: Update az_barrio library deprecation messages.
