az-digital/az_quickstart

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md

We may want to modify these and/or add additional issue templates in the future (e.g. "User Story") but I think it'd be good to just add these as a starting point.

Add default issue templates

---

composer.json

Closes #24 by updating drupal/core-recommended to 8.8.2 in composer.json.

Closes #24 Update Drupal core-recommended version to 8.8.2 in composer.json

---

modules/custom/az_core/src/Form/QuickstartCoreSettingsForm.php

Don't use operators that convert type unless absolutely needed
PHP likes to do some weird type conversions with `==`, `!=`, and `<>`. These can be dangerous so we shouldn't use these operators unless there's a good justification and some additional verification going on. See the example below:
```
php > var_dump('0 cats' != 0);
bool(false)
php > var_dump('0 cats' !== 0);
bool(true)
```
https://www.netsparker.com/blog/web-security/type-juggling-authentication-bypass-cms-made-simple/
https://github.com/FloeDesignTechnologies/phpcs-security-audit/pull/53

closes #28 - use !== instead of !=

---

composer.json

This should resolve the remaining deprecation notices generated by the Display Suite module.  This pins Display Suite to the dev revision associated with the most recent recommended release (8.x-3.5) because the composer patches plugin was only able to apply the existing patch using `git apply` (because the patch includes binary file changes) and, at least using the latest release of composer-patches, the only way to enforce that `git apply` is used was to change Display Suite to  use a dev version.
#39, #45 
Tested locally with lando.

#45: Workaround for Display Suite deprecation notices.

---

composer.json

updates composer.json to "drupal/bootstrap_barrio": "4.23" and removes `missing theme config schema` patch.
Steps I took:
- lando composer require 'drupal/bootstrap_barrio:^4.23'
- manually deleted the patch from composer.json
- lando rebuild, install, start
- ensured all looked as expected (including under admin/appearance)
- confirmed the contents from [the patch](https://www.drupal.org/files/issues/2018-12-16/missing-config-schema-3017668-6.patch) are included in [this new version](https://git.drupalcode.org/project/bootstrap_barrio/-/blob/8.x-4.x/config/schema/bootstrap_barrio.schema.yml)

Closes #67 by updating barrio to 8.x-4.23 & remove patch

---

.github/CODEOWNERS
.github/pull_request_template.md

unfortunately github doesn't allow a default project for a pull request template
https://github.com/az-digital/az_quickstart/issues/75

Add default PR reviewers, remind to add project -- closes #75

---

config/install/block.block.az_barrio_main_menu.yml

This pull request adds a configuration entity for the placement of the main menu block in the barrio theme. The present default depth values for the block do not allow for dropdowns to be rendered, as they are of a depth that is trimmed from the markup by the default depth value.
This adds YAML configuration for the main menu block that contains the default values with the exception of updating **Number of levels to display** from 1 to 2. This allows dropdowns for the main menu nav to actually appear in the markup.
#167 
Tested locally by visiting `/admin/structure/block/manage/az_barrio_main_menu` after installation.

Fixes #167 Add default configuration for main menu block

---

modules/custom/az_cas/az_cas.links.task.yml
modules/custom/az_cas/az_cas.routing.yml
modules/custom/az_cas/az_cas.services.yml
modules/custom/az_cas/config/install/az_cas.settings.yml
modules/custom/az_cas/config/schema/az_cas.schema.yml
modules/custom/az_cas/src/Form/AzCasSettingsForm.php
modules/custom/az_cas/src/Subscriber/PreventPasswordResetSubscriber.php
modules/custom/az_cas/tests/src/Functional/AzCasAdminSettingsTest.php
modules/custom/az_core/az_core.links.task.yml

- Adds custom az_cas module setting for disabling user password reset link/form/route provided by core
- Adds AZ CAS settings form (attached to AZ Core settings form as local task/tab)
- Adds RouteSubscriber class/service to alter core `user.pass` route when custom setting is enabled
- Adds AzCasAdminSettings functional test for testing custom setting
- Fixes existing `Quickstart Core` local task (tab) to be displayed in the correct location
#160 
Tested locally using lando.

Fixes #160: Added custom az_cas setting for disabling password reset form.

---

themes/custom/az_barrio/config/install/az_barrio.settings.yml

A variable in the `az_barrio` settings that is intended for boolean usage was currently set to a string value, causing some Form API issues.
A configuration setting for `bootstrap_barrio_navbar_container` is intended for boolean usage as the value of a checkbox, but is currently set to a default value of `'navbar-toggleable-md'`. This gets evaluated as true, but causes the Form API to discard that value the first time the theme settings form is saved, which breaks the site menu.
#170 
Ensure that after site installation, the theme setting for `Components > Navbar > Navbar width container` is checked.
Configuration updates.

Fixes #170 Provide appropriate value for Navbar width container configuration.

---

.probo.yaml
config/install/user.role.az_content_admin.yml
modules/custom/az_core/az_core.permissions.yml
modules/custom/az_core/az_core.routing.yml
modules/custom/az_core/tests/src/Functional/ClearCacheTest.php
modules/custom/az_core/tests/src/Functional/MonitoringPageTest.php

- Adds `administer quickstart configuration` permission to az_core
- Adds `administer quickstart configuration` to default permissions for `az_content_admin` role
- Updates existing az_core routes to use new permission
- Updates existing az_core tests to use new permission
- Adds ProboCI step to create test users with custom roles
#162 #159 
Tested locally with lando:
- composer install
- phpcs
- drupal-check
- phpunit
- manual functional testing

Fixes #162, Fixes #159: Added permission for administering Quickstart settings & added additional test users to ProboCI sites.

---

composer.json

This morning the composer build process of the profile broke due to the dev version of display suite having been updated to a version that includes a patch we were previously using and the patch consequently failing. Due to the commit referencing feature of composer being fairly bug prone, it's no longer requesting our specified commit hash. I've attempted to fix this by removing the patch in question and updating to a commit hash that included it.
#179 
Locally. Review of display suite components is needed as this brings in several new display suite commits.

Fixes #179 Update DS commit hash

---

themes/custom/az_barrio/config/install/az_barrio.settings.yml
themes/custom/az_barrio/templates/page.html.twig

This pull request resolves the duplicate messages that are presently being rendered by `az_barrio`.
The twig template that az_barrio renders its blocks from has apparently always been double rendering the messages, but due to the functionality where messages were displayed via JS in the screen corner as toasts, this issue was being masked. It's not necessary to print the messages in the subtheme as they're rendered in the surrounding markup of the parent theme: 
```
{% if page.highlighted %}
<div class="highlighted">
<aside class="{{ container }} section clearfix" role="complementary">
{{ page.highlighted }}
</aside>
</div>
{% endif %}
```
This isn't readily overridden in the subtheme as this takes place 'between' the blocks that the subtheme is responsible for rendering due to barrio's …

Fixes #171 Resolve Duplicate Drupal Messages

---

themes/custom/az_barrio/az_barrio.theme
themes/custom/az_barrio/includes/common.inc

The following PR updates the URL being used for fetching the CDN resources for az barrio.
The helper function `az_barrio_az_bootstrap_assets_path` has been updated to point to the correct link. 
References to loaded css assets from the previous cdn will still be seen in browser network activity, but this appears to be due to loading of milo from the old cdn. Bootstrap itself should be coming from the new cdn.
#183
locally. Turn off CSS aggregation, and then verify that the CSS files being loaded are coming from [https://cdn.digital.arizona.edu/lib/arizona-bootstrap/](https://cdn.digital.arizona.edu/lib/arizona-bootstrap/)

Fixes #183 Update CDN Link to Github-based CDN

---

.github/workflows/create-upload-release.yml

This update will build az_quickstart using az-quickstart-scaffolding, create zip and tar archives, create a github release based on the incoming tag, then push the archives to the release.
Closes #185
Tags have been created and assets get successfully built and pushed to github

Build assets and publish to github release

---

az_quickstart.info.yml
composer.json
config/install/block.block.az_utility_links.yml
config/install/system.menu.az-utility-links.yml
modules/custom/az_demo/az_demo.info.yml
modules/custom/az_demo/az_demo.install
modules/custom/az_demo/az_demo.module
modules/custom/az_demo/data/az_demo_menu_links.json
modules/custom/az_demo/migrations/az_demo_menu_links.yml
modules/custom/az_demo/tests/src/Functional/AZDemoContentTest.php
themes/custom/az_barrio/templates/navigation/menu--az-utility-links.html.twig

This pull request adds a utility links menu and block placement to the configuration for quickstart.
`az_utility_links` is added as a menu block, and the block is placed above the search box in the `Header 1` region. A template is added to handle the addition of necessary bootstrap 4 classes.
This PR also adds a basic `az_demo` module that imports demo content. This could be fleshed out further when we start in earnest on our demo content epic.
#172 #195 
Locally.

#172 Add Utility Links Menu and Block.

---

composer.json

Adds [drupal.org patch](https://www.drupal.org/project/cas/issues/3138426#comment-13626352) for CAS module deprecation warning that is currently breaking our Probo builds.
#205 
Locally with lando. Patch being used passed Drupal.org tests

Fixes #205: Apply patch for CAS module deprecation warning.

---

themes/custom/az_barrio/templates/navigation/menu--main.html.twig

The current markup of the main navigation doesn't presently allow the proper Bootstrap classes to apply on the downdown menu items. @akslay found out that this is because the `.dropdown-item` class is currently present on the `li` element of the menu markup rather than on the link where bootstrap expects it to be.
This PR adds a twig template for the menu that moves the `.dropdown-item` class from the `li` element to the `a` element.
#230
- Create a nested menu.
- Verify that links are white rather than red and underlined.

#230 Move .dropdown-item class from list element to anchor element

---

themes/custom/az_barrio/templates/navigation/menu--az-utility-links.html.twig

Closes #228 by adding the `.nav-utility` class to the utility links menu. These styles are available in Bootstrap az-digital/arizona-bootstrap#81 (pending merge to master).

Closes #228 - Add .nav-utility class

---

.ddev/commands/web/phpcs
.ddev/commands/web/phpunit
.github/workflows/security.yml
.lando.yml
composer.json
phpcs.xml.dist

This moves various things related to our require-dev dependencies from the scaffolding repo to the profile repo:
- phpcs.xml.dist config
- Github actions security check workflow
It also adds a new repo, az-quickstart-dev as a require-dev dependency.
#33 
- Locally with lando
- On GitHub actions

#33: Moved require-dev dependencies out of scaffolding repo (profile repo PR)

---

composer.json

This pull request provides a fix for an issue where the necessary attributes for quickedit to work were missing for layout builder blocks.
This pull request fixes #243 by adding a patch that causes the necessary expected attributes for quickedit integration to be rendered for layout builder blocks. This prevents the javascript error being thrown in #243 .
#243 
Create blocks in layout builder, save the content, edit the layout again, and verify that your blocks have "quickedit" in their contextual links menu.

Fixes #243 by adding patch to properly render quickedit attributes.

---

modules/custom/az_layouts/src/Element/AZLayoutBuilder.php

This pull request prevents a potential ContextException that could occur when editing the default layout for a content type.
There are some checks in place to verify that some customizations are only applied if the content type of the page is a flexible page. To do this, a check is made regarding the section's entity context. However, this could fail in cases where there was no entity context. (Typically when editing the default layout for a content type).
A potential `ContextException` is caught to resolve the issue.
#249 
Visit: `/admin/structure/types/manage/az_flexible_page/display/default/layout` and verify no error is encountered.

Fixes #249 Manage Layout Button Doesn't Work

---

composer.json
modules/custom/az_layouts/az_layouts.info.yml

Adds media_library_theme_reset module as fix for #241 
#241
Fix verified on ProboCI site.

Fixes #241: Added media_library_theme_reset contrib module to fix Layout Builder Media Library display issues.

---

modules/custom/az_cas/config/install/cas.settings.yml

This change corrects the format of the token that is replaced by the logged in user's account name.
Logged in with CAS, now I see my username
change %cas_username to [cas:username]

Fix [cas:username] token

---

az_quickstart.info.yml
composer.json
config/install/easy_breadcrumb.settings.yml
config/install/user.role.az_content_admin.yml
themes/custom/az_barrio/templates/navigation/breadcrumb.html.twig

This pull request adds breadcrumb settings to `az_quickstart` that mimic the settings that were in place in `ua_zen` @joshuasosa suggested in the original ticket that this could be done using the contrib `easy_breadcrumb` module which is the approach taken in this PR.
This PR adds the `easy_breadcrumb` module, incorporates it into the install profile, provides default settings for it, and also provides a template override for the barrio breadcrumbs to apply the necessary aria labels, some of which weren't present in the original barrio theme.
By default, the **Home** breadcrumb entry isn't shown, and the "leaf" current breadcrumb showing the page isn't shown, as it's right next to the page title. If the leaf breadcrumb is enabled later, it has the proper aria property.
#194 
Create nested …

Fixes #194 Add Breadcrumb Settings

---

.ddev/commands/web/install
.ddev/config.quickstart.yaml

- ~Moves compser and yarn script steps out of custom ddev `install` command into ddev `post-start` hook~
- ~Replaces step that git clones scaffolding repo with git init, git fetch, and git checkout commands due to weirdness with `/var/www/html` directory already existing~
- Replaces existing command to remove files in the `/var/www/html` directory with `rm -rf /var/www/html/*` to fix problems with latest ddev release
- Bumps PHP + MariaDB versions in ddev config to improve D9 compatibility (while preserving backwards compatibility)
#247 
Locally with ddev version 1.15.0

Fixes #247: Improve compatibility with latest ddev release + backwards-compatible D9 ddev config changes.

---

phpstan.neon

Whitelists additional deprecation warning/error patterns getting flagged by phpstan for modules recently added in #281 and #324. 
#310

Fixes #310: Ignore certain deprecation warnings originating from recently-added contrib modules.

---

.github/dependabot.yml

This PR adds a config file for github dependabot.
Adding this dependabot config will generate a PR every Monday if there are available updates for our dependencies. We should still get the dependabot security update PRs as they become available.
For more info, see https://docs.github.com/en/github/administering-a-repository/enabling-and-disabling-version-updates

Add weekly dependabot checks for new packages

---

.ddev/commands/web/drupal-check
.ddev/commands/web/phpstan
.ddev/commands/web/phpstan-contrib
.gitattributes
.lando.yml
.probo.yaml
modules/custom/az_core/az_core.module
modules/custom/az_core/src/QuickstartConfigInstaller.php
phpstan-contrib.neon
phpstan.neon
themes/custom/az_barrio/theme-settings.php

- Fixes #336 
- Removes drupal-check tooling
- Moves old `phpstan.neon` config to `phpstan-contrib.neon`
- Adds new `phpstan.neon` config for testing custom code
- Addresses various existing code quality check issues
#336
Locally with lando
-  Replace `drupal-check` dependency in `az-quickstart-dev` metapackage with `phpstan-drupal`.

Fixes #336: Resolve new deprecation errors + various PHP code quality checks improvements

---

composer.json

- Updates Drupal core to version 9.0.7
- Adds @akslay's core patch which better documents core's accessible nolink menu option (https://www.drupal.org/project/drupal/issues/3153394)
#344 
Locally with Lando

Closes #344: Update Drupal core to version 9.0.7 (bugfix release) and add akslay's core patch.

---

composer.json

https://www.drupal.org/sa-core-2020-012
#381

#381: Updated Drupal core to version 9.0.8 for SA-CORE-2020-012 (critical security vulnerability).

---

composer.json

Change `dev-main` alias to reference 2.1.x instead of 2.x

Updated main branch alias to be 2.1.x

---

composer.json

https://www.drupal.org/sa-core-2020-013
#391

#391: Updated Drupal core to version 9.0.9 (critical security update for SA-CORE-2020-013).

---

.github/workflows/security.yml

Noticed that our GitHub actions were failing for `2.0.x` branch commits.  Replaced references to `main` branch in GitHub actions config with `2.0.x`.
#393

Fixes #393: Replaced hard-coded references to main branch in GitHub actions config.

---

modules/custom/az_paragraphs/az_paragraphs.libraries.yml
modules/custom/az_paragraphs/css/az_paragraphs_preview.css
modules/custom/az_paragraphs/src/Plugin/paragraphs/Behavior/AZDefaultParagraphsBehavior.php

This PR adds some preview-mode specific paragraph styles proposed by @danahertzberg  to make it easier to reorder collapsed paragraphs.
This PR adds some CSS for paragraph preview modes that enforces a height limit on paragraph previews proposed by @danahertzberg - the intent is that long previews are truncated in height so they can still be reordered easily.
To accomplish this, the PR also adds an extension to our existing library system. We previously had in place functionality that could load paragraph-specific libraries; that functionality has been expanded to allow for view-mode specific libraries and per-bundle-view-mode-specific libraries. The system is put into use to load a CSS library for paragraph previews.
This customization is to paragraph preview modes only, and does not …

Fixes #386: Update Paragraph Preview Styles

---

.lando.yml

Remove hirak/prestissimo from .lando file since it is now outdated with composer2
According to the official documentation on this page
https://github.com/hirak/prestissimo
We should no longer be using it.
Closes #405

remove hirak/prestissimo

---

.github/PULL_REQUEST_TEMPLATE/pull_request_template.md

This pull request adds a checkbox to track whether or not someones pull request is going to add configuration changes to Quickstart.
I added a line to the "Types of Changes" section: 
Closes Task/419
Minor documentation change

Updating the PR template to add a configuration checkbox

---

themes/custom/az_barrio/css/style.css

Remove vestigial references to the Milo font family in az_barrio theme stylesheets
Closes #422

Remove all references to Milo font.

---

RELEASES.md

This release policy has been put together through multiple Arizona Digital workshops and the purpose of this PR is to add that Release Policy to the codebase so that it can be easily found by anyone using Quickstart and can be managed by Version Control.
The Release Policy lays out how we will manage minor and patch releases for Quickstart 2.0 including which types of changes would be included in each type of release and what the expected timelines for releasing them would be. 
Issue #141

Adding release policy to quickstart

---

modules/custom/az_event/az_event.module

This PR fixes the display of event pseudo fields, which currently aren't displaying in `bug/471`.
During refactoring of field config, the calendar output of event month and day via pseudo field seems to have stopped working.
#494 
Create an event and verify the side box day and month are displaying on `/calendar`

Fixes #494 Fix Event Pseudo Fields

---

composer.json

Adds [`sort-package: true`](https://getcomposer.org/doc/06-config.md#sort-packages) to the composer config, and also sorts the existing packages so the next `composer require` will have a clean diff.
Closes #462 by adding sort-packages setting to composer config and sorting the existing packages.
#462 
I tested that the new config is working by first adding it via `composer config sort-packages true`, then requiring an existing package via `composer require drupal/cas` to trigger the sort. I verified that the dependencies were all still there, just in alphabetical order.

Make composer sort packages alphabetically.

---

modules/custom/az_core/config/install/field.storage.node.field_az_caption.yml
modules/custom/az_core/config/install/field.storage.node.field_az_subheading.yml
modules/custom/az_core/config/install/field.storage.node.field_az_summary.yml
modules/custom/az_event/config/install/core.entity_form_display.node.az_event.default.yml
modules/custom/az_event/config/install/core.entity_view_display.node.az_event.az_row.yml
modules/custom/az_event/config/install/core.entity_view_display.node.az_event.default.yml
modules/custom/az_event/config/install/core.entity_view_display.node.az_event.teaser.yml
modules/custom/az_event/config/install/field.field.node.az_event.field_az_subheading.yml
modules/custom/az_event/config/install/field.field.node.az_event.field_az_summary.yml
modules/custom/az_news/config/install/core.entity_form_display.node.az_news.default.yml
modules/custom/az_news/config/install/core.entity_view_display.node.az_news.az_media_list.yml
modules/custom/az_news/config/install/core.entity_view_display.node.az_news.default.yml
modules/custom/az_news/config/install/core.entity_view_display.node.az_news.teaser.yml
modules/custom/az_news/config/install/field.field.node.az_news.field_az_caption.yml
modules/custom/az_news/config/install/field.field.node.az_news.field_az_subheading.yml
modules/custom/az_news/config/install/field.field.node.az_news.field_az_summary.yml

This pull request changes some identified fields from plain text to formatted text with the plain text format. This was decided in order to future proof those fields if it ever becomes allowed to use text formats with them.
The following fields are changed:
- `field_az_subheading` from text_plain to formatted (but not long, still rendered as plain for now )
- `field_az_summary` change to text (formatted, long) (rendered as plain text)
- `field_az_caption` change to (formatted, long) (rendered as plain text)
#490 
Determine that summary, subheading and caption are now formatted text fields with the plain text format set.
Verify that events and news are still displaying as expected, in each of their view modes (full node, view displays, etc.)

Fixes #490 Makes plain text fields formatted text with plain text

---

composer.json
themes/custom/az_barrio/includes/common.inc

As part of creating the official Quickstart pre-release, we decided we also needed to incorporate the latest Arizona Bootstrap changes.

Updated Arizona Bootstrap to version 2.0.6.

---

composer.json

This patch alters the menu editing experience in a way more in line with what a user expects. Once a menu link is added, the user is then returned to that menu's editing page.
#502 
Built and tested locally with Lando.

Add patch for menu editing experience

---

modules/custom/az_paragraphs/config/optional/editor.editor.az_standard.yml

The "paste from Word" option in CKEditor does not work with modern browsers, so this PR removes the button from the az_standard text format.
#491 
Built and tested locally with Lando.

#491: Remove paste from word ckeditor option

---

.github/workflows/security.yml

Replaces deprecated sensiolabs/security-checker script with symfonycorp GH action.
#504 
Needs to be tested on GH actions.

#504: Replaced sensiolabs/security-checker script with symfonycorp/security-checker-action.

---

themes/custom/az_barrio/az_barrio.info.yml
themes/custom/az_barrio/az_barrio.theme
themes/custom/az_barrio/css/style.css
themes/custom/az_barrio/theme-settings.php

Made the use default logo checkbox functional.
Made footer logo fields conditional to the default logo checkbox
Made footer logo fields for alt, title, destination required if using a custom logo.
Added styles to footer logo to comply with brand guidelines
Closes #473
Closes #497 
1. build site and see if the default logo looks appropriate.
2. in the footer logo area of the theme check the "use default logo" checkbox and see if the footer logo uses the default logo and is formatted correctly and check the inspector console for image mixed media errors
3. add a new SVG footer logo and SVG header logo and check if the two logos are different and styled appropriately and check the inspector console for image mixed media errors.
4. check the boxes to inline the svg logos and check that the …

Issue/473 Fix logo styling and update logo path to use relative url.

---

modules/custom/az_paragraphs/az_paragraphs.libraries.yml
modules/custom/az_paragraphs/az_paragraphs_html/config/install/paragraphs.paragraphs_type.az_html.yml

Resolves #365
Updated the az_paragraphs configurations so that Jquery is loaded earlier in the DOM.
Thanks for a fellow developer at the Library (shout out to Ruiqi Yu!), who spoon fed me the solution, I committed the solution for this after wrapping my brain around it. Added a configuration to the az_paragraphs.libraries.yml file for az_html. That configuration adds core/jquery as a dependency for az_paragraphs_html. Then  enabled az_default_paragraph_behavior in the install config for az_html so that the library would get attached. This resolves #365 
Bug #365 
I tested this by first enabling az_paragraphs_html. I then created a new page and added an HTML paragraph type to the page and inserted some JQuery into the HTML field. Before the fix the Jquery would not work, but after the code …

Bug/365 Fix how Jquery is loaded with HTML Paragraph

---

.ddev/config.quickstart.yaml
.github/workflows/create-release.yml
.github/workflows/security.yml
.lando.yml
.probo.yaml
composer.json
modules/custom/az_core/az_core.module
phpcs.xml.dist

Changes PHP version for all of our local dev / CI tools to PHP 7.4.  Also addresses a PHP 7.4 compatibility issue in Config Distro and enables PHPCompatibility coding standard in our PHP CodeSniffer configuration.
#350 
Locally with Lando
- Scaffolding repo PR: az-digital/az-quickstart-scaffolding#39
- Pantheon upstream repo PR: az-digital/az-quickstart-pantheon#5

#350: Updated PHP versions to 7.4.  Added PHPCompatibility coding standard to PHPCS config.

---

themes/custom/az_barrio/templates/page.html.twig

Removes extra instance of `page.footer_sub` from AZ Barrio's `page.html.twig` template.
#532

Closes #532: Removed extra instance of footer_sub region in AZ Barrio's page template.

---

themes/custom/az_barrio/az_barrio.libraries.yml

Fixed incorrect Arizona Bootstrap JS library path in `az_barrio.libraries.yml`.
Thanks @akslay for reporting!
#530

Closes #530: Fixed Arizona Bootstrap JS library path.

---

modules/custom/az_news/az_news.info.yml
modules/custom/az_news/config/install/core.entity_view_display.node.az_news.az_card.yml
modules/custom/az_news/config/install/views.view.az_news.yml
modules/custom/az_paragraphs/az_paragraphs_view/config/install/field.field.paragraph.az_view_reference.field_az_view_reference.yml

This PR covers the previous 3 card and 6 card teaser displays for News
Updates
- Renamed the display to "Grid View"
- Add functionality to the Views paragraph that allows content editors to specify the limit number (by default will be 3 if left blank)
- Updated the design
- Updated the Read All News button to point to /news
https://github.com/az-digital/az_quickstart/issues/550
https://github.com/az-digital/az_quickstart/issues/551
Tested locally
To test:
1. Create at least four news items
2. Create a page
3. Add a view Paragraph and then choose AZ News and the Grid View display
4. Specify the limit as something larger than 3 
5. Save your page and make sure items appear appropriately (display 3 items in date order)
If you really want to get fancy, create more news items, add tags, and …

Adding grid view for News (formerly "Teaser Block") Closes #550 #551

---

.github/workflows/security.yml

Should fix #393 (GitHub actions security workflow is currently failing on 2.0.x branch).  This PR targets the 2.0.x branch directly.
#393 
Has not been tested.  Need to see if it works on GitHub actions.

Closes #393: Use quickstart_branch script to require correct branch/version of Quickstart in GitHub actions security workflow.

---

themes/custom/az_barrio/templates/navigation/menu--main.html.twig

While reviewing az-digital/arizona-bootstrap#240 with @danahertzberg we decided that the `.nav` class that is added to the main menu by Arizona Barrio is problematic and not needed.
az-digital/arizona-bootstrap#223
In browser inspectors (a little).

az-digital/arizona-bootsrap#223: Removing unnecessary .nav class from main menu template.

---

composer.json

While reviewing #598, I noticed that content containing blockquote elements with an existing class attribute triggers [this bug](https://www.drupal.org/project/bootstrap_utilities/issues/3204191) in the bootstrap_utilities module which causes PHP warnings to get logged in the watchdog log when the content is rendered.
This PR is against @barrettbaffert's existing PR (#598) branch and adds a patch from Drupal.org to fix the bootsrap_utilities bug.
#401 

Added patch for BlockquoteFilter issue.

---

composer.json

Closes #601 by patching a bug that prevents you from selecting a single View Display or "all" View Displays when configuring a view.
Closes #535 
- https://github.com/az-digital/az_quickstart/issues/601
- https://www.drupal.org/project/drupal/issues/2552541
- https://www.drupal.org/files/issues/2020-11-03/2552541-43.patch
- Added & active on the Registrar website. 
- Tested on a local build.
[ x ] Bug fix (non-breaking change which fixes an issue)
[ ] New feature (non-breaking change which adds functionality)
[ ] Breaking change (fix or feature that would cause existing functionality to change)
[ x ] I've added this Pull Request to the AZ Quickstart Github project and set it to "Review in progress".
[ x ] My code follows the code style of this project.
[ ] My change requires a change to …

Closes #601 - Add patch 2552541-43 to core/views

---

modules/custom/az_core/az_core.module

Fixes incorrect render array for Quickstart version indicator toolbar item which is causing watchdog errors.
#599 

Fixes #599: Fix broken Quickstart version indicator render array.

---

modules/custom/az_paragraphs/config/optional/embed.button.az_embed_content.yml

Updates existing configuration for the content embed button. Adds in Event, News, and Person content types as options. Adds in Card and Media List view modes as options.
**Review site:** https://7b5e2985-cedf-4a13-ab91-3a35916c835d--pr-609.probo.build/
Closes #541.
Tested locally.

Fixes #541: Update config settings for embed content

---

modules/custom/az_paragraphs/az_paragraphs_view/az_paragraphs_view.info.yml
modules/custom/az_paragraphs/az_paragraphs_view/config/install/core.entity_form_display.paragraph.az_view_reference.default.yml
modules/custom/az_paragraphs/az_paragraphs_view/config/install/core.entity_view_display.paragraph.az_view_reference.default.yml
modules/custom/az_paragraphs/az_paragraphs_view/config/install/field.field.paragraph.az_view_reference.field_az_title.yml
modules/custom/az_paragraphs/az_paragraphs_view/config/install/field.field.paragraph.az_view_reference.field_az_view_reference.yml
modules/custom/az_person/config/install/views.view.az_person.yml

This a re-evaluation of how we handle contextual filters on the AZ Person views.
**New goal:** Make person views more user friendly to how people are already using views by providing expected outcomes when adding the view paragraph type.
- Expected outcome without any filters is to display all people in alphabetical order
- Expected outcome with a filter is to display only people associated with that filter
- Current experience without filters is display all people by category
- Current experience with filters requires second contextual filter to show only that filter
- If someone wants one page with people in category order, they can add multiple views
- Implementing second filter on D9 cannot be done in the same way as D7 because relationships are not available for selection by the …

Fixes #407: AZ Person view contextual filter updates

---

modules/custom/az_card/az_card.services.yml
modules/custom/az_card/css/az-card-widget.css
modules/custom/az_card/src/AZCardImageHelper.php
modules/custom/az_card/src/Plugin/Field/FieldFormatter/AZCardDefaultFormatter.php
modules/custom/az_card/src/Plugin/Field/FieldWidget/AZCardWidget.php

This pull request updates many aspects of the card widget of our custom card field, primarily the introduction of card previews and two-step editor forms so that the entire deck does not open at once.
The following changes are made to the card type and card widgets:
- Storage of the media ID is sanitized so that it may be NULL
- Corrected issue where the media widget was providing a comma delimited list of Media IDs
- Card field forms are now a two-step AJAX process where an `Edit Card` button is pressed to edit an individual card, as opposed to all field inputs showing simultaneously.
- Card background color selection
- Card background color implementation
- On the edit screen, a rendered preview is provided for collapsed cards.
#538 
#427 
#390 
#613 
#377 
- Create a page
- Add cards
- …

Fixes #390, Fixes #427, Fixes #538, Fixes #613 Card Widget Updates

---

az_quickstart.info.yml
composer.json
config/install/user.role.az_content_admin.yml
config/install/user.role.az_content_editor.yml

This PR is based on permissions work by myself and @danahertzberg during the 3/31 workshop.
When we added the flexible block, permissions were not set for content admins and content editors. This ticket address that:
- Added block_content_permissions contrib module to be able to set the permissions
- Set permissions so that content admins can create/delete flexible blocks
- Set permissions so that content admins can place flexible blocks in regions
- Set permissions so that content editors can edit existing blocks
Note: We did not give content editors the Administer Block role (although they do have it in QS1). We also did not set permissions for the basic block.
#627 
Tested locally and in Probo.
How to test:
- Sign in and azcontentadmin
- Create a flexible block (Structure, Block …

Setting permissions for flexible block

---

modules/custom/az_accordion/src/Plugin/Field/FieldFormatter/AZAccordionDefaultFormatter.php
modules/custom/az_paragraphs/src/Plugin/paragraphs/Behavior/AZDefaultParagraphsBehavior.php

Updates the following classes to use new agreed upon DI structure for child classes:
- Drupal\az_accordion\Plugin\Field\FieldFormatter\AZAccordionDefaultFormatter
- Drupal\az_paragraphs\Plugin\paragraphs\Behavior\AZDefaultParagraphsBehavior
The following class is being updated in #634 by @tadean:
- Drupal\az_card\Plugin\Field\FieldFormatter\AZCardDefaultFormatter
#632 
Locally with lando

#632: Change composition of child classes needing additional dependencies for better maintainability.

---

.github/workflows/arizona-bootstrap-release.yml

This PR fixes two issues:
1. The `gh` tool needs to be authenticated before it can create a PR
2. `jq` needs to be explicitly told to use 4 spaces for indentation

Fix bootstrap release PR action issues

---

composer.json

This PR attempts to provide a workaround for a current bug in the `config_sync`/`config_distro` ecosystem. The symptom of this problem is that when distribution updates are imported, any modules that are deselected (eg. you choose not to import their updates) still import anyway.
This PR provides a patch that hooks the storage comparer used in the Config Import process up between the site's sync storage and active storage. 
Normally `config_distro`'s import form integrates with the sync storage indirectly, through the new transformation API. The `config_sync`/`config_distro` ecosystem has been trying to move towards using the transformation API but it appears that perhaps something in the `config_filter` layer is being cached or not regenerated during a plugin derivation process.
This …

Fixes #428 Config Distro Import Ignore Bug

---

themes/custom/az_barrio/css/style.css

On the Drupal side, the offcanvas nav wasn't scrolling due to the extra markup Drupal generates when rendering the menu. This fix adds a line of CSS to the styles.css file to address the issue.
Review link: https://7b5e2985-cedf-4a13-ab91-3a35916c835d--pr-655.probo.build/
Closes #615
Tested locally

Closes #615 - Fix offcanvas menu scroll

---

az_quickstart.info.yml
modules/custom/az_media/config/install/core.entity_form_display.media.az_image.default.yml
modules/custom/az_media/config/install/core.entity_form_display.media.az_image.media_library.yml
modules/custom/az_media/config/install/core.entity_view_display.media.az_image.az_background.yml
modules/custom/az_media/config/install/core.entity_view_display.media.az_image.az_card_image.yml
modules/custom/az_media/config/install/core.entity_view_display.media.az_image.az_carousel_item.yml
modules/custom/az_media/config/install/core.entity_view_display.media.az_image.az_large.yml
modules/custom/az_media/config/install/core.entity_view_display.media.az_image.az_medium.yml
modules/custom/az_media/config/install/core.entity_view_display.media.az_image.az_natural_size.yml
modules/custom/az_media/config/install/core.entity_view_display.media.az_image.az_thumbnail.yml
modules/custom/az_media/config/install/core.entity_view_display.media.az_image.default.yml
modules/custom/az_media/config/install/core.entity_view_display.media.az_image.media_library.yml
modules/custom/az_media/config/install/field.field.media.az_image.field_az_caption.yml
modules/custom/az_media/config/install/field.storage.media.field_az_caption.yml
modules/custom/az_paragraphs/az_paragraphs.libraries.yml
modules/custom/az_paragraphs/az_paragraphs_photo_gallery/az_paragraphs_photo_gallery.info.yml
modules/custom/az_paragraphs/az_paragraphs_photo_gallery/config/install/core.entity_form_display.paragraph.az_photo_gallery.default.yml
modules/custom/az_paragraphs/az_paragraphs_photo_gallery/config/install/core.entity_view_display.paragraph.az_photo_gallery.default.yml
modules/custom/az_paragraphs/az_paragraphs_photo_gallery/config/install/field.field.paragraph.az_photo_gallery.field_az_photos.yml
modules/custom/az_paragraphs/az_paragraphs_photo_gallery/config/install/field.storage.paragraph.field_az_photos.yml
modules/custom/az_paragraphs/az_paragraphs_photo_gallery/config/install/paragraphs.paragraphs_type.az_photo_gallery.yml
modules/custom/az_paragraphs/az_paragraphs_photo_gallery/templates/paragraph--az-photo-gallery.html.twig
modules/custom/az_paragraphs/css/az_paragraphs_az_photo_gallery.css
modules/custom/az_paragraphs/src/Plugin/paragraphs/Behavior/AZPhotoGalleryParagraphBehavior.php

This pull request adds a dual purpose Photo Gallery paragraph that covers the functionality of the old photo gallery and carousel types from QS1.
This PR contains the following:
- a paragraph module (`az_paragraphs_photo_gallery`) that contains `az_photo_gallery`
- the addition of a `caption` field to the `az_image` media bundle
- a paragraph behavior plugin that allows choosing between the grid display and the slider display as an option.
- a template that handles rendering both cases; the grid uses a modal display with hint images, and the slider display uses a carousel.
#545 
- Create a Flexible Page
- Add a Photo Gallery paragraph
- Add several media items to the paragraph
- Choose a display type, eg. Slider or Grid.
- Save content
- Verify functionality of the Photo Gallery based on …

Fixes #545 Create Photo Gallery Paragraph Type

---

.ddev/commands/web/phpunit-fastest
.lando.yml
.probo.yaml
composer.json

Or rather, run multiple tests at once.
This uses [Fastest](https://github.com/liuggio/fastest) to parallelize PHPUnit test classes.
Modify the probo build to use Fastest to run more jobs at once. Also provide a new lando command:
```
lando phpunit-fastest
```
to run all the tests locally.
az-digital/az_quickstart/issues/507
Details including terminal output are on the issue. In summary, I've run this many times locally and multiple times in Probo (much faster in Probo!)
Additionally, I verified that these parallel test runs won't conflict because the Drupal test runner automatically prefixes database tables for each test.

Run tests faster! (#507)

---

composer.json

Adds our custom `pheremone/phpcs-security-audit` [fork](https://github.com/az-digital/phpcs-security-audit)  as a composer repository so that _some_ composer operations can be performed directly on this repo (e.g. dependabot update checks) without using a scaffolding / site-specific repository.
#671 
- Verified that a local `compser install` operation is able to complete successfully (even though the resulting build is unusable as a Drupal site).
- Will probably be impossible to test dependabot without merging this.

Closes #671: Add pheremone/phpcs-security-audit fork as composer repository.

---

composer.json

Latest Drupal contrib module updates.  Intentionally omitted Bootstrap Barrio theme updates since I think we'll want to tackle that separately (or potentially really fork Bootstrap Barrio).
3 of the existing contrib module patches we were using are no longer needed with these updates.
#670 
Verified composer install still worked inside lando

Closes #670: April 2021 Drupal contrib maintenance updates.

---

.probo.yaml

Updates ProboCI config to stop referencing the `credentials.sh` asset filename since it turns out that specific filename has special significance in Probo and if it exists, it gets loaded all the time which was causing problems for the migration testing pipeline we're working on adding to our ProboCI config.
#719 
ProboCI FTW

Fixes #719: Don't use magic credentials.sh filename in ProboCI config.

---

.github/dependabot.yml

- Run dependabot daily instead of weekly
- Automatically add reviewers to dependabot PRs

Increase dependabot frequency and add reviewers to dependabot PRs.

---

.github/workflows/review-site.yml

This update should make the workflow watching job more reliable when determining whether or not to proceed to the site install job.
#617 
Tested by creating a test branch and running the action.

Kitten D9 github action fixes

---

composer.json

Adds patch for a [known bug in the Image Widget Crop module](https://www.drupal.org/project/image_widget_crop/issues/3117828) that was causing the mysterious Ajax fatal errors when the "enter" key was pressed within the Add media dialog when embedding media in CKeditor fields using the media library editor plugin.
Fixes #638 
Verified composer build still worked in Lando.

Fixes #638: Added patch for Image Widget Crop module bug affecting media library UX.

---

modules/custom/az_accordion/src/Plugin/Field/FieldWidget/AZAccordionWidget.php
modules/custom/az_card/src/Plugin/Field/FieldWidget/AZCardWidget.php

The form elements for the title field in the Accordion and Card FieldWidget plugins was missing a `#maxlength` value so the default textfield form element value was being used (128).
#738 
ProboCI FTW

Fixes #738: Add #maxlength to title field form element in Accordion and Card FieldWidgets.

---

modules/custom/az_event/az_event.module
modules/custom/az_event/config/install/core.entity_view_display.node.az_event.default.yml

Event tags had no styling so this PR adds the need styling to match what was done for Person
This PR adds a function to `modules/custom/az_event/az_event.module` to add the needed styling to field_az_event_category. 
This was based on what was done in QS1: https://bitbucket.org/ua_drupal/ua_quickstart/pull-requests/424
And on this discussion: https://drupal.stackexchange.com/questions/181341/add-class-to-content-field-link/260232#260232
Thanks @trackleft for some help getting the terms inline.
#727 
Probo and local dev
How to test:
1. Create at least two taxonomy terms in the Event Category taxonomy
2. Add an event and apply event categories to it
3. Verify that the taxonomy terms display with correct styling

Add styling to event category taxonomy terms (Closes #727)

---

modules/custom/az_paragraphs/az_paragraphs_text_background/az_paragraphs_text_background.install
modules/custom/az_paragraphs/az_paragraphs_text_background/templates/paragraph--az-text-background--default.html.twig
modules/custom/az_paragraphs/css/az_paragraphs_az_text_background.css
modules/custom/az_paragraphs/src/Plugin/paragraphs/Behavior/AZTextWithBackgroundParagraphBehavior.php

Adds additional spacing (padding) setting to existing Text with Background paragraph behavior settings.
The database update contained here is still untested and probably needs work.
#691 
Locally with lando (but not the DB update yet).

Fixes #691: Added spacing (padding) setting to text with background paragraph type.

---

modules/custom/az_event/config/install/core.entity_form_display.node.az_event.default.yml

When working on an issue around Event end dates, Dana noticed that an extra 'When' field automatically gets added on the edit form. This is an easy configuration change.
Having the extra widget is potentially confusing to content editors. It can easily be turned off on the form display for the field.
#813 
Tested locally and in Probo
To test:
1. Create an event and save
2. Go back in to edit that same event
3. Confirm that extra 'When' field with start date does not appear unless you click on Add another item.
Probo site: https://7b5e2985-cedf-4a13-ab91-3a35916c835d--pr-815.probo.build/

Closes #813: Set 'When' field to not show extra empty widget on Event form display

---

modules/custom/az_news/config/install/core.entity_form_display.node.az_news.default.yml
modules/custom/az_news/config/install/core.entity_view_display.node.az_news.default.yml

Closes #745 
There were several elements we said we'd come back to later to polish how news stories appear for the news content type.
Before:
-Lead body copy not applying to subheading
-Column width appears too narrow on large displays
-Image not full width
-Caption same size as body text
Changes made by this PR:
-Set column width to `col-lg-10 offset-lg-1`
-Made headline `text-midnight` to match how we have it in other news displays
-Fixed bug where subhead not displaying as lead body copy size (would still love for this to be larger in bootstrap)
-Set image size to large
-Set caption to `small`
Column width is now similar to QS1 and gives about 85 characters max per line. We could make more readable by increasing both text size and line height in bootstrap. 
After:
Bonus: Updated order …

Closes #745: Polish display for News content type nodes

---

modules/custom/az_media/config/install/core.entity_view_display.media.az_image.az_small.yml
modules/custom/az_media/config/install/core.entity_view_display.media.az_image.az_square.yml
modules/custom/az_media/config/install/core.entity_view_mode.media.az_large.yml
modules/custom/az_media/config/install/core.entity_view_mode.media.az_medium.yml
modules/custom/az_media/config/install/core.entity_view_mode.media.az_natural_size.yml
modules/custom/az_media/config/install/core.entity_view_mode.media.az_small.yml
modules/custom/az_media/config/install/core.entity_view_mode.media.az_square.yml
modules/custom/az_media/config/install/filter.format.az_standard.yml
modules/custom/az_media/config/install/image.style.az_medium.yml
modules/custom/az_media/config/install/image.style.az_small.yml
modules/custom/az_media/config/install/image.style.az_square.yml

This PR adds needed image styles, view modes, and displays for using images at different sizes (more closely matching QS1)
Currently some image styles/displays are missing or do not work properly. This PR:
- Adds view mode, image style, and display for "small" - set to 360px (same as QS1)
- Adds image style and updates display for "square" - set to 220x220 (same as QS1)
- Updates image style for medium to 760px (to match QS1, was 360px)
- Updates which embed media is used by Standard text formatter (now: default, small, medium, large, original, card image)
- Set default display to use the small image style (default in QS1 is small)
Some questions/issues:
- Images do not scale based on the column width of where the are placed (I believe they do in QS1, but not sure how that is achieved. …

Closes 743: Updating image styles and display modes

---

modules/custom/az_news/az_news.info.yml
modules/custom/az_news/az_news.install.php
modules/custom/az_news/config/install/field.field.node.az_news.field_az_main_content.yml

This adds the 'Photo Gallery' paragraph type to the extra body field on News
The photo gallery paragraph was not available when we first built the News content type, but it is a useful way for editors to add images to stories.
#842
Tested locally and in Probo.
To test:
1. Add Content > News
2. Add the the photo gallery paragraph at the bottom of your story.
3. Verify that the grid or slider appears
https://7b5e2985-cedf-4a13-ab91-3a35916c835d--pr-846.probo.build/news/test-news-photo-gallery

Closes #842: Add photo gallery to news

---

composer.json

Added patch to Drupal.org for issue https://www.drupal.org/project/ckeditor_bs_grid/issues/3218760
Have not tested if this breaks core, and not sure if we should worry about that.
There is also some discussion about setting equal width as the default option 
https://www.drupal.org/project/ckeditor_bs_grid/issues/3208113
which has been blocked by https://www.drupal.org/project/ckeditor_bs_grid/issues/3193368
https://github.com/az-digital/az_quickstart/issues/736
Probo and local.

Closes #736: Adding patch to fix claro dialog with ckeditor_bs_grid plugin

---

modules/custom/az_event/az_event.module
modules/custom/az_event/config/install/views.view.az_events.yml

This PR adds logic similar to what was present in Quickstart 1.0 where events are split into multiple occurrences listed by delta.
Filters on the Event views are changed from 'now' to 'today' to reflect the fact that some events for the day would be hidden if they'd already gone past your start timezone.
#723 
#806 
Note: it seems it's become much more convoluted to test for this. In QS1, we did something like:
```
$row_index = $context['entity']->view->row_index;
```
However, in Drupal9, it doesn't appear that the EntityRow type views provide the row_index to the node builder because of the type of caching they do (the `row_index` is still null by the time the entities are rendered). I'm currently getting around this by injecting that information before rendering, but we should look for …

Fixes #806, Fixes #723 Update Events Views to use Delta Splitting, Change 'Now' to 'Today'

---

themes/custom/az_barrio/css/style.css
themes/custom/az_barrio/templates/navigation/menu--sidebar.html.twig

Removed active class from active trail items because arizona bootstrap reserves the active class for actually active links.
Blocked by https://github.com/az-digital/arizona-bootstrap/pull/319
Blocked by https://github.com/az-digital/arizona-bootstrap/issues/318
Closes #864
Locally by compiling arizona bootstrap from PR 318 and moving it into az_quickstart

Closes #864, Relates az-digital/arizona-bootstrap#318: Active state of sidebar nav.

---

modules/custom/az_seo/az_seo.install

Adds DB update to force install of `field_az_metatag` field storage to resolve config dependencies preventing config distro import.
#886 
Tested on multidev version of existing Quicsktart 2 site on Pantheon.

Closes #886: Force install of field_az_metatag field storage to resolve config dependencies preventing config distro import.

---

config/install/system.date.yml

This sets a default timezone to Arizona/Phoenix for Quickstart sites, which hadn't previously been set. This resulted in the default timezone being UTC, and making most user accounts default to UTC for their own timezone settings. This resulted in dates being a little confusing on new builds.
#873 
- Visit `admin/config/regional/settings` and verify the timezone has been set to Phoenix.
- Visit the edit page of individidual users and verify that their default timezone is Phoenix rather than UTC.

Fixes #873 Add default timezone settings.

---

modules/custom/az_media/config/install/core.entity_form_display.media.az_image.default.yml
modules/custom/az_media/config/install/core.entity_form_display.media.az_image.media_library.yml
modules/custom/az_media/config/install/core.entity_view_display.media.az_image.az_large.yml
modules/custom/az_media/config/install/core.entity_view_display.media.az_image.az_medium.yml
modules/custom/az_media/config/install/core.entity_view_display.media.az_image.az_natural_size.yml
modules/custom/az_media/config/install/core.entity_view_display.media.az_image.az_small.yml
modules/custom/az_media/config/install/core.entity_view_display.media.az_image.az_square.yml
modules/custom/az_media/config/install/core.entity_view_display.media.az_image.default.yml
modules/custom/az_media/config/install/field.field.media.az_image.field_az_credit.yml
modules/custom/az_media/config/install/field.storage.media.field_az_credit.yml

This PR adds captions to each view mode of inline images and also creates/adds a field for image credit
A caption field already exists, but was not displaying on images add via the ckeditor. This PR adds the caption field to each view mode (default, small, medium, large, natural, square) and also creates a new field for image credit.
Styling needs to be added for figcaption but may be best as a separate bootstrap ticket ([#322](https://app.zenhub.com/workspaces/quickstart-20-5e8f25351c5b8596956ebb92/issues/az-digital/arizona-bootstrap/322))
#447
#448 
Tested locally and in Probo:
https://cd6b51a5-110f-4cd6-8d2d-6aaaeec8ff25.probo.build/test-captions
To test:
1. Create a page
2. Add an image
3. Enter caption and credit when adding
4. Edit media and set a size
5. Verify image, caption, and …

Closes #447 #448: Add captions and credit field to inline images

---

modules/custom/az_media/config/install/core.entity_view_display.media.az_remote_video.az_large.yml
modules/custom/az_media/config/install/core.entity_view_display.media.az_remote_video.az_medium.yml
modules/custom/az_media/config/install/core.entity_view_display.media.az_remote_video.az_natural_size.yml
modules/custom/az_media/config/install/core.entity_view_display.media.az_remote_video.az_small.yml
modules/custom/az_media/config/install/core.entity_view_display.media.az_remote_video.az_square.yml

This PR creates display modes for remote videos similar to images and with the same sizing.
Content editors in QS 2 currently can select the same sizes when adding a remote video as they do for images, but these sizes do not do anything because the Remote video view modes are not set.
This PR adds view modes for small, medium, large, natural size, and square and also set a max-width for some sizes (to match what we did for images):
- small: max-width 360px
- medium: max-width 760 px
- square: max-width 220 px (and also 4:30 ratio matching QS1)
- default: no sizing
- large: no sizing
- natural size: no sizing
#748 
Tested locally and in Probo.
Review site: https://a2169b16-8bb1-49a6-802a-1096efb6c13b.probo.build/video-display-modes
To test:
1. Add video to page
2. Edit media and select …

Closes #748: Set video display modes

---

az_quickstart.info.yml

Adds the Content Moderation (in core) module to the install profile in order to address content permissions issue. By enabling the module, you grant "view unpublished" permissions to editors without modifying permissions to a per node basis. This method keeps permissions on a per node type basis. Enabling the module does not enable content workflows--you must manually enable workflows to specific content types.
Closes #844 
Locally and on Probo

Add Content Moderation to install profile

---

modules/custom/az_paragraphs/az_paragraphs.libraries.yml
modules/custom/az_paragraphs/css/az_paragraphs_widget.css

This was being caused by the overflow attribute shown here. Removing that attribute resolves this issue, but may have other implications depending on where else these classes are used.
```
.js .paragraph-type {
text-overflow: ellipsis;
overflow: hidden;
white-space: nowrap;
}
```
This CSS was provided by the contrib module in this file: /modules/contrib/paragraphs/css/paragraphs.widget.css
I created a new css file that we will be able to use for any future style changes to the widgets.
https://github.com/az-digital/az_quickstart/issues/651
Locally with Lando
- [ x ] Bug fix (non-breaking change which fixes an issue)

Closes #651 Show full paragraph type labels in the editor experience

---

config/install/user.role.az_content_editor.yml
modules/custom/az_core/az_core.module

This PR changes the 'Quickstart 2' link in the admin toolbar to point to the documentation site quickstart.arizona.edu
#907 
Tested locally and in Probo

Closes #907: Point Quickstart indicator to quickstart.arizona.edu

---

modules/custom/az_flexible_page/az_flexible_page.libraries.yml
modules/custom/az_flexible_page/az_flexible_page.module
modules/custom/az_flexible_page/css/az_flexible_page.theme.css
themes/custom/az_barrio/css/style.css

Apply the Barrio theme's `margin-top: 10px;` from the `.node__content` rule in node.css (now ignored), but add an override on az_flexible_page nodes, following the pattern used by az_person.
Repairs a regression introduced by the fix for Issue #852.

Closes #916 — Restore the Barrio node__content margin-top, override it on az_flexible_page.

---

modules/custom/az_flexible_page/css/az_flexible_page.theme.css

The fix re-introducing `margin-top: 10px` failed to complete the module-specific override for az_flexible_page.
Closes #916 — Restore the Barrio node__content margin-top, override it on az_flexible_page. (PR #921)
Verified that the override works on a local Lando build.

Closes #852: Restore the original fix, broken when re-introducing default margins.

---

themes/custom/az_barrio/config/optional/block.block.az_barrio_footer_menu_info.yml
themes/custom/az_barrio/config/optional/block.block.az_barrio_footer_menu_main.yml
themes/custom/az_barrio/config/optional/block.block.az_barrio_footer_menu_resources.yml
themes/custom/az_barrio/config/optional/block.block.az_barrio_footer_menu_topics.yml

This removes the warnings during install time.  We may also want to look into moving the menu configs out of the profile (as a follow-up issue/PR) in order for these blocks to actually get properly placed during install since the install profile config is installed _after_ the theme config.
#939 

Closes #939: Fix install time footer menu-block config warnings.

---

modules/custom/az_flexible_page/css/az_flexible_page.theme.css

Attempts to remove the margin-top from elements with the class `node__content` only when they are at the top of the main content area of a Page.
Another iteration in the series of issues #852, #916 ...
On a local Lando build, created some az_flexible_page nodes, verified that there was no margin between the navigation menu and the top of a full-width text on media paragraph at the top of the page content, verified that margins did appear between entries in the `/page-list` view.

Closes #941: Make the selectors in the CSS rule applying the margin-top override very specific.

---

.github/workflows/review-site.yml

The fix for #964 that we merged this morning added an extra line to the multi-line shell command without adding the necessary `\` to the preceding line so now the `drush site:install` command is totally broken 🤦🏻 .
#964

#964: Fix broken drush site:install command (again).

---

modules/custom/az_event/config/install/core.entity_view_display.node.az_event.az_row.yml

There is a bug on small screens for the calendar view on events with the short date (column 1) and event summary info (column 2) stack on mobile rather than appearing side by side as the did in Quickstart 1. 
To fix this, I updated the col classes to match bootstrap 4 (e.g. removing xs).
Before:
After:
#722
Tested locally and in Probo

Fixes column sizes for calendar view on small screens

---

modules/custom/az_paragraphs/az_paragraphs_view/config/install/field.field.paragraph.az_view_reference.field_az_view_reference.yml

This PR sets the install config for the Views paragraph item to only display the intended, front-end views.
This both simplifies the View paragraph type, but also prevents users from selecting potentially harmful views that have been shown to crash sites. 
~~This _does not_ include AZ Page, since that view was not included in this configuration file.~~
After merging in Joe's suggestions it does include AZ Page.
#360 
This is only completing one of the tasks on that ticket, so it should not close it. 
Locally with a new build.
I have not tested this on an existing site.

#360: Limiting the Views options to AZ Events, AZ News and AZ Person.

---

modules/custom/az_paragraphs/az_paragraphs_text_media/templates/paragraph--az-text-media--default.html.twig

This updates the title text on dark background to be white (completes one of the remaining tasks for #656).  If it would be better to merge this into [@trackleft's existing Issue #656 branch](https://github.com/az-digital/az_quickstart/compare/issue/656-text-media-updates), I'd be fine with that.
Before:
After:
#1028 
- [] I have updated the documentation accordingly.

Closes #1028: Update text on media title text on dark background to be white.

---

modules/custom/az_core/az_core.module
modules/custom/az_demo/data/az_demo_event_node.json
modules/custom/az_event/config/install/core.entity_view_display.node.az_event.az_card.yml
modules/custom/az_event/config/install/core.entity_view_display.node.az_event.az_row.yml

This PR is the result of a group workshop on Wednesday Sept 22 2021
Bypass need for using tokens in summary link field in favor of adding our own token `[az-canonical-url]` that checks if the field is empty, and if it is use the node url, otherwise use the field value.  This token is then used in the Field Group Link formatter (custom url setting) on each display mode for each content type that needs to house internal/external content.
Still need to reexport all the display modes and add the field_az_link field to each content type that needs it.
Relevant links https://git.drupalcode.org/project/field_group_link/-/blob/8.x-3.x/src/Plugin/field_group/FieldGroupFormatter/Link.php#L203-213
#446
Locally

Closes #446: Summary link field(s) cannot use tokens.

---

modules/custom/az_card/src/Plugin/Field/FieldWidget/AZCardWidget.php

This PR addresses some of the remaining card improvements.
This PR makes the following changes:
- An empty card will not appear when opening an existing card deck for editting
- Cards have a delete button that will delete them from the deck.
#377 
- Create content with card decks
- Verify that when editing a previously-saved deck, an extra card form isn't added unless the Add Another button is clicked
- Verify that cards can be deleted from the deck (to a minimum of one)

Fixes #377 Card Followup Tasks

---

modules/custom/az_person/config/install/views.view.az_person.yml
modules/custom/az_person/config/install/views.view.az_reorder.yml

- Updates the AZ Person view so that both `grid` and `row` view displays are referencing the correct "reorder" view, rather than "this view/display".
- Updated the AZ Reorder view so "distinct" is checked and caching is turned off.
Review site: https://7b5e2985-cedf-4a13-ab91-3a35916c835d--pr-1115.probo.build/
Closes #1064 
- Tested locally with demo content
- Pending Probo test

Closes #1064 - Fix reorder people

---

config/optional/workflows.workflow.editorial.yml

On the COVID-19 and Quickstart sites I noticed that the default editorial workflow for content moderation makes small edits more difficult because you have to save as a draft and then go back and save as published (no way to move from published state to published state like you can in QS1). This PR adds published state for "From" for the Published transition.
Before:
After:
#1122 
Locally and in Probo
https://a24a042a-fb91-4897-a080-806c4265ea93.probo.build/
Note: you may need to turn the workflow on for a particular content type you are testing.

Closes #1122 Updates editorial workflow to allow published to published

---

modules/custom/az_migration/migrations/migrate_plus.migration.az_user.yml

The `authenticated user` role is automatically added to all users and not explicitly assignable.  Since we are want all migrated users to only have the `authenticated user` role, we can simply omit our existing (problematic) role mapping which is causing migration failures for source sites having users with no assigned roles.
This also includes some minor cleanup changes and makes the `access` (last access) field value optional (since it isn't populated on the source site if a user has never logged in). 
#1154 
Locally with lando

Closes #1154: Remove problematic role mapping from az_user migration.

---

.probo.yaml

Adds step to check for PHP entries in the watchdog logs.
#1164

Closes #1164: Add ProboCI step to check for PHP error/notice logs.

---

.lando.yml

Use lando drupal9 recipe
Update database to mariadb:10.4
DDev doesn't have the same segfault issue as lando when running composer install with npm packages included.
#1177 
Locally by running
```
lando start
lando install
lando phpcs
lando phpunit
lando phpcbf
```

Updating .lando.yml to be used with Apple M1 Chip

---

modules/custom/az_paragraphs/src/Plugin/paragraphs/Behavior/AZTextWithMediaParagraphBehavior.php

Fixes #1184 Regression: Bottom margin on text on media paragraphs no longer works.

---

modules/custom/az_paragraphs/src/Plugin/paragraphs/Behavior/AZTextWithMediaParagraphBehavior.php

Content editors (me and Catherine) have been confused about the "none" option for Content position on Text on Media. Neither of us realized that this option would make the box larger than the other positions.
Changing the language to say "Full-width" will be more understandable to content editors.
#1166 
Tested in locally and in Probo

Closes #1166 Changes Content position 'none' option to say 'full-width'

---

modules/custom/az_migration/migrations/migrate_plus.migration.az_node_uaqs_basic_page_to_az_page.yml
modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_uaqs_basic_page_to_az_page.yml

Add two new migrations, one for body field, and one for node.
body field migration creates either a text or html paragraph type
node creates the flexible page and attaches the new paragraph
Closes #1146 
Locally

Closes #1146 Migrate basic page content type (to az_page)

---

config/optional/workflows.workflow.editorial.yml

Fixes the content moderation workflow issue described in #1197 where you cannot go from Published > Published.
#1197
Locally and in Probo
To test:
1. Create a page and save as Published
2. Edit that same page and make a change
3. Save as published again
4. Verify that the change appears on the live page.

Closes #1197 Fixes content moderation workflow problem

---

modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_card_deck.yml

Updates card deck paragraph migration to use correct field name for card count since changes made to `AzParagraphsItem` source plugin made in #1130.
#1192 

Closes #1192: Use correct field name from AzParagraphsItem source plugin in card deck migration.

---

modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_single_card.yml
modules/custom/az_migration/migrations/migrate_plus.migration.az_user.yml

Fixes issues that were preventing the Single Card paragraph migration from working correctly.
Note: this adds a migrated path lookup step to the link field on Single cards which means that the Single Card migration needs to be ran a second time (in update mode) after the node and term migrations have been run to update the migration lookup stubs:
```
$ drush mim --group az_migration
...
(lots of progress messages)
...
$ drush mim az_paragraph_single_card --update
[notice] Processed 17 items (0 created, 17 updated, 0 failed, 0 ignored) - done with 'az_paragraph_single_card'
```
The term and node migrations used in the migrated path lookup step are added as optional dependencies because the single card migration is a dependency for the flexible page migration and so it can't be added as a …

 Closes #1150: Fix issues with Single Card paragraph migration.

---

modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_single_card.yml
modules/custom/az_migration/src/Plugin/migrate/source/AZParagraphsItem.php

Still seeing issues with single card migration (since all the fields are optional and not always populated).  This should resolve remaining issues.
This PR also adds a condition to the query used in the AZ Paragraphs Item migration source plugin to omit archived (deleted) paragraph items.  We'll probably want to discuss that bit.
#1150 
Locally with lando using a Pantheon site as the source.

#1150: Fixes additional single card migration issues.

---

modules/custom/az_card/src/Plugin/Field/FieldFormatter/AZCardDefaultFormatter.php
modules/custom/az_card/templates/az-card.html.twig
modules/custom/az_paragraphs/src/Plugin/migrate/process/ParagraphsBehavior.php
modules/custom/az_paragraphs/src/Plugin/paragraphs/Behavior/AZCardsParagraphBehavior.php

Add a card deck paragraph-wide configuration option for clickable card.
If the option is selected all cards get the stretched-link class added.
This stretches the link over the entire card.
#737 
Locally and on probo.

Closes #737 Clickable Card

---

modules/custom/az_global_footer/config/install/block.block.az_barrio_footer_menu_social_media.yml

This PR adds classes to the block for the social media connect menu to match those that the other global footer menus have.
After this fix, the menus align properly on mobile:
#1221 
Locally and in Probo.

Closes #1221: Adds classes for connect menu block

---

modules/custom/az_global_footer/config/install/block.block.az_barrio_footer_menu_info.yml
modules/custom/az_global_footer/config/install/block.block.az_barrio_footer_menu_resources.yml
modules/custom/az_global_footer/config/install/block.block.az_barrio_footer_menu_social_media.yml
modules/custom/az_global_footer/config/install/block.block.az_barrio_footer_menu_topics.yml
themes/custom/az_barrio/az_barrio.info.yml
themes/custom/az_barrio/az_barrio.theme
themes/custom/az_barrio/config/install/az_barrio.settings.yml
themes/custom/az_barrio/config/schema/az_barrio.schema.yml
themes/custom/az_barrio/templates/layout/page.html.twig

- Adds a new theme region to the footer (`footer_sub_menus`), specifically for menu blocks (below existing `footer_sub` region)
- Sets the `bootstrap_barrio_region_clean_footer_sub_menus` theme setting to `true` by default 
- Changes default theme setting value for `bootstrap_barrio_region_clean_footer_sub` back to `false`
- Changes default theme region for global footer menu blocks to new region
#1228, #1229

Closes #1228, closes #1229: Added new menu-specific footer theme region.

---

config/install/system.image.gd.yml
config/install/system.image.yml

This specifies a higher setting than default Drupal for image toolkit quality.
This changes the image toolkit rendering quality from 75 to 92. This number was chosen as a balance between quality and file size. The remaining points of percentage up to 100% quality greatly increase file size.
#1215 
- verify that `/admin/config/media/image-toolkit` reports accurate quality
- create content with image styles and verify acceptable content quallity.

Fixes #1215 Image Quality Issues

---

az_quickstart.info.yml
composer.json

Expedites removal of quickedit from Quickstart's default installed modules to eliminate browser console errors.
Does not (currently) automatically uninstall quickedit.  I would be open to adding that.
#1254

Closes #1254: Don't install quickedit module by default.

---

modules/custom/az_card/src/Plugin/Field/FieldFormatter/AZCardDefaultFormatter.php

Should fix undefined index notices being generated on sites with existing cards after updating to 2.0.15.
Closes #1248 
Issue introduced with #1220
Needs to be tested.

Closes #1248: Fix undefined index notices generated for existing cards.

---

composer.json

The `2.1.x` branch has been opened in preparation for creating the `2.1.0-alpha1` release.  We need to change the composer branch alias for `dev-main` to now be `2.2.x-dev` since main is now effectively `2.2.x`.  This change should also be back-ported to both the `2.1.x` and `2.0.x` branches.

Update composer branch alias for dev-main to 2.2.x-dev.

---

themes/custom/az_barrio/config/install/az_barrio.settings.yml
themes/custom/az_barrio/templates/layout/page.html.twig

Removes container and row divs wrapping az_barrio alert theme region.
Closes #1262

Closes #1262: Make az_barrio alert theme region full-width.

---

modules/custom/az_migration/migrations/az_redirects.yml

The current migration for redirects suffers from an error documented here:
https://www.drupal.org/project/redirect/issues/3200841#comment-14040845
This MR implements a variation of the solution from the same link.
https://github.com/az-digital/az_quickstart/issues/1265
I implemented this in my own custom migration which takes the redirect migration and makes some project specific changes. I manually tested this by rolling back and re-running the migration multiple times, making various changes to the source database's redirect table.

Fixes #1265: Redirect Migration Status Code Fix

---

composer.json

Applies the patch/merge-request provided by the Drupal issue: https://www.drupal.org/project/drupal/issues/1810148
Corrects exposed grouped filters behavior/results.
Review site: https://7b5e2985-cedf-4a13-ab91-3a35916c835d--pr-1261.probo.build/
Closes #1260 
Tested on a local build. Pending Probo build for additional testing.

Closes #1260: Views grouped exposed taxonomy term filters do not work

---

modules/custom/az_global_footer/README.md
modules/custom/az_global_footer/az_global_footer.info.yml
modules/custom/az_global_footer/config/install/block.block.az_barrio_footer_menu_info.yml
modules/custom/az_global_footer/config/install/block.block.az_barrio_footer_menu_main.yml
modules/custom/az_global_footer/config/install/block.block.az_barrio_footer_menu_resources.yml
modules/custom/az_global_footer/config/install/block.block.az_barrio_footer_menu_social_media.yml
modules/custom/az_global_footer/config/install/block.block.az_barrio_footer_menu_topics.yml

Make block_class a dependency of az_global_footer
Make az_global_footer a dependency of the config within az_global_footer.
Closes #1280
Test by uninstalling az_global_footer and reinstalling az_global_footer.

Closes #1280 Add block_class as dependency and make az_global_footer a dependency of its config.

---

az_quickstart.profile
themes/custom/az_barrio/az_barrio.theme
themes/custom/az_barrio/config/install/az_barrio.settings.yml
themes/custom/az_barrio/config/schema/az_barrio.schema.yml
themes/custom/az_barrio/templates/layout/page.html.twig
themes/custom/az_barrio/tests/src/Functional/AzBarrioTest.php
themes/custom/az_barrio/theme-settings.php

Adding two new theme settings for setting column classes on the parent divs of the branding region and the header1 &2 regions.
Set page variable keys for `az_header_responsive_column_classes_one` and `az_header_responsive_column_classes_two`
Should contain a string with classes separated by a space.
Added a new section on the `az_barrio` theme settings page.
I moved the existing classes that existed in the page.twig.html file into the default settings.
Added schema config for the two new settings.
Tested config distro update using the merge strategy to import the defaults.
**Header columns are missing until defaults imported via config distro.**
**Once imported it looks like this with the imported classes:** 
Closes #1293 
`lando drush cd-update -y` config updated.

Closes #1293 Make header columns configurable

---

.lando.yml
composer.json

Adds a Drupal core patch to fix an issue that prevents our AZ News Feeds menu local task from appearing at `/admin/content` when the content_moderation module isn't installed.
See https://www.drupal.org/project/drupal/issues/3199682
Fixes #1303.
Locally on lando.

Closes #1303: Add Drupal core patch to fix missing az_news_feeds local menu task when content_moderation module not installed.

---

composer.json

Updated version of old PR for adding Better Exposed filters module.  This now uses the latest version of the module (5.0) and adds a patch to remove the dependency on jquery_ui_slider.
#682 

Closes #682: Added Better Exposed Filters module.

---

composer.json
modules/custom/az_paragraphs/az_paragraphs_view/config/install/core.entity_view_display.paragraph.az_view_reference.preview.yml

- Adds [patch from drupal.org](https://www.drupal.org/project/viewsreference/issues/2938433) for viewsreference module that adds a "Label" field formatter for viewsreference fields
- Enables customized preview entity field display config (view mode) for views paragraphs that uses new label formatter
- Should fix #1296 since the view(s) won't actually be rendered in the paragraphs preview/edit UIs anymore
Note: the view label that is displayed is a clickable link _only_ if the current user has views edit access.  i.e. it looks like this for content editors:
Fixes #1296 

Closes #1296: Use views label instead of rendered views inside paragraph previews.

---

modules/custom/az_accordion/templates/az-accordion.html.twig

Fixes Accordions so they match Bootstrap styling; nested `h3` tag has been removed from inside the `button` tag.
Accordions currently look like this on Quickstart:
This is what they will look like with this fix:
Review site: https://7b5e2985-cedf-4a13-ab91-3a35916c835d--pr-1335.probo.build/pages/accordions
Closes #739 
Pending Probo test

Closes #739 - Accordions should match Bootstrap

---

modules/custom/az_paragraphs/src/Plugin/paragraphs/Behavior/AZDefaultParagraphsBehavior.php
modules/custom/az_paragraphs/src/Plugin/paragraphs/Behavior/AZTextWithMediaParagraphBehavior.php
themes/custom/az_barrio/az_barrio.theme

Attributes class arrays should always be arrays and never strings.
Closes #1225 
Probo
Go to text on media page, add margin bottom to one of the paragraphs, and it still works.
Go to theme settings and upload SVG and mark that it should be rendered inline, with  `qs-logo-svg-inline` class

Closes #1225: Removing setting the class array as a string everywhere, and fixing bottom spacing issue.

---

themes/custom/az_barrio/templates/content/node--az-person--az-card.html.twig
themes/custom/az_barrio/templates/content/node--az-person--az_row.html.twig
themes/custom/az_barrio/templates/content/node--az-person--full.html.twig

Closes #1341 with the following changes:
- In the theme implementation for AZ Person cards, replace the `&nbsp;` between the first and last names with standard whitespace. This allows the names to wrap as expected.
- Make the same replacement on Row and Full displays for AZ Person, for consistency.
(The original commit below was for issue 1328 before it was split into two issues, 1328 and 1341.)
#1341 
Tested with Probo and locally with Lando.
Before:
After:

Closes #1341: fix line break issues with names in AZ Person Grid View

---

modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_flexible_page_sub.yml

az_paragraph_flexible_page_sub migration adds extra text areas even if there is no subhead value.
Closes #1344
Used arizonaedu test db to migrate subhead fields to text paragraphs.
If there was a value in the subhead a new paragraph is created
If there is no value in the subhead field, no new paragraph is created.

Closes #1344 Migration: Extra (blank) Text Boxes are showing up 

---

modules/custom/az_migration/src/Plugin/migrate/source/NodeWithFieldCollection.php

The recently added `NodeWithFieldCollection` source plugin seems to not be available to migrations. Migrations using it cannot be run and report 'Migration not found.' 
#1361 
- Create migration using the plugin
- Run migration before and after applying this pull request
- Verify that the migration was previously not available
- Verify that the migration runs after this PR's change

Fixes #1361 NodeWithFieldCollection source plugin not accessible.

---

modules/custom/az_paragraphs/css/az_paragraphs_az_text_media.css
modules/custom/az_paragraphs/css/az_paragraphs_full_width.css

Simple fix of the class specified in the modules/custom/az_paragraphs/css/az_paragraphs_full_width.css to match the class on the elements in Text with Background
#1331 
Locally and in Probo
Appreciate testing to make sure it doesn't break Text on Media (particularly when using Media Aspect Ratio) or other full-width elements.
https://5ec40ba7-e988-4dc9-9e2f-0560bea3e812.probo.build/pages/test-page

Closes #1331: Make sidebar not overlap text for Text with Background

---

modules/custom/az_mail/az_mail.install

#1333 
- Created a new site with this change
- Installed `az_mail`
- Confirmed `system.mail.interface.default` was set to `SMTPMailSystem`

Closes #1333: Configure system mail interface to use SMTP during install.

---

modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_headed_text.yml
modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_html.yml
modules/custom/az_migration/src/Plugin/migrate/process/EntityEmbedProcess.php

Adds `az_` prefix to ID for new EntityEmbedProcess plugin consistent with the naming convention we recently agreed upon for _new_ migration plugins:
- Use `az_` prefix in the ID (machine name) of the plugin
- Do not prefix class name of plugin
Would be best to merge this _before_ creating today's releases, if possible.
#1371 

Closes #1371: Add az prefix to EntityEmbedProcess migrate plugin ID.

---

composer.json

We need to change the composer branch alias for dev-main to now be 2.3.x-dev since main will effectively be 2.3.x once we release 2.2.0. 
This should be merged _after_ any remaining PRs that we still want to include in the `2.2.0` release.
This change should also be back-ported to both the 2.1.x and 2.0.x branches.

#1367: Update composer branch alias for dev-main to 2.3.x-dev

---

composer.json
themes/custom/az_barrio/templates/layout/page.html.twig

We inadvertently reused the global attributes object instead of the navbar specific one.
Fixes #1384
Related to #1363
Locally

Fixes #1384 Global Footer (after 2.2 Update) Formatting Incorrect

---

modules/custom/az_card/src/Plugin/Field/FieldWidget/AZCardWidget.php

Closes #1390 by setting the maxlength for the link_uri textfield in AZCardWidget.php. On the Card paragraph form, the current textfield for the Card Link URL has the default maxlength of 128 characters. This PR sets the maxlength to 2048 characters to match the storage limit of the field.
#1390 
Tested in Probo on [this page](https://7b5e2985-cedf-4a13-ab91-3a35916c835d--pr-1392.probo.build/1390-test) with these links:
- [Google Maps](https://www.google.com/maps/place/32%C2%B025'50.6%22N+110%C2%B051'39.1%22W/@32.43072,-110.8630387,17z/data=!3m1!4b1!4m6!3m5!1s0x0:0x22ac80a3fa642aa9!7e2!8m2!3d32.4307203!4d-110.8608496) (184 characters)
- [Google Search](https://www.google.com/search?as_q=you%20have%20to%20write%20a%20really%20really%20long%20search%20to%20get%20to%202000%20characters.%20like …

Closes #1390 by setting maxlength of Card Link URL field to 2048 characters

---

modules/custom/az_demo/migrations/az_demo_text_media_paragraph.yml
modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_content_marquee.yml
modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_full_width_media_row.yml

Add back appropriate fields for background styles in text_on_media paragraphs during migration.
Fixes #1397
Fixes #1132
Locally

Fixes #1397 Update migrations to add text_media_spacing default and change bg_attach to bg_attachment

---

modules/custom/az_core/tests/src/Functional/ConfigOverrideTest.php
modules/custom/az_demo/tests/src/Functional/AZDemoContentTest.php
modules/custom/az_paragraphs/tests/src/Functional/AZParagraphsTest.php
modules/custom/az_paragraphs/tests/src/FunctionalJavascript/AZParagraphsJavascriptTest.php

Upgrading PHPstan caused more issues to be found in our existing tests related to this Drupal change record:
https://www.drupal.org/node/3083055
Fixes #1415 

Fixes #1415: Add required default_theme property to all tests.

---

modules/custom/az_paragraphs/config/optional/embed.button.az_embed_content.yml
modules/custom/az_paragraphs/config/optional/embed.button.az_embed_content_block.yml

Updated two embed button icons in the CKEditor (embed content and embed content block) using the icons designated in issue #396. 
Update involved two files:
- embed.button.az_embed_content.yml
- embed.button.az_embed_content_block.yml

Closes #396 Updated CKEditor icons for embed buttons

---

composer.json

Patching Date Ap Style to fix all day setting in relation to time display.
Fixes #1438 
Log into probo site
Go to the calendar page `/calendar`
See time appears.
Go to `/events/pi-day`
edit the pi-day site to be an all-day event.
See All Day appears

Fixes #1438: Add patch for AP Style Date module time display issue

---

modules/custom/az_select_menu/css/az-select-menu.css
modules/custom/az_select_menu/templates/az-select-menu.html.twig

Closes #1433 with the following changes:
- In az-select-menu.css, update styling of the select element to match the height of the Go button
- In az-select-menu.css, update top margin of div.select-menu-label to vertically align the label text with the other text in the menu
- In az-select-menu.html.twig, add if statement to display the pre-form text element only if the text is not empty
- In az-select-menu.html.twig, correct the screen reader label for the pre-form text to reference preform_text_sr_only instead of button_text_sr_only
#1433 
Tested in Probo: please see the [Select Menu Test](https://7b5e2985-cedf-4a13-ab91-3a35916c835d--pr-1434.probo.build/select-menu-test) page.
Before:
After:
After (showing "I am a" label alignment):
To test the changes:
1. Enable the Quickstart Select …

Closes #1433 Fix alignment and label issues with Quickstart Select Menu

---

modules/custom/az_news/az_news_feeds/src/EventSubscriber/AzNewsFeedsMigrateSubscriber.php
modules/custom/az_news/az_news_feeds/src/Form/AzNewsFeedsAdminForm.php

Moves AZ News Feed URL modification out of Pre:Import event subscriber and into settings form submit handler since modifying the URL during the migrate Pre:Import hook doesn't allow the migration to correctly detect how many source rows are available.
Closes #1302 

Closes #1302: Fix AZ News Feed if <30 stories match configured tag(s).

---

modules/custom/az_migration/README.md
modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_chucks_view.yml
modules/custom/az_migration/src/Plugin/migrate/process/ParagraphsChunksViewDisplayMapping.php
modules/custom/az_migration/src/Plugin/migrate/process/ViewsReferenceMapping.php

Adds new ViewsReferenceMapping migrate process plugin and deprecates old ParagraphsChunksViewDisplayMapping plugin.
New plugin performs migrate lookups on source viewsfield argument values if present.  Provides built-in mappings for default QS1 views but custom views can be used via `view_mapping` migration configuration key.
Closes #880 
Pretty extensive local testing with lando.

Closes #880: Add new ViewsReferenceMapping process plugin with views argument lookup handling.

---

modules/custom/az_media/config/install/core.entity_view_display.media.az_image.az_natural_size.yml
modules/custom/az_media/config/install/image.style.az_natural.yml
themes/custom/az_barrio/css/style.css

This issue in #1403 was when you embed an image, set the size to Natural, and align center ... the block aligned left. So I added a wrapper class to override that display setting and make it `flex` instead of `block`. Changes should apply only to the Natural Image display. Did a new class because I didn't want to bother existing blocks using that behavior.
It required changes to two files:
1. Structure > Media Type > Image (Edit) > Manage display (Filename: modules/custom/az_media/config/install/core.entity_view_display.media.az_image.az_natural_size.yml) to add new container/wrapper setting the class to align-image-natural.
2. Added those class settings to style.css:
```
.align-natural-image {
display:flex;
}
```

Closes 1403: Added style for Natural Image behavior

---

modules/custom/az_core/src/AZConfigOverride.php
modules/custom/az_core/src/Plugin/ConfigProvider/QuickstartConfigProvider.php
modules/custom/az_security/az_security.install

This PR adds functionality for quickstart configuration overrides to not install themselves until the module that uses them is ready; this covers the case of `az_security` where it contains overrides for `seckit.settings` but `seckit` is not installed by default.
This means that an attempt to install `seckit.settings` would create problems because it installs configuration for a module that doesn't exist. When a user later attempts to install  `seckit` it would fail, because it would find that its configuration already exists.
This PR attempts to extend the Quickstart configuration provider to wait to install configuration overrides until the dependencies it is based on are present. This creates the notion of a "passive" override that has not be installed yet because a module it depends …

Fixes #1460 Allow for Delayed Configuration Overrides.

---

modules/custom/az_alphabetical_listing/az_alphabetical_listing.module
modules/custom/az_paragraphs/az_paragraphs.module

Change how we look for template files in the az_paragraphs and az_alphabetical_listing modules.
Fixes #1535 
enable Alphabetical listing module and follow its steps for adding to person content type.
In probo, ensure that existing paragraph templates work. Ensure that az_alpha view still works as expected.
Locally create a subtheme and override paragraph template and az_alphabetical listing templates.

Fixes #1535 Allow subthemes to override paragraphs and alphabetical listing.

---

modules/custom/az_core/az_core.module
modules/custom/az_core/src/AZConfigOverride.php
modules/custom/az_core/src/Plugin/ConfigProvider/QuickstartConfigProvider.php

This PR alters our distribution configuration handler to transparently remove permission that do not exist, to be compatible with [a Drupal 9.3 change](https://www.drupal.org/node/3193348)
#1340 
#1180 
WIP
Verify that permissions are removed if they belong to not enabled modules.

Fixes #1340 Drupal 9.3 Permissions Updates

---

composer.json

The [2.3.x branch](https://github.com/az-digital/az_quickstart/tree/2.3.x) has been created.  Before we can create any `2.3.x` releases, we need to update the composer branch alias for `dev-main` from `2.3.x-dev` to `2.4.x-dev` (see https://github.com/az-digital/az_quickstart/wiki/Steps-to-create-minor-release).
This change will need to be merged into main and backported into _all_ existing release branches.
#1561 
Shouldn't break anything.

#1561: Update composer branch alias for dev-main to 2.4.x-dev.

---

modules/custom/az_news/az_news.install

Closes #1570 
Introduced in #1539
- Add PR diff as composer patch to existing site
- Run drush updatedb

Closes #1570: Ensure better_exposed_filters module is installed.

---

modules/custom/az_event/config/install/core.entity_view_display.node.az_event.az_card.yml
modules/custom/az_news/config/install/core.entity_view_display.node.az_news.az_marquee.yml
modules/custom/az_news/config/install/core.entity_view_display.node.az_news.default.yml

Backport of minor entity view display changes identified by @bberndt-uaz and included in #1181.  Needs to be manually backported due to all the config changes happening for 9.3.x.
Closes #1559 

Closes #1559: 2.2.x Backport of minor entity view display fixes from #1181.

---

composer.json

This is a workaround that updates `guzzlehttp/guzzle` (a Drupal core dependency) until a new Drupal core release is created that includes Guzzle 6.5.6.  Might be worth waiting to see if any plans for a core release are announced today before merging this...
Closes #1600
- General QA/testing

#1600: Drupal core to 9.3.14 for SA-CORE-2022-010/CVE-2022-29248.

---

modules/custom/az_paragraphs/az_paragraphs_text_background/az_paragraphs_text_background.install
modules/custom/az_paragraphs/az_paragraphs_text_media/az_paragraphs_text_media.install

Applied fix from #1629 to existing `hook_update_N()` implementations.  This is to prevent the same kind of situation we saw yesterday when trying to apply the new DB update to existing sites in case anyone is still running an old enough version of Quickstart and still needs to apply these old updates.
Closes #1634
See #1627 
Would require building an older version of AZ Quickstart and then applying DB updates.

Closes #1634: Fix invalid count comparisons in existing hook_update_N() implementations.

---

modules/custom/az_migration/az_migration.install

media migration alpha14 has a new dependency on migmag, and not update to enable it, so we are enabling it for az_migration.
Closes #1643
Related #1640 
Related #1639 
Add this pr to an existing site with az_migration enabled.
Run database updates.
See if it works.

Closes #1643 Ensure Migrate Magician is enabled

---

themes/custom/az_barrio/az_barrio.libraries.yml

Changed 'component' to 'theme' in az_barrio's libraries file for style overrides.
Closes #1513.
Tested locally on DDEV with no noticeable difference.
Example before the change, style.css comes before these other files:
```
<link rel="stylesheet" media="all" href="/profiles/custom/az_quickstart/themes/custom/az_barrio/css/style.css" />
<link rel="stylesheet" media="all" href="/themes/contrib/bootstrap_barrio/css/components/tabs.css" />
<link rel="stylesheet" media="print" href="/themes/contrib/bootstrap_barrio/css/print.css" />
<link rel="stylesheet" media="all" href="https://use.typekit.net/emv3zbo.css" />
<link rel="stylesheet" media="all" href="https://fonts.googleapis.com/css?family=Material+Icons+Sharp" />
<link rel="stylesheet" media="all" …
```

Closes #1513: Changes az_barrio style library setting to theme.

---

modules/custom/az_event/config/install/core.entity_view_display.node.az_event.default.yml
modules/custom/az_news/config/install/core.entity_view_display.node.az_news.default.yml
themes/custom/az_barrio/templates/content/node--az-person--full.html.twig

Person, News, Events need some bottom margin on the body so they don't stack directly on top of the footer. 
I added mb-5 to the row or container/wrapper on each display type or twig.
#1648 directly references this issue, as I spent a little time trying to dig up how to complete Person (it sits in a twig)
-Add content to Person, News, and Event. 
-Scroll down to the footer and see if there's adequate spacing between the body content and the footer.

Closes #746: Adds bottom margin to Person, News, Events

---

modules/custom/az_event/az_event.module
modules/custom/az_event/config/install/views.view.az_events.yml
modules/custom/az_event/css/az_calendar_filter.css
modules/custom/az_event/js/az_calendar_filter.es6.js
modules/custom/az_event/js/az_calendar_filter.js

Adds a category filter to the calendar. Additionally, since the vocabulary may not be used on a given site, the filter is disabled if doesn't contain options.
#1626 
- enable demo content
- clear cache
- verify category filter does not appear on calendar
- add terms to event taxonomy
- clear cache
- verify category filter DOES appear on calendar
- assign terms to some events
- verify category filter works as expected and in conjuction with dates chosen by calendar
- Clear cache after ANY change to taxonomy - exposed filter blocks are heavily cached.

Fixes #1626 Add calendar category filter

---

.probo.yaml
modules/custom/az_cas/az_cas.module
modules/custom/az_cas/config/install/az_cas.settings.yml
modules/custom/az_cas/config/quickstart/cas.settings.yml
modules/custom/az_cas/src/Routing/AzCasRouteSubscriber.php
modules/custom/az_cas/tests/src/Functional/AzCasAdminSettingsTest.php
modules/custom/az_cas/tests/src/Functional/AzCasTest.php
modules/custom/az_core/tests/src/Functional/ClearCacheTest.php
modules/custom/az_core/tests/src/Functional/MonitoringPageTest.php
modules/custom/az_core/tests/src/Functional/QuickstartFunctionalTestBase.php
modules/custom/az_core/tests/src/FunctionalJavascript/QuickstartFunctionalJavascriptTestBase.php
modules/custom/az_core/tests/src/Traits/AllowDrupalLoginSetupTrait.php
modules/custom/az_demo/tests/src/Functional/AZDemoContentTest.php
modules/custom/az_paragraphs/az_paragraphs.info.yml
modules/custom/az_paragraphs/tests/src/Functional/AZParagraphsTest.php
modules/custom/az_paragraphs/tests/src/FunctionalJavascript/AZParagraphsJavascriptTest.php
themes/custom/az_barrio/az_barrio.info.yml
themes/custom/az_barrio/tests/src/Functional/AzBarrioTest.php

Alternate PR for addressing both #1607 and #1678 together.  Replaces and combines #1667 and #1679:
- Moved `disable_login_form` implementation from route subscriber to `az_cas_form_user_login_form_alter()` (per suggestions from @trackleft and @joshuasosa). 
- Simplified existing code in `az_cas_form_user_login_form_alter()` (from #1667) to only set the weight of the login link.
- Turn on `disable_login_form` setting by default (from #1679).
- Updates existing tests to prevent failures caused by new default disable_login_form setting (from #1679)
- These needed to be combined because both use `az_cas_form_user_login_form_alter()`.
- Updates existing AZ CAS settings test to work with new `disable_login_form` implementation.
- Closes #1607 
- Closes #1678
- Minor …

Closes #1607, Closes #1678: Change disable_login_form functionality, disable login form by default, add link to webauth to login form.

---

composer.json

We need to change the composer branch alias for dev-main to now be 2.5.x-dev since main will effectively be 2.5.x once we release 2.4.0-beta1.

#1703 2.4.x release preparations

---

modules/custom/az_course/src/CourseMigrateBatchExecutable.php
modules/custom/az_course/src/CourseSearch.php
modules/custom/az_course/src/Form/CourseImportForm.php
modules/custom/az_course/src/Plugin/migrate_plus/data_fetcher/RetryHttp.php

This addresses a few PHPStan issues that popped up in courses after the new PHPstan PR was added.
#1728 
- enable `az_course` module
- visit `/admin/config/az-quickstart/courses` as an administrator
- add a subject code or course to import to the text area
- e.g. `FCSC` or `FCSC 120`
- run drush migration `drush mim az_course --update`
- visit `/courses`

Fixes #1728 Fix course PHPstan errors.

---

modules/custom/az_paragraphs/az_paragraphs.libraries.yml
modules/custom/az_paragraphs/js/az_paragraphs_full_width.es6.js
modules/custom/az_paragraphs/js/az_paragraphs_full_width.js
modules/custom/az_paragraphs/src/Plugin/paragraphs/Behavior/AZTextWithBackgroundParagraphBehavior.php
modules/custom/az_paragraphs/src/Plugin/paragraphs/Behavior/AZTextWithMediaParagraphBehavior.php

This PR fixes the JavaScript error that occurs when Text with Background or Text on Media paragraphs are added to a page but none are set to full width by doing the following:
- Remove the az_paragraphs.az_paragraphs_full_width library as a dependency for Text with Background and Text on Media
- Update the preprocess function for Text with Background and Text on Media to attach the az_paragraphs.az_paragraphs_full_width library only if the paragraph is set to be full-width.
- Add a test to az_paragraphs_full_width.js to exit the pushSidebarsDown function if there are no full-width elements in the content region.
#1697 
1. Create a page with one or more Text with Background or Text on Media paragraphs. Make sure none of those paragraphs are set to full width.
2. Visit the page
3. Open …

Closes #1697: Fix JS error when Text with Background, Text on Media are not full-width

---

composer.json

Adds patch for known issue affecting the field_group module on Drupal 9.4.x (referenced in the release notes for Drupal 9.4.2).
Closes #1734
Ensure content displays that use field groups still function as expected.

Closes #1734: Add patch for known issue affecting field_group module on 9.4.x.

---

modules/custom/az_paragraphs/js/az_paragraphs_full_width.es6.js
modules/custom/az_paragraphs/js/az_paragraphs_full_width.js
themes/custom/az_barrio/js/button-no-conflict.es6.js
themes/custom/az_barrio/js/button-no-conflict.js

Best viewed while ignoring whitespace https://github.com/az-digital/az_quickstart/pull/1754/files?w=1
Now that we are attaching the full width js (even on the edit form) it is necessary to check whether the main content region exists.
The no-conflict fix is a dependency on the full-width js and also appears before it is possible to use.
Closes #1743 
Edit page with a paragraph that has a full width checkbox.
Javascript empty checking.

Closes #1743 Fix block embeds

---

modules/custom/az_paragraphs/src/Plugin/paragraphs/Behavior/AZTextWithMediaParagraphBehavior.php

Although we replaced the `light` and `dark` classes used by the Text on Media Paragraph behavior in #1713, more references to those classes were added by #1683.
Closes #1742 
Verify that the correct light and dark styles are applied to Text on Media paragraphs using the `bottom` style

Closes #1742: Update references to removed light and dark classes in Text on Media Paragraphs Behavior.

---

composer.json
modules/custom/az_digital_asset_library/az_digital_asset_library.module
modules/custom/az_digital_asset_library/config/install/entity_browser.browser.az_digital_asset_library.yml

Added preprocess functions to hide links for intelligence bank media types in both the media embed dialog and on the add/media page
Closes #1741 
Follow-up PR https://github.com/az-digital/az_quickstart/pull/1752 (Would need to remove changes from this PR)
Waiting on Drupal issue: https://www.drupal.org/project/intelligencebank/issues/3295615
Go to any page content
Add text paragraph
Attempt to embed media
See no option for intelligence bank dam media type
Go to /media/add page
See no option for intelligence bank dam media type
Go to /media/add/ib_dam_embed
See available options (DO NOT USE THOUGH)

Closes #1741 Hide default intelligenceBank Media Type.

---

composer.json

Adds patch to fix IntelligenceBank module issue that breaks non IntelligenceBank/Entity Browser embeds.
See https://www.drupal.org/project/intelligencebank/issues/3299165
Closes #1777 
1. Install Quickstart Digital Asset Library module
2. Ensure embedding entities in text fields in content still works

Closes #1777: Add patch for IntelligenceBank issue breaking entity_embeds.

---

composer.json

Adds core patch for missing (renamed) Backbone JS map file that was fixed in Drupal 9.4.x but not 9.3.x.
https://www.drupal.org/project/drupal/issues/3291283
Closes #1787 
- Disable JS Aggregation
- Verify that no errors/warnings related to a missing `backbone-min.js.map` file are logged in the JS console or Drupal watchdog.

Closes #1787: Restore missing Drupal core backbone-min.js.map file (2.3.x only)

---

az_quickstart.install
composer.json
modules/custom/az_event/config/install/pathauto.pattern.az_event_url_pattern.yml
modules/custom/az_news/config/install/pathauto.pattern.news_content_type.yml
modules/custom/az_person/config/install/pathauto.pattern.az_person_url_pattern.yml

drupal/ctools 4.0.0 is no longer available (Drupal contrib module maintenance fail 🤦🏻‍♂️).
https://www.drupal.org/project/ctools/releases/8.x-3.10
While testing ctools 8.x-3.10 we also realized that our exported Pathauto pattern configs had not all been updated for Drupal 9.3+ and Pathauto 8.x-1.10 compatibility.
- Closes #1790
- Closes #1792 
- Verify `composer install` works
- Verify PHPunit tests pass
- Apply patch to existing site, run DB updates and config distro update, ensure Pathauto patterns work

Closes #1790, Closes #1792: Update Pathauto patterns for Drupal 9.3+ and use drupal/ctools:4.0.1.

---

.github/dependabot.yml

Allow dependabot to have more than 5 PRs open at a time.
Closes #1803
I think we may have to merge this in order to test it.

Closes #1803: Allow more open dependabot PRs.

---

modules/custom/az_migration/migrations/migrate_plus.migration.az_paragraph_html.yml

text_format_recognizer determines if the value of a text field should be added as an html field or az_standard text area.
This works great until there are embedded entities in the source.
Closes #1523 
QS1 Source site with html paragraphs with embedded content.
QS2 Destination site with az_paragraphs_html module enabled
Attempt to migrate az_migration group, see error(or not if this fix is enabled).
Bug fix

Closes #1523 use az_entity_embed_process before passing to text_format_recognizer

---

modules/custom/az_paragraphs/az_paragraphs_photo_gallery/templates/paragraph--az-photo-gallery.html.twig

This PR fixes the twig variable index to address the issue of alt text not rendering on gallery images.
Closes #1844

Closes #1844 - Fix twig variable index for alt text on gallery images

---

.probo.yaml
modules/custom/az_accordion/src/Plugin/Field/FieldFormatter/AZAccordionDefaultFormatter.php
modules/custom/az_card/src/Plugin/Field/FieldFormatter/AZCardDefaultFormatter.php

Fixes deprecation warnings generated by empty card/accordion body (sub)fields.
Related core issue:
https://www.drupal.org/project/drupal/issues/3294680
Closes #1856
- Create a page with a card or accordion paragraph containing at least one card or accordion with an empty body field
- Verify that no warnings like this are shown / logged:
```
Deprecated function: str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in Drupal\filter\Element\ProcessedText::preRenderText() (line 101 of core/modules/filter/src/Element/ProcessedText.php).
```

Closes #1856: Fix deprecation warning caused by empty card/accordion body fields on PHP 8.1+.

---

modules/custom/az_global_footer/az_global_footer.info.yml
modules/custom/az_global_footer/az_global_footer.install
modules/custom/az_global_footer/data/az_global_footer.json

Updates URL of "Global Engagement" link in `az_global_footer` topics menu.  (Changed from https://global.arizona.edu to https://international.arizona.edu).
Adds DB update to update link on existing sites.
Closes #1837
- Verify that the Global Engagement link in the global footer points at https://international.arizona.edu after installing the `az_global_footer` module on a new site (e.g. on ProboCI)
- Apply PR as patch to existing Quickstart site already using the `az_global_footer` module and ensure Global Engagement link URL is updated after running DB updates.

Closes #1837: Update URL of Global Engagement link in global footer.

---

.probo.yaml

Our `Check for PHP errors and notices` ProboCI step is not currently working (due to upgrading to Drush 11).
Closes #1858 
Look at output of ProboCI `Check for PHP errors and notices` in the ProboCI console.

Closes #1858: Fix broken ProboCI 'Check for PHP errors and notices' step.

---

.github/workflows/create-release.yml

Updates 'Create release' GH actions workflow to use revision after committing the changes to `az_quickstart.info.yml` instead of the `HEAD` of the release branch when the action was triggered.
Closes #1903 
We'll need to run this workflow after merging to actually test.

Closes #1903: Tag correct revision during 'Create release' GH actions workflow.

---

composer.json

Adds [CAS module patch](https://www.drupal.org/project/cas/issues/3190842) to hopefully fix reported intermittent CAS login issues.
Closes #1936
Lots of CAS logins (not really testable on Probo)

Closes #1936: Add patch to fix CAS module session handling on Drupal 9.2+.

---

modules/custom/az_core/az_core.services.yml
modules/custom/az_core/src/AZConfigOverride.php

Under some rare circumstances, when using quickstart overrides, Quickstart may not understand that the same module contains non-overrides also, and snapshots them but does not apply them.
#1877 
Verify quickstart overrides are applied to third-party module config without snap-shotting non-override config in the same module and leaving it unused.
Snapshots are stored in  `config_snapshot.snapshot.config_sync.module.my_module_name` collections in the `config` table of the database.

Fixes #1877 Snapshot only Necessary Config on Override

---

modules/custom/az_event/config/install/core.entity_view_display.node.az_event.default.yml

Closes #1830 with the following changes to the Default view display for the AZ Event content type:
1. Update the AZ Event Default display to show When, Where, Contacts, and Attachments headings as h2 elements with the h3 class
2. Change the order of the display to be: Event Photos, When/Where, Subtitle, Event Description, Category, Contacts, Attachments
3. Update the labels and machine names of the field groups on the display to be consistent with other Quickstart view displays
5. Add "mb-5" class to the When/Where row to fix vertical space between it and the event subtitle/description below it
6. Add "pt-2" class to the Category containing div to fix vertical space between it and the event subtitle/description above it
7. Disable the Links field since it doesn't appear to change the …

Closes #1830: Update AZ Event Default view display to fix heading tags, reorder content

---

modules/custom/az_core/src/Plugin/migrate/process/ArrayIntersect.php

In order to use the array_intersect process plugin without enabling az_news_feeds or az_migration, we need to move it into a more general module az_core.
Closes #1974

Closes #1974 Move ArrayIntersect migrate process plugin into az_core from az_news_feeds.

---

composer.json

Alternative fix for #1963 suggested by @joshuasosa in https://github.com/az-digital/az_quickstart/pull/1964#issuecomment-1269123811
Closes #1963 
See whether contextual menus/links are usable for nodes within views (e.g. in event and news listings).

Closes #1963: Add bootstrap_barrio patch for node template contextual menu issue.

---

composer.json

Adds patch for core's `migrate_drupal` module to address a known memory leak that exists in the `DrupalSqlBase` migration plugin (that many of our migration plugins extend):
https://www.drupal.org/project/drupal/issues/3154156
Closes #2002 
Try running our `az_migration` group on environments where crashes happened previously.

Closes #2002: Fix memory leak in core to improve stability of migrations.

---

composer.json

Adds a Drupal Core patch (for Claro theme) to address unusable input fields that are using a "table" format within views. Patch updates Claro CSS.
Review site: https://7b5e2985-cedf-4a13-ab91-3a35916c835d--pr-2034.probo.build/admin/az-person/reorder-people
Closes #2031 
- https://www.drupal.org/project/drupal/issues/3159896#comment-14770958
- https://www.drupal.org/files/issues/2022-02-16/3159896-9-4.x-fix-custom-command.patch
- Visit the Reorder People view
- Click on "show row weights"
- Verify row weight values are visible in input fields

Closes #2031 - Fix unusable row weights in reorder view

---

modules/custom/az_event/config/install/core.entity_view_display.node.az_event.default.yml

This moves the subtitle display below the title on the default display mode.
Closes #2032 
1. Create an event or edit an existing one
2. Complete the subtitle field
3. Observe subtitle is located below event title on default display
Example event: https://1be10c25-5fa3-46cf-8106-cee70b6a5130.probo.build/events/mini-health-screening-phoenix

Closes #2032: Move Event subtitle below title on default display

---

modules/custom/az_metrics/az_metrics.module

This PR adds in the version numbers to our AZ_Metrics module. This should give us better insight in to how different departments around campus are taking advantage of our different releases and also help us to identify sites that are in need of critical security updates.
#2009 
Not sure how to test this.

Closes #2009: Include Quickstart version in az_metrics (when available).

---

modules/custom/az_global_footer/az_global_footer.install
modules/custom/az_paragraphs/az_paragraphs.install
modules/custom/az_paragraphs/az_paragraphs_text_background/az_paragraphs_text_background.install
modules/custom/az_paragraphs/az_paragraphs_text_media/az_paragraphs_text_media.install

As described in [this change record for Drupal core](https://www.drupal.org/node/3201242):
> ... all entity queries on content entities should always include an explicit call to ::accessCheck() prior to the query being executed. For Drupal 10 this will be enforced by throwing an exception if ::accessCheck() is not called.
This PR is based on branch issue/1938. It adds five more calls to accessCheck() for instances of \Drupal::entityQuery() in the Quickstart codebase. This should take care of the remaining entity queries which needed the accessCheck() call.

PR for issue/1938: Include accessCheck() for all entity queries

---

modules/custom/az_event/js/az_calendar_filter.es6.js
modules/custom/az_event/js/az_calendar_filter.js
modules/custom/az_event/src/Plugin/views/filter/AZCalendarFilter.php

Presently, if the exposed filter block for the full calendar appears on a path other than the one the view is on (e.g. `/calendar`) then the calendar cell highlighting for days with events does not work. This is because the javascript cell data information were javascript settings on the view, not the exposed filter.
This PR adds the javascript settings to the filter block as well. Also, since the main use of this is to put the date picker on another page, this PR also adds the feature to the javascript to read the initial filter value (e.g. if we load into the page and a different month than the current one is selected by the filters. Previously, the current month would always be selected.)
#2010 
- Verify calendar still works as expected
- Add calendar exposed filter block to another …

Fixes #2010 Add calendar cell information to non-view paths.

---

composer.json

Quickstart currently does not display the red asterisk for webform fields because a required library is not included by our version of barrio. This has been fixed in [more recent barrio versions](https://www.drupal.org/project/bootstrap_barrio/issues/3133643). Until we update our version of barrio or decide to fork our subtheme we can fix the issue by including a template patch that includes the library.
#2130 
- enable webform and webform UI
- create webform with a required field
- verify that the red asterisk is displayed

Fixes #2130 Barrio webform required field issue.

---

.github/workflows/review-site.yml

Using setting in github actions so that we don't have to waste time waiting for jobs to finish before merging.
This will set the status of each action in the queue as pending during the duration of the jobs ahead of it in line.
Closes #2109 
Merge

Closes #2109 adding concurrency key to queue sequential jobs when merging to main.

---

modules/custom/az_core/drush.services.yml
modules/custom/az_core/src/Commands/AZCoreConfigCommands.php
modules/custom/az_core/src/Plugin/ConfigProvider/QuickstartConfigProvider.php

Sites that have customized permissions are not receiving permission updates when using `config_distro` merge mode. This is due to the fact that merge mode can only merge non-customized array keys, and permissions per role are contained in a single array key (`permissions:`), so `config_distro` will not merge permission changes on sites with custom permissions. This is working as intended, but not very convenient for distribution updates as performing a full reset to apply permissions is not desirable.
This PR adds a `az-core-config-add-permissions` drush command that will add permissions to roles that are missing permissions from the installation profile. It does not remove any custom permissions. It prompts before each addition, but can be made to default to yes with the `-y` switch as …

Fixes #2074 Add drush command for adding missing permissions to Quickstart roles.

---

modules/custom/az_core/src/Plugin/ConfigProvider/QuickstartConfigProvider.php

Currently when modules are disabled in Quickstart, customized entity form displays are being reverted, causing custom fields to become hidden on entity forms. This is a symptom of the fact that Quickstart configuration override modules are reapplying their override each time a module was uninstalled.
Our configuration provider uses the `listConfig()` function to gather information about changing module configuration to know what configuration may need overrides enabled, and when no modules are selected (e.g. no new modules is enabled), it returns all configuration rather than no configuration; this lead to our provider reapplying its overrides on every module uninstall. This PR puts in place a check to make sure the list of extensions isn't an empty array to prevent this.
Additionally, …

Fixes #2201 Custom form display disabled on module uninstall.

---

themes/custom/az_barrio/css/style.css
themes/custom/az_barrio/templates/field/field.html.twig

Default field labels in Quickstart currently appear as plain text and are difficult to distinguish from their surrounding field values.
Presently most of our content types have custom templates of their own, override their field label appearance or by other means customize how their fields look. For custom content types that are not part of quickstart the default appearance of field labels is normal weight text which makes them not very noticeable in the content for custom content types that are relaying on default field appearance.
This results in sites with custom content types often needing to make their own field label customizations.
This PR adds some simple styles to the default field template (h3 for above labels, which is similar to some of our stock content types, and bolded text …

Fixes #2094 Improve markup of default fields.

---

composer.json

Expands the `drupal/smart_date` composer version requirement to support either 3.7.0 or 3.6.1 since 3.7.0 requires PHP 8.0+ which won't be possible for all Quickstart site hosting environments yet.
#2234 
`composer install` on web servers using either PHP 7.4 or 8.0

#2234: Allow smart_date 3.6.1 to be used since 3.7.0 requires PHP 8.0+.

---

composer.json

Backport #2238 for 2.5.x Allow smart_date 3.7.0 to be used if PHP 8.0+ is available.

---

composer.json

Adds [Asset Injector](https://www.drupal.org/project/asset_injector) module to Quickstart as optional module (disabled by default).
Closes #2268

Closes #2268: Add drupal/asset_injector as optional module.

---

themes/custom/az_barrio/theme-settings.php

See https://www.drupal.org/project/drupal/issues/59750
#2288 
Attempt to upload a logo in the az_barrio theme.

Closes #2288 Fix broken az_barrio footer logo field validation

---

modules/custom/az_news/az_news.module

Fixes a bug in the AZ News module that was poisoning the cache metadata on all content types with a `field_az_links` instance in displays without the `az_news_read_more` fieldgroup (i.e. the default full displays for AZ News, AZ Person, AZ Event).
Closes #2312 
- Change a field values on an existing Person, News or Event nodes
- Check to see whether the changes are reflected immediately or not without needing to manually clear caches

Fixes #2312 Changes to existing news, event and person content do not update without clearing cache.

---

composer.json

Downgrades menu_block back to 8.x-1.7 (the version used in Quickstart 2.5.x).  This should resolve the immediate problems identified in issue #2315 for now for sites upgrading to Quickstart 2.6.x and give us time to find a better solution to deal with the larger core issue that is the underlying cause of the issue: https://www.drupal.org/project/drupal/issues/953034
This reverts PR #2049.
Verified that no database or config schema changes exist between 8.x-1.7 and 8.x-1.10.
Closes #2315 
- Add a custom menu
- Add a menu block for the new menu to the sidebar first region
- Verify that an empty sidebar is not displayed for pages not in the menu
- **Other or …

Closes #2315: Downgrade menu_block to 8.x-1.7 until we have a better solution for empty sidebars getting rendered.

---

composer.json

Builds are currently failing because `academicpuma/locales` has reverted to only having a master branch, whereas we require `1.0.0` in our `composer.json`. This is likely related to the fact that `academicpuma/locales` was originally a clone of `citation-style-language/locales` (which was not available on packagist until recently). It appears the maintainer of `academicpuma/locales` may be intending to abandon the package now that `citation-style-language/locales` is available on packagist.
This PR **does not** contain the API-related change of referenced styles discussed in #2313 
#2378 
- Perform a build
- enable `az_publication`
- create a publication
- Verify that publication citations still are displayed
- …

Fixes #2378 Academicpuma/locales abandoned

---

themes/custom/az_barrio/az_barrio.theme
themes/custom/az_barrio/theme-settings.php

Adds a new sidebar position to the Arizona Barrio theme which moves the Sidebar First region below the page content on mobile devices (the `xs` and `sm` Bootstrap breakpoints).
#2368 
[Link to Probo site](https://7b5e2985-cedf-4a13-ab91-3a35916c835d--pr-2369.probo.build/)
1. In the Arizona Barrio theme settings, set the Sidebar position to "Both sides below on mobile".
2. Verify that pages now show the left sidebar below the page content on mobile devices. If the right sidebar is present, it should appear below the left sidebar, at the very bottom.
3. Confirm that there are no other layout changes or problems. …

Closes #2368 Add option to move Sidebar First region below page content on mobile

---

modules/custom/az_publication/az_publication.module

Fixes issue with publication filenames containing special characters getting double-encoded by CiteProc.
Not exactly an ideal fix but seems to work.
Closes #2417 
- Add a file with spaces in the filename to the Publication File field in a publication.
- Ensure the link rendered in the publication citation isn't double-encoded.

Closes #2417: Fix double-encoded publication file URLs.

---

modules/custom/az_event/src/Plugin/migrate/process/SmartDateCreateRecurrenceOnField.php

Fixes a PHP 8 code deprecation error when installing AZ Demo module.
Closes #2382 
Install AZ Demo & check error logs

Closes #2382 - Fix PHP 8 code deprecation in custom smart_date migrate plugin.

---

modules/custom/az_core/config/install/smart_title.settings.yml
modules/custom/az_event/config/install/core.entity_view_display.taxonomy_term.az_event_categories.az_badge.yml
modules/custom/az_flexible_page/config/install/core.entity_view_display.taxonomy_term.az_page_categories.az_badge.yml
modules/custom/az_news/config/install/core.entity_view_display.taxonomy_term.az_news_tags.az_badge.yml

Implemented the az_badge display for all default taxonomy vocabularies so that we can use them in additional displays.
Related to #2406 
Related to #2423 
Related to #2398
Add taxonomy as rendered entity to any display mode, and choose Badge.
Enhancement.

Close #2424 Adding badge display for all default taxonomy vocabularies.

---

modules/custom/az_publication/az_publication.module
modules/custom/az_publication/templates/views-exposed-form--az-publications.html.twig

Publication exposed form filters currently attempt to display them as a flex row all in one line in the Bootstrap large viewport size, with the year field allowed to flex shrink as it doesn't need to be as large as the other text fields. This approach works on the normal large viewport width, but fails when a sidebar is present as it causes the type filter to overlap once the year shrinks too far.
This PR takes an alternate approach and disables the `lg-nowrap` behavior. Instead, the size of the rendered text elements are reduced to have form elements that are not unnecessarily wide to begin with. This creates a situation where they are less likely to need to wrap, but can still wrap if necessary (e.g. pages with sidebars on both sides and similar circumstances.)
Note that this does not …

Fixes #2362 Publication Views exposed filters overlap

---

modules/custom/az_core/config/install/smart_title.settings.yml
modules/custom/az_publication/az_publication.info.yml
modules/custom/az_publication/config/install/core.entity_view_display.node.az_publication.az_card.yml
modules/custom/az_publication/config/install/core.entity_view_display.node.az_publication.default.yml

Presently the publication image media field on publications is not used by any active displays. This PR adds the publication image to the default display, and adds a card display that contains the image, title, and publishing reference.
The image is considered optional and is used for sites that wish to have cover images associated with their publications.
Publication images are not used in bibliographies, i.e. they do not appear in views that use the Publication Reference view mode.
#2439 
- Enable `az_publication` (and `az_demo` optionally, if you want some media images already on the site)
- Create some publications; make sure some have images and publication documents
- Verify that if a publication has an image, it is displayed (in node view) alongside the reference and abstract
- If …

Fixes #2439 Add Publication Image to Full View Display and Card View Display

---

.probo.yaml
az_quickstart.info.yml

Enables the Digital Asset Library integration by default.
#2483 
Open the Probo site and verify that the module is enabled and functional.

Closes #2383 Enable az_digital_asset_library by default

---

.ddev/commands/web/drupal
.lando.yml
CONTRIBUTING.md

Removes lando and ddev tooling for Drupal console since it is not compatible with D10 and is abandoned/not maintained.
Closes #2486 

Closes #2486: Remove tooling for Drupal console 😢.

---

composer.json

CSS Only fix for ckeditor, specifically for chrome.
Fixes #2512 
Using Chrome browser
Create a new page
Add a text area
See if cursor appears when selecting the text area.
Using Other browsers
Create a new page
Add a text area
See if cursor appears when selecting the text area.

Fixes #2512 Cursor missing in new text area on Chrome

---

CONTRIBUTING.md

Announced change:https://uarizona.slack.com/archives/C0SAW6H4J/p1687372251771549
Made change: https://uarizona.slack.com/archives/C0SAW6H4J/p1687372599604809
Updated arizona-bootstrap: https://github.com/az-digital/arizona-bootstrap/pull/793
Searched quickstart.arizona.edu for azdigital-general https://quickstart.arizona.edu/search/node?keys=azdigital-general
#2331

#2331 Update slack channel names from #azdigital-general to #azdigital-support

---

CONTRIBUTING.md

- Announced change:https://uarizona.slack.com/archives/C0SAACCMS/p1687372371857999 
- Made change: https://uarizona.slack.com/archives/C0SAACCMS/p1687372576307579 
- Updated channel topic: https://uarizona.slack.com/archives/C0SAACCMS/p1687373204173049 
- Updated arizona-bootstrap: https://github.com/az-digital/arizona-bootstrap/pull/794 
- Searched quickstart.arizona.edu for friday-meetings https://quickstart.arizona.edu/search/node?keys=friday-meetings
- Searched github for friday-meetings https://github.com/search?q=org%3Aaz-digital%20friday-meetings%20&type=code
- Made change to template repo: https://github.com/az-digital/.github/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc
#2330

#2330 Update slack channel names from #friday-meetings to #azdigital-meetings

---

modules/custom/az_news/az_news.install

Closes #2525 
For sites that are currently ahead of any released version of quickstart. Example dev-main/ RC-1
For sites that applied config distro updates before running the database updates.

Closes #2525 Add error handling to 2.7.x az_news database update.

---

.github/workflows/create-release.yml

Use 2.5.x branch of scaffolding repo when creating release artifact.
#2560

#2560 Update github action to use specific release branch of scaffolding repo

---

.github/workflows/create-release.yml

Use 2.6.x branch of scaffolding repo when creating release artifact.
#2560

#2560 Update github action to use specific release branch (2.6.x) of scaffolding repo

---

.github/workflows/create-release.yml

Use 2.7.x branch of scaffolding repo when creating release artifact.
#2560

#2560 Update github action to use specific release branch (2.7.x) of scaffolding repo

---

modules/custom/az_google_tag/az_google_tag.module

I removed the "/" from the query parameters.
#2617 
Validate that the Analytics Dashboard link in the admin toolbar takes you to the new Looker Studio, and that it doesn't have a "/" or the URL encoded %2F at the end of the domain name.

Closes #2617 Remove the back slash from the analytics dashboard link

---

composer.json

Adds a patch that addresses a bug preventing you from having multiple access schemes in combination with the "Deny access to unassigned content" setting.
Closes #2663 
In a fresh QS build (not using this PR):
- Install Workbench Access
- Add 2 user accounts for testing, and assign them the "Content Editor" role (not "Content Admin")
- Set up a couple sections on the website (or use AZQS demo content)
- In Workbench Access settings, enable the "Deny access to unassigned content" setting
- Create an Access Scheme, using menus, for one section of the site, and assign one of your users to it
- Create another Access Scheme, using menus, for another section of the site, and assign your other user to it
- Use Masquerade to try editing the 2 sections of the site using both editor accounts.
This …

Closes #2663 - Allow multiple access schemes with Workbench Access

---

modules/custom/az_card/src/Plugin/Field/FieldFormatter/AZCardDefaultFormatter.php
modules/custom/az_card/src/Plugin/Field/FieldWidget/AZCardWidget.php

- PR #2641 fixed a deprecation warning generated by `AZCardFieldFormatter` but it turns out `AZCardWidget` also generates the same deprecation warning.  This should fix that deprecation warning.
- I think should also fix an issue with empty card links getting rendered as links to the front page.
Closes #2686 
1. Create flexible page
2. Add cards paragraph
3. Add card with a link title but no link URL
4. Save page
5. View page
6. Verify that link is rendered with an empty `href` attribute (will behave like a link to the current page at least in Chrome)
7. Edit page (no need to save again)
8. Ensure no deprecation warning in logs
- …

Closes #2686 Fix AZCardWidget deprecation warnings and broken default (empty) URL.

---

modules/custom/az_event/config/install/core.entity_view_display.node.az_event.az_row.yml

In the Row display for AZ Event, adds a negative margin for the  Summary Thumbnail field group and a top margin for the Heading field group. This fixes an issue where event rows did not have the proper top padding on mobile devices.
#2713 
Link to Probo site: https://7b5e2985-cedf-4a13-ab91-3a35916c835d--pr-2715.probo.build/
1. Visit the [Calendar page](https://7b5e2985-cedf-4a13-ab91-3a35916c835d--pr-2715.probo.build/calendar)
2. Confirm that event rows have the proper padding above the event title on both mobile and desktop screens

Closes #2713 Event rows without thumbnails are missing top padding on mobile devices

---

composer.json

This PR provides a temporary workaround for an issue located by @bberndt-uaz - an ajax error loading css styles during an ajax request prevents adding paragraphs.
This is happening because the `loadjs` async loader that is newly in use by Drupal `10.1` for css file arrays does not recognize the google font url structure as being a css link, and so it ends up adding it as a script instead.
https://www.drupal.org/project/drupal/issues/3110517 (per @joeparsons )
A more robust workaround for this should be found, but this temporarily works around the issue.
Closes #2772 
See instructions in #2772 
- **Minor …

Fixes #2772 Error loading CSS library prevents adding paragraphs

---

modules/custom/az_core/az_core.libraries.yml
modules/custom/az_core/az_core.module
modules/custom/az_core/css/arizona-bootstrap-node-form-overrides.css
modules/custom/az_core/css/claro-node-form-overrides.css
modules/custom/az_paragraphs/az_paragraphs.libraries.yml

1. Fixes two issues caused by Claro node form styling:
- Fixes the column widths for the main and secondary regions of the node edit form so they match Quickstart 2.7 and before.
- Fixes inconsistent colors for accordion headings.
2. Fixes multiple issues caused by Arizona Bootstrap styling:
- Adds a new `arizona-bootstrap-node-form-overrides` CSS library.
- Fixes font-weight and color issues for links, breadcrumbs, and headings.
- Fixes white background color added to breadcrumb nav element.
- Fixes element size of draggable icon for multi-value fields.
3. Fixes issue caused by absence of AZ Barrio global styling
- Restores `az_barrio/global-styling` dependency to az_paragraphs.preview to fix paragraph rows not being striped.
I'm open to suggestions about better approaches for any of …

Closes #2824 Visual changes to node edit form with 2.8 pre-release

---

modules/custom/az_curated_views/src/Plugin/views/field/AZCuratedViewsField.php

2.8 beta testing revealed that publication curation options cannot be saved, clicking "Save" produces the error "No Action option selected." This is because 10.1's `BulkForm` class which the curation form extends now throws an error if no action is selected.
This PR fixes the issue by overriding the parent class's form validation function to no longer throw an error if no action is selected (as this form does not have actions).
Closes #2851
- enable `az_demo` and `az_publication`
- place the optional block `AZ Publications: Person` on Person content pages
- Create publications, and assign them an author that references a Person
- View that person page
- On the Publications block, select the `Curate Publications` contextual action
- Verify that curation options can be saved and function …

Fixes #2851 Cannot Save Curation Options

---

.github/workflows/security.yml

Closes #2864 
See https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onpushbranchestagsbranches-ignoretags-ignore

Closes #2864  Update security.yml github action to not run on pushing of tags

---

composer.json

Adding a patch for making the subtheme D10 compatible.
Closes #2878 
Attempt to enable the bootstrap barrio subtheme.

Closes #2878 Bootstrap Barrio Subtheme not D10 Compatible.

---

modules/custom/az_media/az_media.module

Since `hook_ckeditor_css_alter` is no longer available, this PR replaces that hook with `hook_library_info_alter` to add the az_media_edit CSS library as a dependency of the CKEditor 5 Media library.
Resolved questions ([see answers in comment from @joeparsons below](#issuecomment-1828617671)):
1. Is it acceptable to rely on the [internal.drupal.ckeditor5.media](https://git.drupalcode.org/project/drupal/-/blob/10.1.x/core/modules/ckeditor5/ckeditor5.libraries.yml?ref_type=heads#L76) library? This was the approach taken by the OEmbed Lazyload module to resolve a [similar issue](https://www.drupal.org/project/oembed_lazyload/issues/3339708).
2. Currently, this PR resolves only the first problem noted in the related issue, where the video thumbnail is too small and only shows the play …

Closes #2946 Video Thumbnail in Page/Event/News Editor Too Small

---

modules/custom/az_event/config/install/core.entity_form_display.node.az_event.default.yml
modules/custom/az_flexible_page/config/install/core.entity_form_display.node.az_flexible_page.default.yml
modules/custom/az_news/config/install/core.entity_form_display.node.az_news.default.yml
modules/custom/az_person/config/install/core.entity_form_display.node.az_person.default.yml
modules/custom/az_seo/config/quickstart/core.entity_form_display.node.az_event.default.yml
modules/custom/az_seo/config/quickstart/core.entity_form_display.node.az_flexible_page.default.yml
modules/custom/az_seo/config/quickstart/core.entity_form_display.node.az_news.default.yml
modules/custom/az_seo/config/quickstart/core.entity_form_display.node.az_person.default.yml

When editing content it is not apparent just how important the summary fields are.
I'v set the summary fieldset to always open on the edit form of each content type that comes with quickstart.
This has been done for 
- az_news
- az_event
- az_flexible_page
- az_person
Closes #2928 
Create or edit any of the following types of content: https://7b5e2985-cedf-4a13-ab91-3a35916c835d--pr-2932.probo.build/user/login?destination=/node/add
- az_news
- az_event
- az_flexible_page
- az_person
Notice the summary section on the right of the screen.

Close #2928 Always show summary fields when adding or editing content.

---

phpunit.xml.dist

Saw this in the PHPUnit output
```
113 Runtime:       PHP 8.1.17
114 Configuration: /src/az-quickstart-scaffolding/web/profiles/custom/az_quickstart/phpunit.xml.dist
115 Warning:       Your XML configuration validates against a deprecated schema.
116 Suggestion:    Migrate your XML configuration using "--migrate-configuration"!
```
This removed the `<filter>` section, possibly because the explaination here: https://github.com/sebastianbergmann/phpunit/issues/5405#issuecomment-1586034679

Update PHPUnit config file using lando phpunit --migrate-configuration

---

modules/custom/az_demo/data/az_demo_image_file.json
modules/custom/az_demo/migrations/az_demo_image_file.yml

Adding uuid as a migrated key, then add uuid to each image I would like to embed in the demo content.
Close #1946 
Before:
After:
Go to https://0d198b4b-4802-431f-bc42-3bd740ced7c9.probo.build/pages/text and see embedded images.

Closes #1946 Embedded images in demo content are not found

---

modules/custom/az_migration/src/Plugin/migrate/process/TextFormatRecognizer.php

In the case of empty paragraphs. or paragraphs with broken markup that is stripped regardless of the selected filter.
Closes #2962

Close #2962 handle empty values in TextFormatRecognizer.php

---

composer.json

Simulated changes that would have been created by [create-pull-request](https://github.com/peter-evans/create-pull-request) GitHub action for the 2.8.x branch.

Prepare 2.8.x branch for new minor release branch 2.9.x

---

modules/custom/az_card/src/Plugin/Field/FieldFormatter/AZCardDefaultFormatter.php

Addresses deprecation warnings caused by cards that have link title values but empty link URL values observed on a Quickstart 2.8.x site.
Closes #3077
1. Add a card deck to a page with at least one card containing a populated link title field and an empty link URL field
2. Save the page
3. View the page
4. Ensure no deprecation warnings were logged in the recent log messages

Closes #3077: Address PHP 8.1+ deprecation warnings caused by card links with empty URLs.

---

composer.json

See https://www.drupal.org/sa-core-2024-001

#3099 Update Drupal core to 10.1.8 for SA-CORE-2024-001 (2.8.x)

---

composer.json

To resolve a problem where a page's parent item in the menu may change when a Content Editor saves the page, this PR adds a patch from comment 20 on the following Workbench Access issue:
- [Content is assigned to wrong menu level if user does not have access to the current level](https://www.drupal.org/project/workbench_access/issues/3187152)
I tested this patch with the demo content: I created a Menu Access Scheme and gave a new Content Editor user access to some specific pages (Split Screen, Menu Blocks - First Child). When I masqueraded as that user and re-saved those pages, their associated menu items did not change.
In contrast, when I saved those pages in another environment using the Quickstart main branch, the menu items for those pages were moved under different parent items: …

Closes #3185 Workbench Access menu schemes may cause menu items to change when pages are saved

---

modules/custom/az_publication/az_publication_import/src/Controller/AZPublicationImportController.php
modules/custom/az_publication/src/Controller/AZAuthorController.php

Autowires controller services using feature added in Drupal 10.2.x.
Associated Drupal 10.2.x change record: https://www.drupal.org/node/3395716
Closes #3016

Closes #3016: Autowire controller services.

---

modules/custom/az_cas/az_cas.services.yml
modules/custom/az_event/az_event_trellis/az_event_trellis.services.yml
modules/custom/az_metrics/az_metrics.services.yml
modules/custom/az_news/az_news_feeds/az_news_feeds.services.yml
modules/custom/az_publication/az_publication_import/az_publication_import.services.yml

Enables auto-configuration feature for event subscribers added in Drupal 10.2.x.
Associated Drupal 10.2.x change record: https://www.drupal.rg/node/3357408
Closes #3018 

Closes #3018: Enable auto-configuration for event subscribers.

---

modules/custom/az_paragraphs/src/Plugin/Field/FieldFormatter/AZBackgroundMediaFormatter.php

`AZBackgroundMediaFormatter` currently assumes it is present on a paragraph entity and causes PHP errors in field displays if on a non-paragraph entity, or paragraph missing the appropriate behaviors.
There is usually no reason for this to occur, but this can accidentally occur on user-defined content types if an entity reference field is disabled and Drupal automatically selects it as the formatter due to weight.
Closes #3234 
- Add a reference field to a node type
- Set the display formatter for the field as `Background Media`
- Create a piece of content of the above node type
- Verify the node can be viewed without PHP errors
- …

Fixes #3234 AZBackgroundMediaFormatter breaks field displays on non-paragraph entities

---

composer.json
modules/custom/az_google_tag/config/install/google_tag.container.az_comprehensive.yml

Exported config from 2.8.x branch.

Backport Update for Google Tag version 2.0.4 to Quickstart 2.8.x branch.

---

modules/custom/az_cas/az_cas.module
modules/custom/az_cas/config/install/az_cas.settings.yml
modules/custom/az_cas/config/schema/az_cas.schema.yml
modules/custom/az_cas/src/Form/AzCasSettingsForm.php

- Changes the text of the "Add CAS User(s)" button on the /admin/people page to be "Add user(s) with NetID"
- Updates the weight of the "Add user(s) with NetID" so it appears first
- Adds a new config setting to the AZ CAS module for optionally disabling (removing) the standard "Add user" button
Closes #3141 
On [ProboCI site](https://7b5e2985-cedf-4a13-ab91-3a35916c835d--pr-3250.probo.build/):
- Login with azadmin or azuseradmin account
- Navigate to /admin/people
- Verify that the "Add CAS User(s)" button has been renamed "Add user(s) with NetID"
- Verify that the "Add user(s) with NetID" button appears first (left of the "Add user" button)
- Navigate to /admin/config/az-quickstart/settings/az-cas
- Turn on "Disable 'Add user' button" setting, save
- Go back to /admin/people
- Verify …

Closes #3141: Customize Add CAS User(s) menu local action and optionally remove standard Add user action.

---

modules/custom/az_demo/config/install/views.view.az_finder.yml
modules/custom/az_demo/config/optional/block.block.az_barrio_exposedformaz_findercontent.yml
modules/custom/az_demo/config/optional/block.block.az_barrio_exposedformaz_finderevent.yml
modules/custom/az_demo/config/optional/block.block.az_barrio_exposedformaz_findernews.yml
modules/custom/az_demo/config/optional/block.block.az_barrio_exposedformaz_finderpage.yml
modules/custom/az_demo/config/optional/block.block.az_barrio_exposedformaz_finderperson.yml

This pull request adds `enforced` configuration to various configuration items within the `az_demo` module. By enforcing these configurations to be dependent on the `az_demo` module, we ensure that they are automatically removed when the module is uninstalled, addressing the issue where the module could not be cleanly reinstalled due to lingering configurations.
- Fixes #3293
1. Install the `az_demo` module.
2. Uninstall the `az_demo` module.
3. Reinstall the `az_demo` module.
4. Confirm that no errors related to pre-existing configuration data are encountered.

Close #3293 Allow reinstallation of az_demo module.

---

modules/custom/az_core/az_core.module
modules/custom/az_seo/config/quickstart/metatag.metatag_defaults.global.yml
modules/custom/az_seo/config/quickstart/metatag.metatag_defaults.node.yml
modules/custom/az_seo/config/quickstart/metatag.metatag_defaults.node__az_event.yml
modules/custom/az_seo/config/quickstart/metatag.metatag_defaults.node__az_news.yml
modules/custom/az_seo/config/quickstart/metatag.metatag_defaults.node__az_person.yml

Updates the default settings for the Metatag contrib module, primarily to:
- Enable social media previews
- Potentially improve SEO
Tasks to complete:
- Currently in Quickstart, if a node doesn't have an external link, the `[node:az-canonical-url]` token returns this URL string internally: `route:entity.node.canonical;node=17`. This string can't be used for a metatag value.
- This PR introduces a new token to return an absolute URL instead, so that the `og:url` tag should always match the `rel="canonical"` link annotation. I tested this on a multidev of a multilingual site and confirmed that each translation of a page has a canonical link set for its specific URL (such as `/some-page` and `/es/some-page`).
- More info on canonical links: …

Closes #2357 Add better metatag defaults for Quickstart

---

modules/custom/az_core/src/AZConfigOverride.php
modules/custom/az_core/src/Plugin/ConfigProvider/QuickstartConfigProvider.php

In #3338 it was found that for some sites that have been active, Quickstart overrides from the new `az_finder` were not being applied to the packaged views. This issue was variable and depended on how the views had been saved and updated on the sites in question, and was not typically exhibited in test builds. It was found in the cases examined that the actual diff was in `cache_metadata` keys of the views which are generated dynamically when views are updated, in some cases.
A potential fix for this is to update `QuickstartConfigProvider` to not consider `cache_metadata` keys when it determines if the configuration item has been customized before applying the override.
Note that this is mostly a convenience change, because the overrides do still become available, they just must be …

Fixes #3347, Fixes #3338 Allow QuickstartConfigProvider to ignore some Diff types.

---

modules/custom/az_carousel/config/install/slick.optionset.center_mode.yml

Hides arrow controls on viewports less than 1310 across.
This is accomplished by adding a second breakpoint to the Slick optionset "Center Mode" that we ship with QS2. The old (and only) breakpoint has been adjusted to no longer show the arrow controls. The new breakpoint is a duplicate of the prior but with arrows enabled. The trigger for the breakpoint is actually 1309 (not 1310) which allows for a pixel-perfect alignment. However, we may choose to set this to 1310 for maintainability purposes.
Maths: 1110 (slide content) + 100 (left arrow) + 100 (right arrow) = 1310px wide
_We could insert some extra padding here if we don't want the arrows to ever touch the active slide. For example, if we did a 1370 breakpoint, this would have the effect of adding 30px of padding to the left and …

Closes #3339 New breakpoint to hide arrows on small displays

---

modules/custom/az_course/config/install/core.entity_form_display.node.az_course.default.yml
modules/custom/az_course/config/install/core.entity_view_display.node.az_course.az_card.yml
modules/custom/az_course/config/install/core.entity_view_display.node.az_course.default.yml
modules/custom/az_course/config/install/core.entity_view_display.node.az_course.teaser.yml
modules/custom/az_course/config/install/field.field.node.az_course.field_az_course_units.yml
modules/custom/az_course/config/install/field.storage.node.field_az_course_units.yml
modules/custom/az_course/config/install/views.view.az_courses.yml
modules/custom/az_course/migrations/az_courses.yml

This PR adds a number of Units field to the course importer and course content type.
#3470 
- enable `az_http` and `az_course`
- visit `/admin/config/az-quickstart/courses`
- Enter a subject code which contains a moderate number of courses, e.g. `PFFP`
- click `Save and Import Courses`
- Wait for the migration to complete
- Visit imported course content or `/courses` and verify the number of course units were successfully imported

Fixes #3470 Additional Course Fields

---

composer.json
config/optional/image.style.max_1300x1300.yml
config/optional/image.style.max_2600x2600.yml
config/optional/image.style.max_325x325.yml
config/optional/image.style.max_650x650.yml
modules/custom/az_core/config/install/image.style.az_enterprise_thumbnail.yml
modules/custom/az_core/config/install/image.style.az_enterprise_thumbnail_small.yml
modules/custom/az_core/config/install/image.style.az_tiny_thumbnail.yml
modules/custom/az_media/config/install/image.style.az_card_image.yml
modules/custom/az_media/config/install/image.style.az_carousel_item.yml
modules/custom/az_media/config/install/image.style.az_full_width_bg_extra_small.yml
modules/custom/az_media/config/install/image.style.az_full_width_bg_large.yml
modules/custom/az_media/config/install/image.style.az_full_width_bg_medium.yml
modules/custom/az_media/config/install/image.style.az_full_width_bg_small.yml
modules/custom/az_media/config/install/image.style.az_large.yml
modules/custom/az_media/config/install/image.style.az_medium.yml
modules/custom/az_media/config/install/image.style.az_modal_image.yml
modules/custom/az_media/config/install/image.style.az_natural.yml
modules/custom/az_media/config/install/image.style.az_small.yml
modules/custom/az_media/config/install/image.style.az_square.yml
modules/custom/az_media/config/install/image.style.az_very_small.yml

Adds webp conversion step to all included image styles, similar to how Drupal core updated all of its included image styles.  See: https://www.drupal.org/node/3421405
```
This release adds a WebP conversion step to all image styles provided by AZ Quickstart and [Drupal core](https://www.drupal.org/node/3421405). A [patch for Drupal core](https://www.drupal.org/project/drupal/issues/3310963) has also been included that the adds a directive to the `.htaccess` file included with Drupal core to ensure the WebP image MIME type is supported.  Sites hosted on Apache web servers may need to [update their .htaccess files](https://www.drupal.org/node/3456338) to take advantage of this improvement.
```
#2635
#3290
Media images / image fields should be rendered as WebP files. …

#2635, #3290: Add WebP conversion step to all included image styles.

---

themes/custom/az_barrio/templates/forms/fieldset.html.twig

Corrects duplicate asterisks on required multi-select fields (i.e., checkboxes, radios, checkboxes other, radios other). 
Closes #3453 
1. Install Webform & Webform UI.
2. Build a Webform with different types of fields.
_Be sure to include some multi-select field types, and mark them as required._
3. View the Webform and verify that multi-select fields no longer have a duplicate asterisk.

Closes #3453 | Remove duplicate required asterisk on Webforms

---

modules/custom/az_event/az_event_trellis/src/Plugin/migrate/source/AZTrellisEventSource.php
modules/custom/az_event/az_event_trellis/src/Plugin/views/field/AZEventTrellisViewsField.php

This PR updates `AZEventTrellisViewsField` to be Workspace aware as per the Parent class (`BulkForm`) which was added in [Add the ability to mark (VBO) actions as workspace-safe](https://www.drupal.org/project/drupal/issues/2986005)in 10.3.
Additionally, a regression is fixed that changed `AZTrellisEventSource` to being a `MigrateProcess` plugin in #3419  
Closes #3556 
Closes #3557 
- enable `az_demo`, `az_enterprise_attributes_import`, `az_event_trellis`
- visit `/admin/trellis-event-importer`
- search for an event
- verify the event can be successfully imported via the Import button at the bottom of the form …

Fixes #3556, Fixes #3557 Regressions in AZEventTrellisViewsField, AZTrellisEventSource

---

modules/custom/az_finder/src/Form/AZFinderSettingsForm.php
modules/custom/az_finder/src/Service/AZFinderOverrides.php
modules/custom/az_finder/src/Service/AZFinderViewOptions.php

This PR, to be merged into the PR for #3420, makes the following changes to the Finder settings form:
1. Updates the text of view display names to have the format: `View label (View display title)`
- Note: As part of the changes for this update, the `origin` key has been removed from the `$overrides` arrays in the settings form code. This key did not seem to be used in any way.
3. Other updates to the text for clarity/consistency:
- Changed dropdown heading from 'Default Display' to 'Default Display of Parent Terms'
- Changed submit button text from 'Override' to 'Add Override'
- Changed section heading from 'Configure Applied Overrides' to 'Configure Added Overrides'
This PR is not directly related to an issue: it is meant to be merged into the …

[Branch for issue/3262] Standardize text on the settings form

---

modules/custom/az_core/src/Plugin/ConfigProvider/QuickstartConfigProvider.php
modules/custom/az_core/tests/src/Functional/ConfigOverrideTest.php

Not sure if this is correct, but it does allow me to override the smtp.settings via az_mail.
Close #3588 
1. Enable az_mail module
2. Go to /admin/config/system/smtp
3. See settings are applied.
Additionally, check the build log for any anomalies.

Close #3588 Allow newly enabled module config to be overridden.

---

modules/custom/az_finder/css/taxonomy-index-tid-widget.css
modules/custom/az_finder/src/Plugin/better_exposed_filters/filter/AZFinderTaxonomyIndexTidWidget.php

The goal of this PR is to establish a more uniform presentation for the taxonomy term filters in the AZ Finder exposed form.
This PR proposes the following styling changes to the AZ Finder exposed form:
1. Adjust the horizontal alignment of filter items so that collapsible parent terms (with plus/minus buttons) and leaf terms (terms with checkboxes and no children) have a matching layout.
- Checkbox items have been converted to `display: flex` as part of this change.
- Similar to the [change we made to footer menu links](https://github.com/az-digital/az_quickstart/issues/1613), the `line-height` of filter items has been reduced to improve the display of multi-line text.
2. Standardize the spacing of nested filter items (whether they are collapsible parent terms or not).
- Nested filter …

Closes #3567 Styling adjustments for the AZ Finder exposed form (AZDIGITAL-158)

---

RELEASES.md
modules/custom/az_core/az_enterprise_attributes_import/az_enterprise_attributes_import.info.yml
modules/custom/az_course/az_course.info.yml
modules/custom/az_curated_views/az_curated_views.info.yml
modules/custom/az_demo/az_demo.info.yml
modules/custom/az_digital_asset_library/az_digital_asset_library.info.yml
modules/custom/az_event/az_event_trellis/az_event_trellis.info.yml
modules/custom/az_finder/az_finder.info.yml
modules/custom/az_http/az_http.info.yml
modules/custom/az_marketing_cloud/az_marketing_cloud.info.yml
modules/custom/az_migration/az_migration.info.yml
modules/custom/az_news/az_news_export/az_news_export.info.yml
modules/custom/az_news/az_news_feeds/az_news_feeds.info.yml
modules/custom/az_paragraphs/az_paragraphs_link_group/az_paragraphs_link_group.info.yml
modules/custom/az_paragraphs/az_paragraphs_views_side_by_side/az_paragraphs_views_side_by_side.info.yml
modules/custom/az_publication/az_publication.info.yml
modules/custom/az_publication/az_publication_bibtex/az_publication_bibtex.info.yml
modules/custom/az_publication/az_publication_doi/az_publication_doi.info.yml
modules/custom/az_publication/az_publication_import/az_publication_import.info.yml

Followup to #2164.  Adds `lifecycle_link`s to all experimental modules.
Closes #3597

Closes #3597: Add lifecycle_link to experimental modules documentation in experimental modules.

---

composer.json

Since Dependabot did not create a PR for the most recent Drupal core release, this PR was created to update drupal/core-recommended from 10.3.1 to 10.3.2.
Big thanks to @trackleft for working on this Drupal core issue which needed an updated patch:
- [filter_autop() returns `<br />` but should return `<br>` for HTML5](https://www.drupal.org/project/drupal/issues/2350049)
https://www.drupal.org/project/drupal/releases/10.3.2
> 
> Drupal 10.3.x will receive security coverage until June 2025.
> 
> **Important update information**
> 
> If you are updating from 10.2.x or earlier and have the [CKEditor …

Closes #3642 Upgrade Drupal core to 10.3.2

---

modules/custom/az_paragraphs/az_paragraphs_views_side_by_side/az_paragraphs_views_side_by_side.info.yml
modules/custom/az_paragraphs/az_paragraphs_views_side_by_side/az_paragraphs_views_side_by_side.install
modules/custom/az_seo/az_seo.info.yml
modules/custom/az_seo/az_seo.install

Disables DB updates added in #3499 and #3446.
```
This update reverts (disables) database updates included in earlier versions of AZQS that were problematic for certain sites (az_seo_update_1021001 and az_paragraphs_views_side_by_side_update_1021001).
```
#3647

#3647: Disable az_seo_update_1021001 and az_paragraphs_views_side_by_side_update_1021001.

---

modules/custom/az_migration/migrations/az_node_news.yml

Added  all of our paragraph migrations as optional dependencies to the az_node_news migration.
Close #3658 
Run a migration on a site with overrides to the az_news content type's paragraph reference field that allows using more than the default paragraphs.

Close #3658 Add all paragraph migrations as optional dependencies of the news node migration.

---

themes/custom/az_barrio/az_barrio.theme

Adds 'minified' option on az_bootstrap_js_info similar to az_bootstrap_css_info to indicate that the file is minified.
#3671 

Closes #3671 Add minified option on az_bootstrap_js_info

---

modules/custom/az_card/css/az-card-title-hover.css
modules/custom/az_card/src/Plugin/Field/FieldFormatter/AZCardDefaultFormatter.php
modules/custom/az_card/templates/az-card.html.twig

Closes #3723 by making these changes:
- Update styling in the `az_card_title_hover` CSS library to target linked card titles.
- Attach the `az_card_title_hover` library to any Cards paragraph with a card that has a link.
- In the card theme template, add the `text-reset` class to all linked titles (since we can take care of this styling with a Bootstrap class).
- #3723
Probo review site: https://7b5e2985-cedf-4a13-ab91-3a35916c835d--pr-3729.probo.build
1. Create a page with four Cards paragraphs to test the following:
- Card title style: Title on image, card title added, link added to Link URL and Link Title
- Card title style: Title on image, card title added, no link
- Card title style: Title within card, card title added, link added to Link URL and Link Title
- Card title style: Title …

Closes #3723 Card title on image is red when the card is not clickable

---

composer.json

Adding patch for cache contexts (https://drupal.org/i/3475039)
Close #3705 
We do not currently know how to reproduce this issue.
Revert patch

For #3705 Menu blocks intermittently not visible to anonymous users after updating to Quickstart 2.11

---

composer.json

Alternative PR for #3725 that adds [custom Drupal core patch](https://gist.github.com/joeparsons/d99b6c6eef240e8eaf768ba79e1c9f1b) that just hard-codes increased WebP conversion quality value in Drupal core's GD image toolkit code.
Closes #3725

Closes #3725: Hard code higher WebP conversion quality setting until configurable for GD in core.

---

modules/custom/az_core/az_core.module
modules/custom/az_core/src/AZConfigOverride.php
modules/custom/az_core/src/Drush/Commands/AZCoreConfigCommands.php
modules/custom/az_core/src/Plugin/ConfigProvider/QuickstartConfigProvider.php
modules/custom/az_core/tests/src/Functional/QuickstartFunctionalTestBase.php
modules/custom/az_course/src/Form/CourseImportForm.php
modules/custom/az_demo/az_demo.module
modules/custom/az_event/az_event_trellis/az_event_trellis.module
modules/custom/az_event/az_event_trellis/src/Entity/AZRecurringImportRule.php
modules/custom/az_event/az_event_trellis/src/EventSubscriber/AZEventTrellisDataSubscriber.php
modules/custom/az_event/az_event_trellis/src/Form/AZRecurringImportRuleForm.php
modules/custom/az_event/az_event_trellis/src/Plugin/migrate/source/AZTrellisEventSource.php
modules/custom/az_event/az_event_trellis/src/Plugin/views/field/AZEventTrellisViewsField.php
modules/custom/az_event/az_event_trellis/src/TrellisHelper.php
modules/custom/az_finder/src/Form/AZFinderSettingsForm.php
modules/custom/az_finder/src/Plugin/better_exposed_filters/filter/AZFinderTaxonomyIndexTidWidget.php
modules/custom/az_finder/src/Plugin/views/exposed_form/QuickstartExposedFilters.php
modules/custom/az_http/src/AZHttpRetryMiddleware.php
modules/custom/az_http/src/Strategy/AZPoliteCacheStrategy.php
modules/custom/az_migration/src/Plugin/migrate/process/MigratedPathLookup.php
modules/custom/az_news/az_news_export/src/Plugin/views/row/AZNewsDataFieldRow.php
modules/custom/az_paragraphs/src/Plugin/migrate/process/ParagraphsBehaviorSettings.php
modules/custom/az_paragraphs/tests/src/Unit/AZVideoEmbedHelperTest.php
modules/custom/az_publication/az_publication.module
modules/custom/az_publication/src/AZAuthorStorage.php
modules/custom/az_publication/src/AZAuthorStorageInterface.php
modules/custom/az_publication/src/Controller/AZAuthorController.php
modules/custom/az_publication/src/Form/AZAuthorRevisionRevertForm.php
modules/custom/az_publication/src/Form/AZAuthorRevisionRevertTranslationForm.php

This PR attempts to resolve sniff errors that are being raised from `slevomat/coding-standard` - it seems like these may have come in from an update to our non-pinned `drupal/core-dev`?
#3737 
- Verify migrations that look up paths still work correctly
- Verify HTTP Cached migrations still work
- Verify that Trellis Event Search/Importer works
- Verify that paragraphs that have behavior settings still work

Fixes #3737 SlevomatCodingStandards

---

modules/custom/az_finder/az_finder.services.yml
modules/custom/az_finder/src/EventSubscriber/AZFinderAjaxResponseSubscriber.php

Adds an Event Subscriber to the AZ Finder module to prevent views using the Quickstart Exposed Form from automatically scrolling to the top of the view content each time a checkbox filter is checked or unchecked.
1. Should we provide an option for this behavior in the AZ Finder settings?
- We will not provide an option at this time. There is a drupal.org issue for this that currently "needs work": [Make Views AJAX scroll to top optional](https://www.drupal.org/project/drupal/issues/3273068). For now, we will implement the fix in this PR without adding a configurable option, since we may want to replace our fix with the Drupal core functionality in the future.
#3744
Probo review site: https://7b5e2985-cedf-4a13-ab91-3a35916c835d--pr-3745.probo.build
1. Compare the scrolling behavior when …

Closes #3744 Prevent views using Quickstart Exposed Filters from scrolling when checkboxes are checked

---

modules/custom/az_core/az_core.module

I've updated the link to be an internal route.
We may want to update the bottom of this page https://quickstart.arizona.edu/site-admin/navigating-administration-section
Close #3765 

Close #3765 Change top-level Quickstart toolbar link to an internal page instead of an external page.

---

modules/custom/az_paragraphs/az_paragraphs_text_media/config/install/core.entity_view_display.paragraph.az_text_media.default.yml
modules/custom/az_paragraphs/css/az_paragraphs_full_width.css

Resolves potential styling issues with Box style Text on Media paragraphs with the following changes:
1. Update the view display for Text on Media paragraphs so that the `.az-full-width-row` div will have `display: flex` regardless of whether or not the paragraph is full-width.
2. Update the `az_paragraphs_full_width` CSS library to allow the full-width paragraph styling to apply to any region, not just the Content region.
- #3773
Probo review site: https://7b5e2985-cedf-4a13-ab91-3a35916c835d--pr-3774.probo.build
1. Create a page with a Text on Media paragraph as the only page element. Use the following settings:
- Do NOT check the "Full width" checkbox
- Set the Content style to Box style
- Set the Space Around Content setting to a large value such as 8 rem
2. Save the page and confirm …

Closes #3773 Styling issues with Box style Text on Media paragraphs

---

modules/custom/az_paragraphs/css/az_paragraphs_az_text_background.css
modules/custom/az_paragraphs/css/az_paragraphs_az_text_media.css
modules/custom/az_paragraphs/css/az_paragraphs_full_width.css

This pull request makes the following changes:
1. In az_paragraphs_full_width.css, reverts a couple changes to selectors made in #3774, so that some specific full-width background styling is applied only to the Content region. (The `.region .az-full-width-row` rule is the only exception.)
- Note: I'm not sure if the styling from the `.region-content .az-full-width-column-content` rule is ever applied: other rules seem to override everything in that rule.
2. To fix an issue with full-width Text with Background paragraphs not using the full width of the page, (a) apply the styling in az_paragraphs_az_text_background.css to all regions instead of just the Content region and (b) move some necessary full-width background styling from az_paragraphs_az_text_media.css to …

Closes #3817 Full-width paragraphs may have wrong width when not in the Content region

---

modules/custom/az_migration/az_migration.module

Reduce unhelpful error messages when developing migrations from drupal 7 Quickstart 1.
Close #1479 
1. Ensure that the d7-kitten site is awake
2. In Probo log into ssh shell
3. Change directory
`cd /var/www/html/sites/migration`
4. Drush migrate status
`drush migrate:status`

Close #1479 exclude Drupal 6 migrations from appearing when running drush migrate:status

---

modules/custom/az_marketing_cloud/az_marketing_cloud.module
modules/custom/az_marketing_cloud/config/install/core.entity_view_display.node.az_news.az_marketing_cloud_30_70_layout.yml
modules/custom/az_marketing_cloud/config/install/core.entity_view_display.node.az_news.az_marketing_cloud_50_50_layout.yml
modules/custom/az_marketing_cloud/config/install/core.entity_view_display.node.az_news.az_marketing_cloud_50_50_layout_image_right.yml
modules/custom/az_marketing_cloud/config/install/core.entity_view_display.node.az_news.az_marketing_cloud_70_30_layout_image_right.yml
modules/custom/az_marketing_cloud/config/install/core.entity_view_display.node.az_news.az_marketing_cloud_hero_layout.yml

This PR changes the Marketing Cloud layouts to use the thumbnail image instead of the featured image.
_Question: If the thumbnail image is not populated, should we fill it in with the placeholder image or the featured image?_
_Answer: Need help with populating with featured image if no thumbnail, and placeholder if no featured image._
```
Marketing Cloud layouts now use the Thumbnail Image field for news images, replacing the previously used Featured Image field, and setting the Featured Image field as the fallback.
```
Closes #3228 
1. Install the AZ Marketing Cloud module
2. Change the thumbnail image on a news item
3. View that news item's marketing cloud layout to observe thumbnail use …

Closes #3228: Change featured image to thumbnail image in Marketing Cloud layouts

---

modules/custom/az_card/src/Plugin/Field/FieldWidget/AZCardWidget.php

Generation of Card widget previews currently does not check if the URL is set before using it. This PR updates the check to verify if the value is present.
#3823 
- Enable `az_demo`
- Visit a node which contains cards, such as `/pages/card-decks`, or create a new page.
- Edit (or add) a card deck
- Create a card which has a link title, but no link URL.
- Save the page
- Edit the page
- Reopen the card deck
- Open and Collapse the individual card several times
- Check `/admin/reports/dblog`
- Verify that `Deprecated function: str_starts_with(): Passing null to parameter #1 ($haystack) of type string is deprecated` is not being generated
- Check for any regressions in card preview functionality
- Verify that a Card Link URL to a public file still works correctly, e.g. …

Fixes #3823 Card Widget Deprecation Notices

---

modules/custom/az_event/config/install/views.view.az_events.yml
modules/custom/az_finder/config/quickstart/views.view.az_events.yml
modules/custom/az_finder/config/quickstart/views.view.az_news.yml
modules/custom/az_finder/config/quickstart/views.view.az_page_by_category.yml
modules/custom/az_finder/config/quickstart/views.view.az_person.yml
modules/custom/az_flexible_page/config/install/views.view.az_page_by_category.yml
modules/custom/az_news/config/install/views.view.az_news.yml
modules/custom/az_person/config/install/views.view.az_person.yml
modules/custom/az_person/config/install/views.view.az_reorder.yml

This adds a stick at top of lists sort criteria to all views.
If this change requires release notes: provide a summary of changes, how to use this change, and any related links. This content will be pasted in the [release notes](https://github.com/az-digital/az_quickstart/releases). Use markdown format to ensure proper pasting of information. [Release notes example](https://github.com/az-digital/az_quickstart/releases/tag/2.11.0)
```
Views of AZ Person, AZ News, AZ Event, and AZ Page are updated to respect the "Sticky at top of lists" setting found on an individual piece of content. Content with this setting will now appear at the top of views.
```
Closes #3850
1. Modify content to check the "Sticky at top of lists" box
2. Add a page …

Closes #3850: Update Quickstart content type views to have sticky at top of lists respected

---

modules/custom/az_event/config/install/views.view.az_events.yml
modules/custom/az_finder/config/quickstart/views.view.az_events.yml

This updates the no results text for AZ Events. Other content types do no have a field for no results.
```
AZ Events are updated to have a `<p>` tag around the no results text. This is needed after the Standard text update in 2.12.0.
```
Closes #3917
- #3917
1. Navigate to an event page or add an Event block to a page
2. Observe no results text for no upcoming or no past events.
3. Ensure spacing below text exists between text and button.

Closes #3917: Update no results views on events

---

modules/custom/az_core/src/Drush/Commands/AZEntityListCommands.php
modules/custom/az_publication/az_publication.module

This PR attempts to address newly broken coding standards issues that came about because of the new release of Drupal/coder
Closes #3974 
Verify that publication date functionality and entity list drush command was not impacted.
Especially, does the entity list drush command still continue to function in Quickstart 2.11.

Fixes #3974 Broken Coding Standards Sniffs

---

modules/custom/az_core/config/quickstart/chosen.settings.yml

Adds a jQuery selector to Chosen: when creating or editing a node that has a main menu option, the dropdown will now use Chosen instead of the regular dropdown menu.
Nodes already in the main menu already get Chosen applied to the dropdown menu. This PR therefore adds parity.
Closes #3003 
1. Visit `/node/add/az_flexible_page`.
2. Open "Menu settings" accordion in the sidebar.
3. Checkmark "Provide a menu link."
4. Click open the "Parent menu" dropdown and see that it uses Chosen module.
The width of the Chosen dropdown menu for Main menu selecting may look too narrow. That's due to default Chosen settings currently setting "Minimum width of widget" to 150px. Instead of the associated CSS using `min-width`, it sets a fixed `width`.
The minimum width might be set when the Chosen menu is in …

Closes #3003: Add menu parent to chosen settings

---

modules/custom/az_paragraphs/az_paragraphs_text_media/az_paragraphs_text_media.libraries.yml
modules/custom/az_paragraphs/az_paragraphs_text_media/config/install/core.entity_view_display.paragraph.az_text_media.preview.yml
modules/custom/az_paragraphs/az_paragraphs_text_media/js/az_paragraphs_az_text_media_vimeo.es6.js
modules/custom/az_paragraphs/az_paragraphs_text_media/js/az_paragraphs_az_text_media_vimeo.js
modules/custom/az_paragraphs/az_paragraphs_text_media/js/az_paragraphs_az_text_media_youtube.es6.js
modules/custom/az_paragraphs/az_paragraphs_text_media/js/az_paragraphs_az_text_media_youtube.js
modules/custom/az_paragraphs/src/Plugin/Field/FieldFormatter/AZBackgroundMediaFormatter.php

This PR is a branch of the `3891-vimeo-remote-video-is-not-supported-as-a-text-on-media-background` branch as tracked in this PR:
- #3981 
This PR is intended to compile some suggestions for that branch:
- Rename the data attribute for the vimeo ID (while still avoiding the name `data-vimeo-id` to prevent an extra iframe from being loaded by the Vimeo player SDK).
- Consolidate some code in AZBackgroundMediaFormatter.php which is the same for both YouTube and Vimeo videos.
- Add the use of core/once to the Vimeo JS code to prevent multiple event listeners from being added to play and pause buttons.
- In the JS code, move the error messaging to a separate function.
- Prevent both Vimeo and YouTube videos from playing on node edit pages by introducing a new `autoplay_remote_video` setting …

[Branch for 3891-vimeo-remote] Various suggestions for Vimeo Text on Media support

---

modules/custom/az_event/az_event_trellis/config/install/migrate_queue_importer.cron_migration.az_event_trellis.yml
modules/custom/az_event/az_event_trellis/src/Plugin/migrate/source/AZTrellisEventSource.php
modules/custom/az_event/az_event_trellis/src/Plugin/views/field/AZEventTrellisViewsField.php

This PR addresses an issue in the trellis event importer that causes events that have been imported to continually be updated, even if they have not changed. This should not be the case, because the migration uses `track_changes: true`
The issue stems from two separate behaviors:
- When drupal migrations run in update mode, they set all rows in the id map to `NEEDS_UPDATE`, and this ignores the track changes behavior. Consequently, this PR avoids running the migrations in update mode. They were previously being run this way both in the periodic queue migration, and the manual import form, resulting in rows being flagged for update.
- At other times, migrations could also be forced to update because lists of trellis event ids in the source plugin could cause alterations to the hash values …

Fixes #3938 Update Trellis events only if content changes

---

modules/custom/az_paragraphs/az_paragraphs_text_media/js/az_paragraphs_az_text_media_vimeo.es6.js
modules/custom/az_paragraphs/az_paragraphs_text_media/js/az_paragraphs_az_text_media_vimeo.js

This PR is a branch of the `3891-vimeo-remote-video-is-not-supported-as-a-text-on-media-background` branch as tracked in this PR:
- #3981 
This PR updates the Vimeo Text on Media JavaScript to resolve issues with sizing of the video iframe element.
- Wrap the behavior JS in a once call so that it is only called once (it was being run 5 times). The once calls for the play and pause buttons are no longer needed.
- Convert setDimensions to a standard function and use it for the initial sizing of the player (after the "bufferend" event) rather than using a separate sizing process
- Move `ratio` property from options to a `defaultRatio` variable (since Vimeo doesn't have a `ratio` property)
- Removed the window onload handler since it never seemed to be called
- Other miscellaneous changes …

[Branch for 3891-vimeo-remote] Further suggestions for Vimeo Text on Media support 

---

modules/custom/az_paragraphs/az_paragraphs_text_media/az_paragraphs_text_media.libraries.yml
modules/custom/az_paragraphs/az_paragraphs_text_media/js/az_paragraphs_az_text_media_youtube.es6.js
modules/custom/az_paragraphs/az_paragraphs_text_media/js/az_paragraphs_az_text_media_youtube.js
modules/custom/az_paragraphs/src/Plugin/Field/FieldFormatter/AZBackgroundMediaFormatter.php

This PR makes the following changes to the Text on Media module:
1. Removes the jQuery and drupalSettings dependencies from the Text on Media YouTube JavaScript library.
2. Updates the library to use Drupal core's once functionality (currently the JS is running 5 times on page load).
3. Separates settings into "defaultSettings" and video-specific "bgVideoSettings":
- `autoplay` is kept as a video-specific setting. It is not added as a playerVar so that we can explicitly control the video playing (and mute it first).
- `start` is always 0, but it is kept as a video-specific setting which we could manipulate in the future if desired.
- `mute` is always true and it is kept as a default setting in the JS.
4. Removes unused default video settings and deprecated YouTube playerVars.
5. Cleans up …

Closes #4118 Refactor Text on Media YouTube JavaScript library

---

modules/custom/az_person/az_person.module

This PR adds `field_az_media_image` to the list of fields that cannot be edited for Persons imported from the profiles API. This was not previously necessary until #4010 because there was no way for a Profile API Person to receive a photo on import.
#4158 
**Profiles Integration (requires Profiles API token to test)**
- enable `az_person_profiles_import` and `az_http`
- `drush cr`
- visit `/admin/config/az-quickstart/settings/az-person-profiles-import` 
- Add your profiles API token
- visit `/admin/content/profiles/import`
- Import several netids. Import a mix of ones that have faculty profiles images and some that do not
- edit an imported person with a photo
- verify that the photo cannot be **removed** (X icon)
- it is intended that you can still click the edit pencil widget and edit …

Fixes #4158 Profiles-imported Person photos should not be editable.

---

modules/custom/az_event/az_event.module
modules/custom/az_event/templates/az-event-calendar-add-button.html.twig
modules/custom/az_event/templates/az-event-view-occurrences-button.html.twig
modules/custom/az_event/templates/field--node--az-event.html.twig

This PR is a branch of the issue/4190 branch as tracked in this PR:
- #4190 
This PR demonstrates an alternate option for displaying the list of event occurrences on an event page. Instead of displaying them in an accordion, this PR places them in a modal in the same way as the Add to Calendar functionality.
This PR also makes some updates to the existing Add to Calendar button styling, mainly to allow the two buttons to appear next to each other. Another improvement is added to make the buttons display with flex for better vertical centering of their contained elements.
Probo review site: https://7b5e2985-cedf-4a13-ab91-3a35916c835d--pr-4208.probo.build
Example events:
- Some future instances, some past, many occurrences: [Weekend Canyon Running …

[Branch of issue/4190] Change event occurrences accordion to a modal

---

modules/custom/az_event/az_event.module
modules/custom/az_event/templates/az-event-calendar-add-button.html.twig
modules/custom/az_event/templates/az-event-view-occurrences-button.html.twig
modules/custom/az_event/templates/field--node--az-event.html.twig

This PR does the following:
- Adds a short description of the recurrence on the page for a recurring event.
- This description will always end with "until <end_date>", where <end_date> is the date of the final occurrence.
- If recurrence instances have been modified or if additional single occurrences have been added to the event date field, help text stating "View all occurrences for exact dates and times." will be added below the recurrence description.
- The description will be automatically translated to the language of the event if that translation is supported by the [Recurr library](/simshaun/recurr).
- Changes the "View all occurrences" accordion to be a modal triggered by a button, just like the "Add to Calendar" modal.
- Updates the heading elements of both modals to be h2 …

Closes #4190: Add a recurrence description to pages for recurring events

---

modules/custom/az_person/templates/horizontal-tabs--node--az-person--group-tabs.html.twig

This PR corrects the value used for the aria-selected attribute on horizontal tabs on AZ Person pages.
- #4253 
https://7b5e2985-cedf-4a13-ab91-3a35916c835d--pr-4254.probo.build
Visit person pages and confirm that the Experience tab has an `aria-selected` attribute value of "true". If the page includes an Interests tab as well, confirm that the value is "false".
- https://7b5e2985-cedf-4a13-ab91-3a35916c835d--pr-4254.probo.build/person/wilbur-wildcat
- https://7b5e2985-cedf-4a13-ab91-3a35916c835d--pr-4254.probo.build/person/wilma-wildcat

Closes #4253: Invalid ARIA attribute on Person tab

---

modules/custom/az_core/css/claro-node-form-overrides.css
themes/custom/az_barrio/css/ckeditor5.css

This PR is a branch of the `4047-when-using-inline-image-text-wrap-bulleted-text-needs-more-left-padding` branch as tracked in this PR:
- #4195
This PR adds some styling to two CSS files:
- claro-node-form-overrides.css: Copies some styling from style.css so the node edit form can match the published page. Also includes styling fixes for sibling list elements, including a `padding-inline-start` value to revert from 0px (the override from the Claro theme) to 40px (from the browser user agent stylesheet).
- ckeditor5.css: Includes the same styling fixes for sibling list elements. Also removes the `margin-right` since that is being added with our Claro overrides now.
This solution seems to work but it would be good to do more testing with varied content to ensure it doesn't cause any …

[Branch for PR 4195] Styling fixes for left-aligned content

---

az_quickstart.install
composer.json

Reverts the removal of jquery_ui_slider and jquery_ui_touch_punch from #4239. These modules remain deprecated and will be removed with Quickstart 2.14.
- #4266

Closes #4266: Revert removal of jquery_ui_slider and jquery_ui_touch_punch

---

modules/custom/az_core/az_core.post_update.php
modules/custom/az_core/az_core.services.yml
modules/custom/az_core/src/AZConfigOverride.php

Updates `AZConfigOverride::importOverrides()` to include step to ensure UUIDs exist on imported config entities.
This should resolve issues we've seen with the following deprecation error showing up in various contexts for override configs:
```
Deprecated function: mb_strtolower(): Passing null to parameter #1 ($string) of type string is deprecated in Drupal\Core\Config\Entity\Query\Condition->compile() (line 39 of core/lib/Drupal/Core/Config/Entity/Query/Condition.php).
```
Closes #2403

Closes #2403: Save UUIDs when importing Quickstart config overrides to prevent deprecation warnings.

---

modules/custom/az_core/az_core.post_update.php

The `az_core_post_update_add_missing_config_uuids` post_update can inadvertently create an empty, plugin-less config entity in cases where one of the config override items has been deleted from the site's active configuration. This is generally uncommon, because many of those overridden entites are critical to Quickstart.
This PR makes the DB post update check to make sure entities actually existed before creating a UUID for them.
#4284 
- Run DB updates on a `2.12.12` site that have had the `search.page.node_search` config forcibly deleted.
- Verify that no new `search.page.node_search` config is created by the update
- **Patch …

Fixes #4284 Check for absent config entities in az_core_post_update_add_missing_config_uuids

---

modules/custom/az_event/az_event_trellis/src/Plugin/views/filter/AZEventTrellisViewsDateFilter.php

The trellis event module does not appear to use the correct timezone for its API requests. This PR adjusts the filters to instead use UTC datetimes.
This makes a difference when searching for events with a time where their UTC time rolls over to a new day (for example, 5:00pm mountain time is midnight the next day on UTC time.
This issue could result in circumstances where searching for a date range for an event could fail to find an event if the range was at the edge of the event's day.
#4319 
- enable `az_event_trellis` and `az_enterprise_attributes_import`
- Identify any trellis event that begins after 5 PM AZ time. (one such event is `a3UKg000000GnHwMAK`, occurred May 6 2025.)
- visit `/admin/trellis-event-importer`
- Select a start date of custom
- Select an event range of **only** …

Fixes #4319 Trellis Event API requests use wrong timezone

---

modules/custom/az_accordion/az_accordion.libraries.yml
modules/custom/az_alphabetical_listing/az_alphabetical_listing.libraries.yml
modules/custom/az_core/az_core.install
modules/custom/az_core/az_core.libraries.yml
modules/custom/az_paragraphs/az_paragraphs.libraries.yml
modules/custom/az_paragraphs/az_paragraphs_splitscreen/az_paragraphs_splitscreen.libraries.yml
modules/custom/az_select_menu/az_select_menu.libraries.yml
themes/custom/az_barrio/az_barrio.libraries.yml
themes/custom/az_barrio/az_barrio.post_update.php
themes/custom/az_barrio/az_barrio.theme
themes/custom/az_barrio/config/install/az_barrio.settings.yml
themes/custom/az_barrio/config/schema/az_barrio.schema.yml
themes/custom/az_barrio/theme-settings.php

```
The `az_barrio/arizona-bootstrap` library is deprecated, if your theme or module depends on it, please update your code to depend on `az_barrio/arizona-bootstrap-css` and/or `az_barrio/arizona-bootstrap-js` instead.
```
Close #1251

Close #1251 separate CSS from JS in Arizona Bootstrap and deprecate az_barrio/arizona-bootstrap library.

---

modules/custom/az_event/az_event.module

Some of the integrations for adding events to calendars depend upon the data being able to fit into the length of a valid url. In events where the body is very long, this can result in request errors.
This PR introduces the following conventions:
- Where available, the summary field will be used
- Where there is no summary, the body field will be used
- In either case, a truncated summary will be generated that is no longer than `text.settings` setting `default_summary_length` (typically 600)
```
When using the Add to Calendar button on events, the event description will now rely on the summary field where available, and be truncated if it is too long.
```
#4327 
- create an event with an extremely long event description
- use the Add to Calendar link, and verify that the added event had …

Fixes #4327 Add to Calendar link fails for Event nodes with long descriptions

---

modules/custom/az_event/az_event.module

Quickstart has custom functionality that causes rendered events in views to  have their date field trimmed so that only the recurrence for the delta associated with that date shows in the rendered event.
This doesn't take into account that not every view has this functionality, and so that views which render the same event in the same display mode can seed the cache with render arrays for that display mode which do not trim the recurrence information. This can currently be seen in #4278 because the finder views do not trim recurrence information.
This can lead to circumstances where the calendar view inherits rendered events that do not have trimmed date fields, leading to calendars showing all the recurrences for a given event.
This PR introduces a cache context for events which cause …

Fixes #4291 AZ Event View Caching

---

modules/custom/az_event/az_event.module

`az_event_preprocess_node` currently assumes an event view will have a delta value for event date. This isn't always the case, as is the case in the `az_finder` content view. This PR adds an additional check to make sure the value exists.
#4621 
- login to site
- visit `/finders/content`
- visit `/admin/reports/dblog`
- Verify no warnings appear regarding `Warning: Undefined property: Drupal\views\ResultRow::$node__field_az_event_date_delta`

Fixes #4621 Event views without delta generate warnings

---

modules/custom/az_event/az_event.module

(cherry picked from commit 64ba7be83076cfcaef4bb132d58f0aba932abc50)
Backport of #4624 
2.x backport of #4624 originally for #4621 

Fixes #4621 Event views without delta generate warnings (2.x backport of #4624)

---

modules/custom/az_event/config/install/core.entity_view_display.node.az_event.az_card.yml
modules/custom/az_event/config/install/core.entity_view_display.node.az_event.az_card_alternate.yml
modules/custom/az_event/config/install/core.entity_view_display.node.az_event.az_row_with_background.yml
modules/custom/az_flexible_page/config/install/core.entity_view_display.node.az_flexible_page.az_card.yml
modules/custom/az_flexible_page/config/install/core.entity_view_display.node.az_flexible_page.az_row.yml
modules/custom/az_flexible_page/config/install/core.entity_view_display.node.az_flexible_page.az_row_with_background.yml
modules/custom/az_news/config/install/core.entity_view_display.node.az_news.az_card.yml
modules/custom/az_news/config/install/core.entity_view_display.node.az_news.az_feature.yml
modules/custom/az_news/config/install/core.entity_view_display.node.az_news.az_marquee.yml
modules/custom/az_news/config/install/core.entity_view_display.node.az_news.az_media_list.yml
modules/custom/az_news/config/install/core.entity_view_display.node.az_news.az_medium_media_list.yml
modules/custom/az_news/config/install/core.entity_view_display.node.az_news.az_minimal_media_list.yml
modules/custom/az_news/config/install/core.entity_view_display.node.az_news.az_row.yml
modules/custom/az_news/config/install/core.entity_view_display.node.az_news.az_row_with_background.yml
modules/custom/az_news/config/install/core.entity_view_display.node.az_news.az_small_row.yml
modules/custom/az_person/config/install/core.entity_view_display.node.az_person.az_row_with_background.yml
modules/custom/az_person/css/az_person.css
modules/custom/az_publication/config/install/core.entity_view_display.node.az_publication.az_card.yml

Closes #4591 
https://review.digital.arizona.edu/arizona-bootstrap/main/docs/5.0/backwards-compatibility/#card-classes
`card-clickable` and `card-clickable-link` are deprecated. This PR updates all content-type view modes that are currently using `card-clickable` to use `stretched-link`'s instead. This PR aims to accomplish this without restructuring any field groups (modifying parent-children relationships); this is to prevent issues later, especially in the case of sites that have added customizations to these card views, when we're upgrading sites from 2.x to 3.x. 
For `az_news`, the view modes were updated before in [commit bda4f36](https://github.com/az-digital/az_quickstart/commit/bda4f360d56bad25eae00e136c05207763f6eff2) to replace use of `card-clickable` with `stretched-link`'s; …

Closes #4591 - Update cases of card-clickable to stretched link

---

modules/custom/az_person/az_person_eds_import/src/Form/AZPersonEDSImportForm.php

Because we merged both #4547 and #4424 independently, we didn't notice that the EDS imports contain a usage of the previous version of Migrate Tools API. This PR updates the EDS Person imports to use the `migrate_tools` 6.1.x API.
Closes #4675 
#4424 
See testing instructions in #4424 

Fixes #4675 Update EDS imports to migrate_tools 6.1.x API

---

themes/custom/az_barrio/az_barrio.info.yml

This PR updates the `ckeditor5-stylesheets` configuration to use **Arizona Bootstrap 5** instead of the older 2.x version.  
It also removes the now-obsolete `ckeditor_stylesheets` key from `az_barrio.info.yml`, since CKEditor 5 does not use this configuration.  
Close #4682
1. Pull this branch and clear caches (`drush cr`).  
2. Edit any content item that uses CKEditor 5.  
3. Inspect the CKEditor iframe styles:  
- Confirm that Arizona Bootstrap **5.x** stylesheet is loaded.  
- Confirm that the az-icons stylesheet is still applied.  
- Ensure that editor styles match frontend styles.  
4. Verify that `ckeditor_stylesheets` no longer exists in `az_barrio.info.yml`.  
5. Confirm no regressions in the WYSIWYG editing experience.
- …

Close #4682 Update ckeditor5-stylesheets to Arizona Bootstrap 5 and remove ckeditor_stylesheets from az_barrio.info.yml 

---

modules/custom/az_core/css/arizona-bootstrap-node-form-overrides.css

Close #4684
I thought about updating
```
// If the field is configured to allow only internal links, add a useful
// element prefix and description.
if (!$this->supportsExternalLinks()) {
$element['uri']['#field_prefix'] = rtrim(Url::fromRoute('<front>', [], ['absolute' => TRUE])->toString(), '/');
$element['uri']['#description'] = $this->t('This must be an internal path such as %add-node. You can also start typing the title of a piece of content to select it. Enter %front to link to the front page. Enter %nolink to display link text only. Enter %button to display keyboard-accessible link text only.', ['%add-node' => '/node/add', '%front' => '<front>', '%nolink' => '<nolink>', '%button' => '<button>']);
}
// If the field is configured to allow both internal and external links,
// show a …
```

Close #4684 add placeholder override to arizona-bootstrap-node-form-overrides.css

---

modules/custom/az_flexible_page/az_flexible_page.module
modules/custom/az_marketing_cloud/templates/page--export--marketing-cloud.html.twig
themes/custom/az_barrio/az_barrio.theme
themes/custom/az_barrio/config/install/az_barrio.settings.yml
themes/custom/az_barrio/templates/layout/page.html.twig
themes/custom/az_barrio/theme-settings.php

This PR is a branch of the issue/4029 branch as tracked in this PR:
- #4104
This PR makes minimal changes to remove the az_barrio_navbar theme setting (formerly az_barrio_navbar_offcanvas). Further improvements could be made in follow-ups to #4104. For example, we may not need to set attributes in the az_barrio_preprocess_page hook function.
https://7b5e2985-cedf-4a13-ab91-3a35916c835d--pr-4694.probo.build/

[Branch of PR 4104] Remove az_barrio_navbar theme setting

---

modules/custom/az_card/src/Plugin/Field/FieldWidget/AZCardWidget.php
modules/custom/az_demo/data/az_demo_card_paragraph.json
modules/custom/az_migration/migrations/az_paragraph_card_deck.yml
modules/custom/az_migration/migrations/az_paragraph_single_card.yml
modules/custom/az_paragraphs/az_paragraphs_cards/az_paragraphs_cards.install

Close #4746 Changing all instances of btn-block to w-100

---

themes/custom/az_barrio/az_barrio.libraries.yml

The backport PR created for #4892  (#4895) has merge conflicts
Turns out the change to deprecate the `az_barrio/material-design-icons-sharp` library was never backported to Quickstart 2.x.
Probably for the best since I don't think we'd want to add the rounded icons library to 2.x.
This updates the deprecation message to say that the deprecation is effective as of 3.0.x instead of 2.14.x
```
The `az_barrio/material-design-icons-sharp` Drupal asset library has been deprecated as of Quickstart 3.0.x and will be removed in Quickstart 3.1.x. Custom modules or themes that utilize this library will need to switch to use `az_barrio/material-symbols-rounded` instead. 
```
Follow-up to #4892 for #4889 …

#4889: Update deprecation message for az_barrio/material-design-icons-sharp library (again).
